### ISSUE TITLE
首谢感谢您的无私分享，我有两个疑问想与您探讨一下！

### ISSUE THREAD

**Issue by wenewzhang** [zfl9/ss-tproxy#1]
第一  这个能不能直接安装在国内的服务器上，因为现在国内很多区域性的问题，这样用户通过VPN或SS连接国内的服务器，就充当了一级的网关的角色！
第二 有没有可以，将所有的dns的请求，全部转发到网关的53上，这样就不用管Client怎么设置dns,都可以正确使用了！

**Comment by zfl9** [comment]
首先回答你的第二个疑问，答案是肯定的，只需使用 iptables 将来自 192.168/16 的 udp/53 包 REDIRECT 至 53 端口；
然后是第一个问题，这是一个很不错的想法，我再思考一下是否可行

**Comment by zfl9** [comment]
**我觉得不好办**，原因如下：
1. 我做透明代理的前提就是所有的内网流量都会流经网关，因此在网关上做手脚非常简单和直接；
2. 而如果部署在国内服务器上，因为服务器在公网环境，我根本无法将所有内网流量流经服务器，除非不使用**透明代理**，只能使用**正向 sock5 代理**（在服务器上安装 ss-local 服务），而这样的话就没有透明代理的意义了；
3. 当然，也不是说没有办法，我们可以使用 VPN 连接我们的国内服务器，然后所有的流量都会经过虚拟的 VPN 网卡发往服务器，完成**透明代理**；
