### ISSUE TITLE
使用haproxy作为ss-server负载分担器，想使用source ip 做负载分担，怎么做。

### ISSUE THREAD

**Issue by Aireed** [zfl9/ss-tproxy#10]
报文流向：  LAN ----》 iptables-->ss-redir-->haproxy--》 ss-server,  
但我发现，haproxy 收到的连接源IP都是本机了，这样就使用不了Haproxy的源IP 负载均衡策略了。

能指点一下有没有什么方法可以ss-redir向haproxy建链的时候，带上代理的真实的内网IP地址？

谢谢

**Comment by zfl9** [comment]
你的 haproxy 运行在 ss-server 服务端上吗？还是允许在与 ss-redir 的同一台机子上？

**Comment by Aireed** [comment]
haproxy与ss-redir 运行在同一台机器上。

**Comment by zfl9** [comment]
我觉得应该将 haproxy 放在 ss-redir 前面，即：
LAN -> iptables -> haproxy -> ss-redir（node1, node2, node3, ...） -> WAN -> GFW -> ss-server

**Comment by Aireed** [comment]
@zfl9 这样做就是要起多个ss-redir吧?  我的目的就是想实现，LAN内的某一台主机的所有通信都被代理到同一台ssserver上。

如果这样的话，我试试看。

**Comment by zfl9** [comment]
这我就不太清楚了。
