### ISSUE TITLE
增加一个选项使得该脚本在chnroute模式下仅修改iptables相关配置

### ISSUE THREAD

**Issue by LitingLin** [zfl9/ss-tproxy#101]
由于某些原因我希望自己配置dnsmasq以及维护ss-redir进程的生命周期，这样更方便调整域名解析策略以及切换服务器节点，也更符合一个模块干一件事的UNIX哲学。

**Comment by zfl9** [comment]
自己开个分支就行了。

**Comment by LitingLin** [comment]
OK，我已经自己改过了，只是提个建议。

**Comment by zfl9** [comment]
这个建议并没有多大的意义，如果真这么改了，那么global/gfwlist模式还不是一样要处理，然后又有人说，要“仅修改dns”的版本，等等。

**Comment by zfl9** [comment]
至于你说的“一个模块只干一件事”，首先ss-tproxy并不是一个“模块”，这本来就是一个“管理脚本”。如果自己有特殊需求无法满足，fork，修改就可以了。
