### ISSUE TITLE
希望新增一个UDP全局代理模式

### ISSUE THREAD

**Issue by cuteSakuraHime** [zfl9/ss-tproxy#105]
希望能够在chnroute/gfwlist模式下，让udp强制走代理，这样可以防止p2p玄学问题出现
和 SSRPlus的游戏增强模式比较类似吧
代码应该也很容易，应该是
`iptables -t nat -A SSTP_RULE -p udp -j REDIRECT --to-ports $proxy_udpport`

**Comment by zfl9** [comment]
> iptables -t nat -A SSTP_RULE -p udp -j REDIRECT --to-ports $proxy_udpport

显然不是 REDIRECT..

**Comment by tefiszx** [comment]
用caddy反代的shadowsocks-v2rayplugin和v2ray没用，再加上套cdn就更没用了。udp转发对于安全级别高的proxy server来说，其实没啥用。但是支持加上这个功能。conf配置加个game模式。

**Comment by zfl9** [comment]
> udp转发对于用caddy反代的shadowsocks-v2rayplugin和v2ray没用，再加上套cdn就更没用了。udp转发对于安全级别高的proxy server来说，其实没啥用。

话不能说太满，没用仅仅是你自己的理解罢了，不要将目光仅仅局限于ss/v2ray。

**Comment by cuteSakuraHime** [comment]
> > iptables -t nat -A SSTP_RULE -p udp -j REDIRECT --to-ports $proxy_udpport
> 
> 显然不是 REDIRECT..，是 TPROXY

抱歉... 我写错了，但是实现的原理应该就是把udp丢到ss-redir开的udp port就可以啦
这样的做真的是可以避免p2p流量穿透不走代理，也就是ssrplus里面的游戏增强模式（
希望作者能加一下啦

**Comment by zfl9** [comment]
过几天再加，现在这几天比较忙。

**Comment by zfl9** [comment]
强制UDP走全局有个问题，dns分流会失效。特别是chnroute模式。

**Comment by cuteSakuraHime** [comment]
DNS可以通过走tcp解析来解决吗？

**Comment by zfl9** [comment]
我感觉没有必要对所有主机的udp都强制走代理。反正这也是个游戏模式，那么我感觉可以仅针对游戏主机进行特殊处理。也就是用iptables规则，仅将游戏主机发出的udp流量（当然也可以有tcp流量）全部重定向到代理进程。

**Comment by zfl9** [comment]
> 我感觉没有必要对所有主机的udp都强制走代理。反正这也是个游戏模式，那么我感觉可以仅针对游戏主机进行特殊处理。也就是用iptables规则，仅将游戏主机发出的udp流量（当然也可以有tcp流量）全部重定向到代理进程。

如果对这种有兴趣，我待会会给一个示例。

**Comment by zfl9** [comment]
不过我仔细想了想，貌似没有这么容易做。。。主要是mode太多，还有tcponly模式，想做通用的有点想复杂。暂时先关了吧，以后有时间再说。

**Comment by zfl9** [comment]
#106 这个先归到这里吧，后续有时间会实现的。
