### ISSUE TITLE
增强：LAN侧访问控制列表的支持

### ISSUE THREAD

**Issue by zfl9** [zfl9/ss-tproxy#106]
目前个人无过多精力实现这个功能。希望有小伙伴们能够提供相关 PR。// TODO

**Comment by cokebar** [comment]
这个repo不知道您看过没，LAN分流方面做的非常完整
https://github.com/shadowsocks/luci-app-shadowsocks/blob/master/files/root/usr/bin/ss-rules
https://github.com/shadowsocks/luci-app-shadowsocks/wiki/Instruction-of-ss-rules

**Comment by lmhdrive** [comment]
大侠你好：非常感谢能提供这么方便的软件！目前遇到2个问题：1、软件使用chnroute模式能正常使用，由于流量有限，希望使用gfwlist模式，但切换到gfwlist模式无法正常使用，youtube能打开网站,但无法显示所有图片，google打不开。客户端上使用ipconfig/flushdns也不行。2、是由于v2ray不好更换代理，我在同网段的另一虚拟机上安装了WINDOWS版本的V2RAY和CLASH并设置好了SOCKS5代理，希望用SS-TPORXY分流时外网直接转到WINDOWS虚拟机的SOCKS5代理端口上，这样更换代理方便些，SS-TPROXY机器只做透明代理，实现分流及智能转发功能，不安装v2ray代理软件了。SS-TPROXY的虚拟机IP为:192.168.2.1,另一个安装WINDOWS版V2RAY和CLASH的虚拟机IP为192.168.2.15，并已经设置好了socks5代理端口为10808。请大侠帮忙看看SS-TPROXY如何设置外网转发到192.168.2.15的SOCKS5代理端口10808上去。非常感谢能帮忙解决！如有机会进行捐助。
