### ISSUE TITLE
如何解决与mwan3双拨共存的问题？

### ISSUE THREAD

**Issue by freechw** [zfl9/ss-tproxy#107]
具体情况为：
openwrt软路由，两条宽带，使用mwan3进行双拨，添加了策略路由，根据运营商ip进行分流。
安装ss-tproxy，使用v2ray的tproxy模式，tcp和udp都做透明代理，所有网络都访问不了。
应该是路由有冲突，不知如何解决？
使用[该文](https://www.dianlujitao.com/2019/04/09/%E5%9C%A8openwrt%E7%BD%91%E5%85%B3%E4%B8%8A%E4%BD%BF%E7%94%A8v2ray%E6%90%AD%E5%BB%BA%E5%9F%BA%E4%BA%8E%E9%BB%91%E5%90%8D%E5%8D%95%E7%9A%84%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86/)的redirect方式，只做tcp透明代理是正常的。

**Comment by zfl9** [comment]
不清楚 mwan3 的实现方式，有谁能介绍下。不然没法解决。

**Comment by rufengsuixing** [comment]
[mwan3_2.6-1_all.zip](https://github.com/zfl9/ss-tproxy/files/4063384/mwan3_2.6-1_all.zip)
[iptmangle.txt](https://github.com/zfl9/ss-tproxy/files/4063391/iptmangle.txt)

**Comment by freechw** [comment]
[这里](https://www.cnblogs.com/nicephil/p/10168065.html)有一篇关于mwan3的原理分析。

**Comment by zfl9** [comment]
暂无时间，先放着。

**Comment by freechw** [comment]
恩，目前只代理tcp，先这么用着，貌似影响也不大。
