### ISSUE TITLE
使用awk取代perl

### ISSUE THREAD

**Issue by rufengsuixing** [zfl9/ss-tproxy#109]
perl太大了
try this
https://github.com/rufengsuixing/gfwlist2dnsmasq-rules

**Comment by cattyhouse** [comment]
perl 是系统内置软件吧? arch/debian/ubuntu都自带的

**Comment by rufengsuixing** [comment]
好吧 我是openwrt 走错位置了

**Comment by cokebar** [comment]
@rufengsuixing try this online file
https://cokebar.github.io/gfwlist2dnsmasq/gfwlist_domain.txt
update weekly.
script:
https://github.com/cokebar/gfwlist2dnsmasq
