### ISSUE TITLE
希望支持ipv4优先策略

### ISSUE THREAD

**Issue by GDoom** [zfl9/ss-tproxy#110]
当网络中同时存在ipv6和ipv4时，终端会优先使用ipv6，但如果没有支持ipv6的代理，ss-tproxy将会使用ipv6直连，导致代理失效。

**Comment by zfl9** [comment]
以下方法自己选择：

1. 使用 iptables 将 ipv6 流量丢弃
2. 使用 sysctl.conf 将 ipv6 全局禁用

**Comment by elvisw** [comment]
可以给远程VPS配置一个IPv6的隧道：https://tunnelbroker.net/
