### ISSUE TITLE
iptables v1.6.2: unknown option "--restore-mark" & "--save-mark"

### ISSUE THREAD

**Issue by peter1123** [zfl9/ss-tproxy#112]
openwrt 18.06
ss-tproxy v4.6

运行的时候报以下错误，请问是需要安装什么样的iptables?
iptables v1.6.2: unknown option "--restore-mark"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.6.2: unknown option "--save-mark"
Try `iptables -h' or 'iptables --help' for more information.

**Comment by zfl9** [comment]
https://github.com/firehol/firehol/issues/49

这种简单问题麻烦动动手，google搜索下。

**Comment by 0neday** [comment]
```
opkg install iptables-mod-conntrack-extra iptables-mod-u32 kmod-ipt-raw kmod-ipt-conntrack iptables-mod-extra iptables-mod-tproxy
```

**Comment by corepro** [comment]
祝你天天开心
