### ISSUE TITLE
透明网关ipv6如何设置？

### ISSUE THREAD

**Issue by lizenghui** [zfl9/ss-tproxy#113]
目前家里的网络是这样的
openwrt路由：192.168.254.1
ubuntu网关：192.168.254.10
已经在openwrt上dnsmasq上配置：
3,192.168.254.10
6,192.168.254.10
将网关和DNS都指向ubuntu 网关。

目前ipv4可以正常透明代理   但ipv6不知如何设置
ubuntu 网关用ipv6可以正常访问国内和科学上网。

**Comment by zfl9** [comment]
ubuntu正常可以v6代理说明代理本身没问题。那么v4咋配的v6就咋配咯。具体看readme。gua或者ula都行，如果想固定网段和网关，那就用ula地址，记得打开v6的snat。
