### ISSUE TITLE
请教: 关于热点共享问题

### ISSUE THREAD

**Issue by ifaws** [zfl9/ss-tproxy#116]
请教，SS-Tproxy与V2Ray搭建的透明代理目前正常运行在树莓派上，需要代理的设备，手动指定网关、DNS和IP地址。如果树莓派开启WiFi热点，并提供DHCP功能，请问在Dnsmasq、Iptables及策略路由的配置上可否提供一些建议？

网络环境
```
               WiFi AP                           
                  |
RaspberryPi -- Switch  -- Router -- INTERNET
                  |       (DHCP)
                Other                           
```

**Comment by zfl9** [comment]
我需要更加详细的信息。

**Comment by zfl9** [comment]
> 如果树莓派开启WiFi热点，并提供DHCP功能，请问在Dnsmasq、Iptables及策略路由的配置

请说明你想什么效果，以及现在遇到什么困难。。

**Comment by ifaws** [comment]
**想达到的效果**
树莓派开启无线热点，客户端通过WiFi连接到树莓派，并通过树莓派的DHCP服务自动获取正确的IP地址及网关地址，然后数据走SS-tproxy和V2Ray搭建的透明代理。

**所做的尝试**
参考文章：[access-point.md](https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md)
网络环境：树莓派eth0，192.168.1.8 255.255.255.0 192.168.1.1
1. 使用Hostapd配置热点
```
root@raspberrypi:/etc/hostapd# cat hostapd.conf
interface=wlan0
driver=nl80211
ssid=Rasp
hw_mode=g
channel=7
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=password
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
```
2. 编辑dhcpcd.conf 配置wlan0为静态IP
```
interface wlan0
    static ip_address=192.168.1.9/24
    nohook wpa_supplicant
```
3. 编辑dnsmasq.conf 配置wlan0上的DHCP
```
dhcp-mac=set:client_is_a_pi,B8:27:EB:*:*:*
dhcp-reply-delay=tag:client_is_a_pi,2
interface=wlan0
dhcp-range=wlan0,192.168.1.201,192.168.1.254,255.255.255.0,24h
dhcp-option=wlan0,option:router,192.168.1.8
dhcp-option=wlan0,option:dns-server,192.168.1.8
```
4. 编辑sysctl.conf 打开ipv4转发
`net.ipv4.ip_forward=1`

5. 至此，我想后面还需要一些转发设置，故来请教。

**Comment by zfl9** [comment]
> 树莓派开启无线热点，客户端通过WiFi连接到树莓派，并通过树莓派的DHCP服务自动获取正确的IP地址及网关地址，然后数据走SS-tproxy和V2Ray搭建的透明代理。

好的，大概情况可概况为下：
1. eth0 接口地址为192.168.1.8/24
2. rpi 的默认网关为192.168.1.1/24
1. wlan0 无线接口上运行着 hostapd
2. 使用 dnsmasq 作为 DHCP 服务器
3. wlan0 接口地址为 192.168.1.9/24
4. dhcp的ip范围为 192.168.1.201-254/24
5. dhcp的dns以及gateway为192.168.1.9/24

大概说几点可能会出问题的地方（只是可能）：
1. dhcp分发的dns和gateway最好设置为192.168.1.9/24，也即wlan0的接口地址
2. 编辑 /etc/ss-tproxy/ss-tproxy.conf 配置文件，将选项 `ipts_set_snat` 设置为 true
3. `net.ipv4.ip_forward=1` 这条配置其实不需要，因为ss-tproxy会自动设置此内核参数

**Comment by ifaws** [comment]
感谢指教，已成功通过WiFi分享透明代理服务，树莓派现在可同时提供WiFi直连以及局域网旁路代理了。

1. 修正dhcpcd.conf，wlan0分配其他网段的静态IP: 192.168.2.1
```
interface wlan0
    static ip_address=192.168.2.1/24
    nohook wpa_supplicant
```
2. 修正dnsmasq.conf配置，使DHCP运行在其他网段。
```
interface=wlan0
dhcp-range=wlan0,192.168.2.2,192.168.2.254,255.255.255.0,24h
dhcp-option=wlan0,option:router,192.168.2.1
dhcp-option=wlan0,option:dns-server,192.168.2.1
```
3. 编辑 /etc/ss-tproxy/ss-tproxy.conf 配置文件，将选项 ipts_set_snat 设置为 true

4. 未追加iptables规则，不影响使用，但网上有文章配置了如下规则：
```
sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE  //同ipts_set_snat设置为true
sudo iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
```

**Comment by zfl9** [comment]
```
sudo iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
```
这两句没必要。
