### ISSUE TITLE
钩子函数应该如何使用

### ISSUE THREAD

**Issue by Angel0726** [zfl9/ss-tproxy#117]
你之后有许多钩子函数，我想问一下该如何使用。proxy_startcmd、proxy_stopcmd添加到哪里。钩子函数的作用，如何进行添加。添加到哪里

**Comment by zfl9** [comment]
![image](https://user-images.githubusercontent.com/22726048/75110233-b87bde80-5666-11ea-969d-13c68f0eca6d.png)
我觉得只要你认真阅读了这段话，就能知道钩子函数 **加在哪里**、**如何添加**。
至于作用，看个人和实际应用场景了，我只能介绍4个钩子函数的执行时机：
- pre_start：代理启动前，将会执行的函数
- post_start：代理启动后，将会执行的函数
- pre_stop：代理停止前，将会执行的函数
- post_stop：代理停止后，将会执行的函数

另外，你说的 `proxy_startcmd` 和 `proxy_stopcmd` 是一个必要配置项，这不是钩子函数。这是用来定义如何启动和停止 **本地透明代理程序** 的命令行而已。我觉得你提出的这些问题，均可以通过阅读 README 解决，你能问出如此问题，只能说未认真阅读 README 而已。

**Comment by Angel0726** [comment]
> ![image](https://user-images.githubusercontent.com/22726048/75110233-b87bde80-5666-11ea-969d-13c68f0eca6d.png)
> 我觉得只要你认真阅读了这段话，就能知道钩子函数 **加在哪里**、**如何添加**。
> 至于作用，看个人和实际应用场景了，我只能介绍4个钩子函数的执行时机：
> 
> * pre_start：代理启动前，将会执行的函数
> * post_start：代理启动后，将会执行的函数
> * pre_stop：代理停止前，将会执行的函数
> * post_stop：代理停止后，将会执行的函数
> 
> 另外，你说的 `proxy_startcmd` 和 `proxy_stopcmd` 是一个必要配置项，这不是钩子函数。这是用来定义如何启动和停止 **本地透明代理程序** 的命令行而已。我觉得你提出的这些问题，均可以通过阅读 README 解决，你能问出如此问题，只能说明你并未认真读。就算如此，你不妨打开 `/etc/ss-tproxy/ss-tproxy.conf` 配置文件看下里面的每一行（注释虽然不算非常详尽，但我表示尽力了）。

对不起，我不是很懂，不过现在明白一点了
