### ISSUE TITLE
启动ss-redir，tcp被监听，但是无法打开google

### ISSUE THREAD

**Issue by Angel0726** [zfl9/ss-tproxy#118]
![image](https://user-images.githubusercontent.com/32816780/75113631-6904c680-5604-11ea-965c-03cfbc88ddf0.png)
ss-redir正常启动
![image](https://user-images.githubusercontent.com/32816780/75113668-a8cbae00-5604-11ea-93a7-3184e60a95f5.png)
tcp被监听，但是无法打开google。

**Comment by Angel0726** [comment]
我是不是需要打开调试日志，如果需要打开调试日志，那日志在哪里怎么打开

**Comment by zfl9** [comment]
自己检查下 udp 端口是否被监听，当然也请打开ss-redir调试日志，加-v选项就行，以及其它的调试日志，具体看readme。多说无益，readme里面都有答案。
