### ISSUE TITLE
ss成功启动，但是无法代理。有偿寻求帮助

### ISSUE THREAD

**Issue by Angel0726** [zfl9/ss-tproxy#119]
我现在怀疑我，代理不成功。我的使用环境是这样子的。在vmware中使用linux，安装shadowsocks-libev，发现代理没有成功。
使用https://ip.tool.chinaz.com 查询ip地址，发现我的地址没有代理成功。![image](https://user-images.githubusercontent.com/32816780/75164589-e0565b00-56d5-11ea-8e5f-b82b66404b36.png)
![image](https://user-images.githubusercontent.com/32816780/75164620-eba98680-56d5-11ea-8b34-2d1d7181c754.png)
结果都是
![image](https://user-images.githubusercontent.com/32816780/75164654-f532ee80-56d5-11ea-8baa-99dc29877ed2.png)
在主机中使用windows，进行代理，是可以的
![image](https://user-images.githubusercontent.com/32816780/75164729-1267bd00-56d6-11ea-9bbb-7bb38888e3be.png)

**Comment by zfl9** [comment]
大哥你没有开启udp relay啊！
![image](https://user-images.githubusercontent.com/22726048/75165211-0115c380-575d-11ea-878d-100f2248ddcf.png)
仔细看看你的ss-redir少了什么参数，`-u`。

**Comment by Angel0726** [comment]
> 大哥你没有开启udp relay啊！
> ![image](https://user-images.githubusercontent.com/22726048/75165211-0115c380-575d-11ea-878d-100f2248ddcf.png)
> 仔细看看你的ss-redir少了什么参数，`-u`。

嗯嗯，你那部分我添加了，但是还没有运行，我主要是想，有没有办法测试ss-redir是否连接到主机。我想对我ss-redir这一步骤操作是否正确做一个检验。

**Comment by zfl9** [comment]
开启tcponly模式试下，修改ss-tproxy.conf，把里面的tcponly设为true

**Comment by Angel0726** [comment]
> 开启tcponly模式试下，修改ss-tproxy.conf，把里面的tcponly设为true

嗯嗯，我一会试一试tcpomly模式。我是用global模型添加了你说的start_cmd和stop_cmd。使用ss-tproxy显示
![image](https://user-images.githubusercontent.com/32816780/75251426-68e50200-578f-11ea-8b02-0a669b0a6cbf.png)
所以我开启了ss-reredir -c   ；然后有使用了命令ss-tproxy start命令。结果发现网络无法使用。ping与curl都无法连接baidu.com
![image](https://user-images.githubusercontent.com/32816780/75251633-d98c1e80-578f-11ea-982f-070f590bcc19.png)
![image](https://user-images.githubusercontent.com/32816780/75251931-7484f880-5790-11ea-9390-f0991ceaa49d.png)

**Comment by zfl9** [comment]
你的系统是不是自动启动了一个dnsmasq进程，去看看。

**Comment by zfl9** [comment]
如果是的话，最好关闭它。

**Comment by Angel0726** [comment]
> 如果是的话，最好关闭它。
是的。如果使用ss-tproxy start之后会有两个dnsmasq进程。使用ss-tproxy stop之后有一个dnsmasq进程。但是我kill 掉dnsmasq之后他会自动启动。不知道该如何解决
![image](https://user-images.githubusercontent.com/32816780/75258899-06dec980-579c-11ea-8238-c794b4744f54.png)
我想问一下，global模式中的dnsmasq是起缓存作用吗？我理解的是dnsmasq在使用chinadns之后，进行缓存IP。但是global中没有用到chinadns

**Comment by Angel0726** [comment]
> 如果是的话，最好关闭它。

望回复

**Comment by zfl9** [comment]
1. ss-tproxy.conf配置文件上传到这，涉及敏感信息打码处理。
2. 如果有代理配置文件，则代理的配置文件也上传，自行打码处理。
3. 执行 ss-tproxy start，终端的相应输出截图发上来
4. 执行 ss-tproxy stop，终端的相应输出截图发上来
5. 然后 ss-tproxy start，执行如下命令测试，结果发上来：
 - `dig www.baidu.com`
 - `dig www.google.com`
 - `curl -4vsSkL https://www.baidu.com`
 - ``curl -4vsSkL https://www.google.com

**Comment by zfl9** [comment]
然后，忘了一点，执行第5条相关的几个测试之前，先修改ss-tproxy.conf，把这几个配置项改为 `true`
- `dnsmasq_log_enable`
- `chinadns_verbose`
- `dns2tcp_verbose`
- 以及代理ss-redir启动参数加上 `-v`，以记录详细日志

然后测试完成之后，这几个日志文件也发过来
- `/var/log/dnsmasq.log`
- `/var/log/chinadns.log`
- `/var/log/dns2tcp.log`
- 以及代理ss-redir的日志文件

**Comment by zfl9** [comment]
涉及到个人隐私信息的内容自行打码处理。

**Comment by Angel0726** [comment]
> 涉及到个人隐私信息的内容自行打码处理。
ss-tproxy.conf
`## mode
mode='global'  # global 模式 (不分流)
#mode='gfwlist' # gfwlist 模式 (黑名单)
# mode='chnroute' # chnroute 模式 (白名单)

## ipv4/6
ipv4='true'     # true:启用ipv4透明代理; false:关闭ipv4透明代理
ipv6='false'    # true:启用ipv6透明代理; false:关闭ipv6透明代理

## tproxy
tproxy='false'  # true:TPROXY+TPROXY; false:REDIRECT+TPROXY

## tcponly
tcponly='false' # true:仅代理TCP流量; false:代理TCP和UDP流量

## selfonly
selfonly='true' # true:仅代理本机流量; false:代理本机及"内网"流量

## proxy
proxy_svraddr4=() # 此处填写了服务器，但是因为涉及隐私所以隐去了
proxy_svraddr6=()        # 服务器的 IPv6 地址或域名，允许填写多个服务器地址，空格隔开
proxy_svrport='80,443,31913'   # 服务器的监听端口，可填多个端口，格式同 ipts_proxy_dst_port
proxy_tcpport='1080'    # ss/ssr/v2ray 等本机进程的 TCP 监听端口，该端口支持透明代理
proxy_udpport='1080'    # ss/ssr/v2ray 等本机进程的 UDP 监听端口，该端口支持透明代理
proxy_startcmd='cmd'     # 用于启动本机代理进程的 shell 命令，该命令应该能立即执行完毕
proxy_stopcmd='cmd'      # 用于关闭本机代理进程的 shell 命令，该命令应该能立即执行完毕

## dns
dns_direct='114.114.114.114'          # 本地 IPv4 DNS，不能指定端口，也可以填组织、公司内部 DNS
dns_direct6='240C::6666'              # 本地 IPv6 DNS，不能指定端口，也可以填组织、公司内部 DNS
dns_remote='8.8.8.8#53'               # 远程 IPv4 DNS，必须指定端口，提示：访问远程 DNS 会走代理
dns_remote6='2001:4860:4860::8888#53' # 远程 IPv6 DNS，必须指定端口，提示：访问远程 DNS 会走代理

## dnsmasq
dnsmasq_bind_port='10053'                  # dnsmasq 服务器监听端口，见 README
dnsmasq_cache_size='4096'               # DNS 缓存大小，大小为 0 表示禁用缓存
dnsmasq_cache_time='3600'               # DNS 缓存时间，单位是秒，最大 3600 秒
dnsmasq_log_enable='true'              # 记录详细日志，除非进行调试，否则不建议启用
dnsmasq_log_file='/var/log/dnsmasq.log' # 日志文件，如果不想保存日志可以改为 /dev/null
dnsmasq_conf_dir=()                     # `--conf-dir` 选项的参数，可以填多个，空格隔开
dnsmasq_conf_file=()                    # `--conf-file` 选项的参数，可以填多个，空格隔开
dnsmasq_conf_string=()                  # 自定义配置，一个数组元素就是一行配置，空格隔开

## chinadns
chinadns_bind_port='65353'               # chinadns-ng 服务器监听端口，通常不用改动
chinadns_timeout='3'                     # 等待上游 DNS 返回响应的超时时间，单位为秒
chinadns_repeat='1'                      # 向可信 DNS 发送几次 DNS 查询请求，默认为 1
chinadns_fairmode='false'                # 使用公平模式，具体看 chinadns-ng 的 README
chinadns_gfwlist_mode='false'            # gfwlist 模式，加载 gfwlist.txt/gfwlist.ext
chinadns_noip_as_chnip='false'           # 启用 chinadns-ng 的 `--noip-as-chnip` 选项
chinadns_verbose='true'                 # 记录详细日志，除非进行调试，否则不建议启用
chinadns_logfile='/var/log/chinadns.log' # 日志文件，如果不想保存日志可以改为 /dev/null
chinadns_privaddr4=()                    # IPv4 私有地址段，多个用空格隔开，具体见 README
chinadns_privaddr6=()                    # IPv6 私有地址段，多个用空格隔开，具体见 README

## dns2tcp
dns2tcp_bind_port='65454'               # dns2tcp 转发服务器监听端口，如有冲突请修改
dns2tcp_verbose='true'                 # 记录详细日志，除非进行调试，否则不建议启用
dns2tcp_logfile='/var/log/dns2tcp.log'  # 日志文件，如果不想保存日志可以改为 /dev/null

## ipts
ipts_if_lo='lo'                 # 环回接口的名称，在标准发行版中，通常为 lo，如果不是请修改
ipts_rt_tab='233'               # iproute2 路由表名或表 ID，除非产生冲突，否则不建议改动该选项
ipts_rt_mark='0x2333'           # iproute2 策略路由的防火墙标记，除非产生冲突，否则不建议改动该选项
ipts_set_snat='false'           # 设置 iptables 的 MASQUERADE 规则，布尔值，`true/false`，详见 README
ipts_set_snat6='false'          # 设置 ip6tables 的 MASQUERADE 规则，布尔值，`true/false`，详见 README
ipts_reddns_onstop='true'       # ss-tproxy stop 后，是否将其它主机发至本机的 DNS 重定向至直连 DNS，详见 README
ipts_proxy_dst_port='1:65535'   # 黑名单 IP 的哪些端口走代理，多个用逗号隔开，冒号为端口范围(含边界)，详见 README

## opts
opts_ss_netstat='auto'                  # auto/ss/netstat，用哪个端口检测工具，见 README
opts_ping_cmd_to_use='auto'             # auto/standalone/parameter，ping 相关，见 README
opts_hostname_resolver='auto'           # auto/dig/getent/ping，用哪个解析工具，见 README
opts_overwrite_resolv='false'           # true/false，定义如何修改 resolv.conf，见 README
opts_ip_for_check_net='114.114.114.114' # 检测外网是否可访问的 IP，ping，留空表示跳过此检查

## file
file_gfwlist_txt='/etc/ss-tproxy/gfwlist.txt'      # gfwlist/chnlist 模式预置文件
file_gfwlist_ext='/etc/ss-tproxy/gfwlist.ext'      # gfwlist/chnlist 模式扩展文件
file_ignlist_ext='/etc/ss-tproxy/ignlist.ext'      # global/chnroute 模式扩展文件
file_chnroute_set='/etc/ss-tproxy/chnroute.set'    # chnroute 地址段文件 (iptables)
file_chnroute6_set='/etc/ss-tproxy/chnroute6.set'  # chnroute6 地址段文件 (ip6tables)
file_dnsserver_pid='/etc/ss-tproxy/.dnsserver.pid' # dns 服务器进程的 pid 文件 (shell)


proxy_startcmd='(ss-redir -c ~/ss-tproxy/shadowsocks.json -u </dev/null &>>/var/log/ss-redir.log &)' # 这里就不记录详细日志了
proxy_stopcmd='kill -9 $(pidof ss-redir)'`

**Comment by zfl9** [comment]
```
## selfonly
selfonly='true' # true:仅代理本机流量; false:代理本机及"内网"流量
```
这条配置确定吗？如果填true，意味着只代理ss-tproxy主机自身的流量，其它主机的流量不会被代理的。

**Comment by Angel0726** [comment]
> ```
> ## selfonly
> selfonly='true' # true:仅代理本机流量; false:代理本机及"内网"流量
> ```
> 
> 
> 这条配置确定吗？如果填true，意味着只代理ss-tproxy主机自身的流量，其它主机的流量不会被代理的。

我目前的需求是自己的电脑访问外网，没有想使用其他电脑进行访问。而且我觉得这样配置起来简单点

**Comment by zfl9** [comment]
那没问题，我只是确认一下

**Comment by Angel0726** [comment]
> 那没问题，我只是确认一下

嗯嗯，为什么没有chinadns和dns2tcp的日志

**Comment by zfl9** [comment]
因为 global 模式不用这两个组件，只有dnsmasq 有日志（dnsmasq只是缓存解析结果）

**Comment by zfl9** [comment]
另外，这两个配置项其实有的， 不是在配置文件末尾加，你看下前面就有同名的两个配置：
```shell
proxy_startcmd='(ss-redir -c ~/ss-tproxy/shadowsocks.json -u </dev/null &>>/var/log/ss-redir.log &)' # 这里就不记录详细日志了
proxy_stopcmd='kill -9 $(pidof ss-redir)'
```

**Comment by zfl9** [comment]
看样子是 /etc/resolv.conf 文件有问题，把这个文件的内容发过来（start前和start后）

**Comment by zfl9** [comment]
我建议你把这个选项 `opts_overwrite_resolv` 改为 true，兼容性好一点。

**Comment by zfl9** [comment]
不对，仔细看日志，似乎解析请求已经被dnsmasq接收了，那么也可能是你的ss服务器不支持 udp 转发导致的。你开启 tcponly 模式，再试一下。同样的，要把测试过后的日志文件（dnsmasq、dns2tcp、ss-redir）日志发过来。还有你的上述配置中 ss-redir 的启动参数要带上 `-v` 才能看到详尽的日志。

**Comment by Angel0726** [comment]
> 不对，仔细看日志，似乎解析请求已经被dnsmasq接收了，那么也可能是你的ss服务器不支持 udp 转发导致的。你开启 tcponly 模式，再试一下。同样的，要把测试过后的日志文件（dnsmasq、dns2tcp、ss-redir）日志发过来。还有你的上述配置中 ss-redir 的启动参数要带上 `-v` 才能看到详尽的日志。

ss-redir  日志模式是这样添加吗？
proxy_startcmd='(ss-redir -c ~/ss-tproxy/shadowsocks.json -v -u </dev/null &>>/var/log/ss-redir.log &)'

**Comment by zfl9** [comment]
是的

**Comment by Angel0726** [comment]
> 不对，仔细看日志，似乎解析请求已经被dnsmasq接收了，那么也可能是你的ss服务器不支持 udp 转发导致的。你开启 tcponly 模式，再试一下。同样的，要把测试过后的日志文件（dnsmasq、dns2tcp、ss-redir）日志发过来。还有你的上述配置中 ss-redir 的启动参数要带上 `-v` 才能看到详尽的日志。

# 配置
```
## mode
mode='global'  # global 模式 (不分流)
#mode='gfwlist' # gfwlist 模式 (黑名单)
# mode='chnroute' # chnroute 模式 (白名单)

## ipv4/6
ipv4='true'     # true:启用ipv4透明代理; false:关闭ipv4透明代理
ipv6='false'    # true:启用ipv6透明代理; false:关闭ipv6透明代理

## tproxy
tproxy='false'  # true:TPROXY+TPROXY; false:REDIRECT+TPROXY

## tcponly
tcponly='true' # true:仅代理TCP流量; false:代理TCP和UDP流量

## selfonly
selfonly='true' # true:仅代理本机流量; false:代理本机及"内网"流量

## proxy
proxy_svraddr4=(这里填域名没有用，只能写ip地址) # 服务器的 IPv4 地址或域名，允许填写多个服务器地址，空格隔开
proxy_svraddr6=()        # 服务器的 IPv6 地址或域名，允许填写多个服务器地址，空格隔开
proxy_svrport='80,443,31913'   # 服务器的监听端口，可填多个端口，格式同 ipts_proxy_dst_port
proxy_tcpport='1080'    # ss/ssr/v2ray 等本机进程的 TCP 监听端口，该端口支持透明代理
proxy_udpport='1080'    # ss/ssr/v2ray 等本机进程的 UDP 监听端口，该端口支持透明代理
proxy_startcmd='(ss-redir -c ~/ss-tproxy/shadowsocks.json -v -u </dev/null &>>/var/log/ss-redir.log &)'     # 用于启动本机代理进程的 shell 命令，该命令应该能立即执行完毕
proxy_stopcmd='kill -9 $(pidof ss-redir)'      # 用于关闭本机代理进程的 shell 命令，该命令应该能立即执行完毕

## dns
dns_direct='114.114.114.114'          # 本地 IPv4 DNS，不能指定端口，也可以填组织、公司内部 DNS
dns_direct6='240C::6666'              # 本地 IPv6 DNS，不能指定端口，也可以填组织、公司内部 DNS
dns_remote='8.8.8.8#53'               # 远程 IPv4 DNS，必须指定端口，提示：访问远程 DNS 会走代理
dns_remote6='2001:4860:4860::8888#53' # 远程 IPv6 DNS，必须指定端口，提示：访问远程 DNS 会走代理

## dnsmasq
dnsmasq_bind_port='10053'                  # dnsmasq 服务器监听端口，见 README
dnsmasq_cache_size='4096'               # DNS 缓存大小，大小为 0 表示禁用缓存
dnsmasq_cache_time='3600'               # DNS 缓存时间，单位是秒，最大 3600 秒
dnsmasq_log_enable='true'              # 记录详细日志，除非进行调试，否则不建议启用
dnsmasq_log_file='/var/log/dnsmasq.log' # 日志文件，如果不想保存日志可以改为 /dev/null
dnsmasq_conf_dir=()                     # `--conf-dir` 选项的参数，可以填多个，空格隔开
dnsmasq_conf_file=()                    # `--conf-file` 选项的参数，可以填多个，空格隔开
dnsmasq_conf_string=()                  # 自定义配置，一个数组元素就是一行配置，空格隔开

## chinadns
chinadns_bind_port='65353'               # chinadns-ng 服务器监听端口，通常不用改动
chinadns_timeout='3'                     # 等待上游 DNS 返回响应的超时时间，单位为秒
chinadns_repeat='1'                      # 向可信 DNS 发送几次 DNS 查询请求，默认为 1
chinadns_fairmode='false'                # 使用公平模式，具体看 chinadns-ng 的 README
chinadns_gfwlist_mode='false'            # gfwlist 模式，加载 gfwlist.txt/gfwlist.ext
chinadns_noip_as_chnip='false'           # 启用 chinadns-ng 的 `--noip-as-chnip` 选项
chinadns_verbose='true'                 # 记录详细日志，除非进行调试，否则不建议启用
chinadns_logfile='/var/log/chinadns.log' # 日志文件，如果不想保存日志可以改为 /dev/null
chinadns_privaddr4=()                    # IPv4 私有地址段，多个用空格隔开，具体见 README
chinadns_privaddr6=()                    # IPv6 私有地址段，多个用空格隔开，具体见 README

## dns2tcp
dns2tcp_bind_port='65454'               # dns2tcp 转发服务器监听端口，如有冲突请修改
dns2tcp_verbose='true'                 # 记录详细日志，除非进行调试，否则不建议启用
dns2tcp_logfile='/var/log/dns2tcp.log'  # 日志文件，如果不想保存日志可以改为 /dev/null

## ipts
ipts_if_lo='lo'                 # 环回接口的名称，在标准发行版中，通常为 lo，如果不是请修改
ipts_rt_tab='233'               # iproute2 路由表名或表 ID，除非产生冲突，否则不建议改动该选项
ipts_rt_mark='0x2333'           # iproute2 策略路由的防火墙标记，除非产生冲突，否则不建议改动该选项
ipts_set_snat='false'           # 设置 iptables 的 MASQUERADE 规则，布尔值，`true/false`，详见 README
ipts_set_snat6='false'          # 设置 ip6tables 的 MASQUERADE 规则，布尔值，`true/false`，详见 README
ipts_reddns_onstop='true'       # ss-tproxy stop 后，是否将其它主机发至本机的 DNS 重定向至直连 DNS，详见 README
ipts_proxy_dst_port='1:65535'   # 黑名单 IP 的哪些端口走代理，多个用逗号隔开，冒号为端口范围(含边界)，详见 README

## opts
opts_ss_netstat='auto'                  # auto/ss/netstat，用哪个端口检测工具，见 README
opts_ping_cmd_to_use='auto'             # auto/standalone/parameter，ping 相关，见 README
opts_hostname_resolver='auto'           # auto/dig/getent/ping，用哪个解析工具，见 README
opts_overwrite_resolv='false'           # true/false，定义如何修改 resolv.conf，见 README
opts_ip_for_check_net='114.114.114.114' # 检测外网是否可访问的 IP，ping，留空表示跳过此检查

## file
file_gfwlist_txt='/etc/ss-tproxy/gfwlist.txt'      # gfwlist/chnlist 模式预置文件
file_gfwlist_ext='/etc/ss-tproxy/gfwlist.ext'      # gfwlist/chnlist 模式扩展文件
file_ignlist_ext='/etc/ss-tproxy/ignlist.ext'      # global/chnroute 模式扩展文件
file_chnroute_set='/etc/ss-tproxy/chnroute.set'    # chnroute 地址段文件 (iptables)
file_chnroute6_set='/etc/ss-tproxy/chnroute6.set'  # chnroute6 地址段文件 (ip6tables)
file_dnsserver_pid='/etc/ss-tproxy/.dnsserver.pid' # dns 服务器进程的 pid 文件 (shell)

```

**Comment by zfl9** [comment]
为什么你的dig和curl不使用127.0.0.1作为dns server。而是193.138.218.74。这明显是start之前的dns-server啊，诡异。

**Comment by zfl9** [comment]
你仔细看这个输出：
```
[03:29:56] kodachi@Live-OS:~/ss-tproxy $ dig www.google.com

; <<>> DiG 9.11.3-1ubuntu1.9-Ubuntu <<>> www.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62748
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		245	IN	A	67.228.102.32

;; Query time: 24 msec
;; SERVER: 193.138.218.74#53(193.138.218.74)
;; WHEN: Fri Feb 28 03:30:26 +04 2020
;; MSG SIZE  rcvd: 48
```
请解决了这个问题在看后续的。正常来说，start之后，dig任何域名这里显示的都是127..0.1.

**Comment by zfl9** [comment]
还是你这系统太诡异了，live-os 是什么

**Comment by Angel0726** [comment]
> 还是你这系统太诡异了，live-os 是什么

是U盘直接启动的。没有安装，估计跟这个没多大关系吧。昨天我有ubuntu试了试一样，就是没有开启tcp only模式

**Comment by Angel0726** [comment]
> 你仔细看这个输出：
> 
> ```
> [03:29:56] kodachi@Live-OS:~/ss-tproxy $ dig www.google.com
> 
> ; <<>> DiG 9.11.3-1ubuntu1.9-Ubuntu <<>> www.google.com
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62748
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
> 
> ;; QUESTION SECTION:
> ;www.google.com.			IN	A
> 
> ;; ANSWER SECTION:
> www.google.com.		245	IN	A	67.228.102.32
> 
> ;; Query time: 24 msec
> ;; SERVER: 193.138.218.74#53(193.138.218.74)
> ;; WHEN: Fri Feb 28 03:30:26 +04 2020
> ;; MSG SIZE  rcvd: 48
> ```
> 
> 请解决了这个问题在看后续的。正常来说，start之后，dig任何域名这里显示的都是127.0.0.1.
> 
> ```
> ;; SERVER: 193.138.218.74#53(193.138.218.74)
> ```

server不应该是gooele的服务器地址吗？

**Comment by zfl9** [comment]
我不要“估计”，server是指dns-server的ip，因为/etc/resolv.conf指定了127.0.0.1，但是dig/curl等等居然不用这个，还是用原来的（你仔细看你start前的resolv.conf内容）。你用正常系统测试。请停止你的live-os测试

**Comment by zfl9** [comment]
> > 你仔细看这个输出：
> > ```
> > [03:29:56] kodachi@Live-OS:~/ss-tproxy $ dig www.google.com
> > 
> > ; <<>> DiG 9.11.3-1ubuntu1.9-Ubuntu <<>> www.google.com
> > ;; global options: +cmd
> > ;; Got answer:
> > ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62748
> > ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
> > 
> > ;; QUESTION SECTION:
> > ;www.google.com.			IN	A
> > 
> > ;; ANSWER SECTION:
> > www.google.com.		245	IN	A	67.228.102.32
> > 
> > ;; Query time: 24 msec
> > ;; SERVER: 193.138.218.74#53(193.138.218.74)
> > ;; WHEN: Fri Feb 28 03:30:26 +04 2020
> > ;; MSG SIZE  rcvd: 48
> > ```
> > 
> > 
> > 请解决了这个问题在看后续的。正常来说，start之后，dig任何域名这里显示的都是127.0.0.1.
> > ```
> > ;; SERVER: 193.138.218.74#53(193.138.218.74)
> > ```
> 
> server不应该是gooele的服务器地址吗？

你自己好好理解 dig 的输出吧，; ANSWER SECTION: 才是解析结果。记住，要走127.0.0.1（也就是dnsmasq）然后才会走到ss-redir，才会走代理出去，你这个走的都是193.138.218.74（国内xxdns），curl google.com能成功就有鬼了

**Comment by Angel0726** [comment]
> 我不要“估计”，server是指dns-server的ip，因为/etc/resolv.conf指定了127.0.0.1，但是dig/curl等等居然不用这个，还是用原来的（你仔细看你start前的resolv.conf内容）。你用正常系统测试。请停止你的live-os测试

我一会试一下ubuntu。但是为了安全起见最后会用live os。请问如果配置dsnmasq会不会有效果

**Comment by Angel0726** [comment]
> 你自己好好理解 dig 的输出吧，; ANSWER SECTION: 才是解析结果。记住，要走127.0.0.1（也就是dnsmasq）然后才会走到ss-redir，才会走代理出去，你这个走的都是193.138.218.74（国内xxdns），curl google.com能成功就有鬼了

那百度国内是可以dns的为什么也不行
