### ISSUE TITLE
能考虑加入adblock功能吗

### ISSUE THREAD

**Issue by tankren** [zfl9/ss-tproxy#121]
不知道工作量多大所以也就是随口问一下，非刚需。不知道是否可以在DNS层面把广告的url给nxdomain响应来屏蔽广告，兼容常见的adlist即可。
谢谢开发者的所有努力。

**Comment by zfl9** [comment]
目前个人没有时间和精力实现，广告屏蔽，目前只能靠dnsmasq的自定义配置过滤部分广告。
