### ISSUE TITLE
不能启动dnsmasq，为stop状态

### ISSUE THREAD

**Issue by matthuo333** [zfl9/ss-tproxy#124]
启动ss-tproxy 中，报如下错误， 暂时使用global模式，请问影响透明代理使用么？
P.S. 使用Qnap 的 docker环境.

iptables v1.6.2: can't initialize iptables table `nat': Permission denied (you must be root)                                                                                                                                          
Perhaps iptables or your kernel needs to be upgraded.                                                                                                                                                                                 
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
iptables v1.6.2: can't initialize iptables table `raw': Permission denied (you must be root)                                                                                                                                          
Perhaps iptables or your kernel needs to be upgraded.                                                                                                                                                                                 
iptables v1.6.2: can't initialize iptables table `raw': Permission denied (you must be root)                                                                                                                                          
Perhaps iptables or your kernel needs to be upgraded.                                                                                                                                                                                 
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted                                                                                                                                                                                  
getsockopt failed strangely: Operation not permitted

**Comment by zfl9** [comment]
这提示不是很明显吗，你需要用root用户执行脚本。

**Comment by matthuo333** [comment]
> 这提示不是很明显吗，你需要用root用户执行脚本。

whoami 后是 root

**Comment by zfl9** [comment]
那问题岂不是更明显？你这系统/环境有问题。

**Comment by matthuo333** [comment]
> 那问题岂不是更明显？你这系统/环境有问题。

怎么fix?

**Comment by zfl9** [comment]
问对人了，我也不知道:joy:

**Comment by zfl9** [comment]
你这何止是dnsmasq无法启动，你是iptables都没权限执行。你说有问题没？
