### ISSUE TITLE
我的网关上运行一个web网站，安装完SS-TPROXY后就无法访问了，请问如何解决？

### ISSUE THREAD

**Issue by lmhdrive** [zfl9/ss-tproxy#128]
您的软件非常好，感谢能为我们提供这个优秀的软件。目前使用上遇到一个问题：我的网关上运行一个web网站，安装完SS-TPROXY后就无法访问了，输入域名以后打不开，PING一下就是代理服务器的地址，给代理到国外了。本机输入IP地址可以访问，输入域名就代理到国外了，域名使用的是DDNS，也就是IP不固定。请问如何把这个域名或几个域名加入白名单，DNS解析时还有访问时都不走代理？

**Comment by zfl9** [comment]
`/etc/ss-tproxy/ignlist.ext`

**Comment by lmhdrive** [comment]
我把域名和IP加到了白名单，还是不行，模式也没问题，chnroute模式。我群晖NAS地址是：192.168.1.100：5001，设置网关是192.168.2.252，网关上安装V2RAY和SS-TPROXY，把网关改成路由器的地址192.168.2.1就都正常了。

**Comment by zfl9** [comment]
那麻烦给出具体的配置，以及网络拓补。以及具体的问题描述，你上面的描述模棱两可，究竟是外部网络无法访问你的web服务，还是内网中无法访问你的web服务。请给我一个清晰的问题描述。

**Comment by zfl9** [comment]
另外脚本是最新的吗

**Comment by lmhdrive** [comment]
脚本是最新版，NAS:192.168.1.100  路由器地址：192.168.1.1（内网） 192.168.2.3（外部地址）   光猫地址：192.168.2.1（内网） 外部地址是：公网IP（106.15.*.*）   正常上网是端口映射都做好了。外面能连接到NAS。虚拟机地址：192.168.2.252，虚拟机中安装的V2RAY翻q和SS-TPROXY。把网关设置成虚拟机192.168.2.252可以实现透明代理也可以翻q，但外网访问不了NAS了。

**Comment by zfl9** [comment]
你最后说的把网关设为SSTP主机，是指将NAS的网关设为SSTP主机还是什么？描述清楚点。

**Comment by lmhdrive** [comment]
端口映射是:光猫192.168.2.1:5000->路由192.168.1.1:5000->NAS192.168.1.100:5000，分别在光猫和路由上配置好了。网关改成虚拟机就映射不了了。在光猫上把映射改到虚拟机192.168.2.252也访问不了NAS。ping NAS的IP依然是外网IP

**Comment by lmhdrive** [comment]
NAS的网关都没改都是原来的路由IP:192.168.1.1

**Comment by zfl9** [comment]
那你说的网关改为SSTP主机是啥，在说一次，麻烦给我一个清楚的无歧义的描述！

**Comment by lmhdrive** [comment]
只在路由器上把原来的网关192.168.2.1改成了虚拟机的192.168.2.254

**Comment by zfl9** [comment]
你的意思是，你在内网中访问不了NAS还是什么？

**Comment by zfl9** [comment]
你还是组织好语言，提供一个完整的环境描述，以及问题描述。不要东一下西一下、

**Comment by lmhdrive** [comment]
做了个虚拟机就是玩翻墙和透明代理用的。在外网需要访问NAS,有时出差在外面，需要访问家里NAS

**Comment by zfl9** [comment]
你这个问题我解决不了，我无法搞清楚你的问题是啥，环境是啥。

**Comment by lmhdrive** [comment]
还是谢谢你了，我估计是映射关系没做好。iptables把原来的映射关系改了，就不行了。

**Comment by zfl9** [comment]
是的，但是我无能为力。你这层层嵌套的映射也是服气。

**Comment by jackyzou226** [comment]
不知道你的问题解决了没有，我也遇到了
