### ISSUE TITLE
建议在启动dnsmasq的时候也一并加载一下其自带的配置文件

### ISSUE THREAD

**Issue by WuSiYu** [zfl9/ss-tproxy#13]
在linux的软路由上，dnsmasq通常也会作为DHCP server ，其依赖于自带的配置文件`/etc/dnsmasq.conf`中的配置。但由于ss-tproxy在启动dnsmasq时使用了`-C`参数，其自带的配置文件`/etc/dnsmasq.conf`不再会被加载，导致软路由失去了DHCP server的功能。

所以建议在启动dnsmasq的时候也一并加载一下`/etc/dnsmasq.conf`，通常各大发行版默认的`/etc/dnsmasq.conf`中全部都是注释，加载一下也不会对原有功能造成冲突。

**Comment by zfl9** [comment]
如果这么做的话，切换模式后（有些模式没有用到 dnsmasq 的），就可能需要用户手动启用一下 dnsmasq 来进行 dhcp 服务了，所以我觉得这不是最佳的解决方法。你完全可以运行两个 dnsmasq 进程（dnsmasq 占用资源很少，而且是软路由，所以完全 OK），一个由 ss-tproxy 启动，作为 dns 服务器，一个由系统启动，作为 dhcp 服务器，只要配置不冲突就行。不过我自己是使用 dhcpd 作为 dhcp 服务器的。

当然，如果你觉得加载 /etc/dnsmasq.conf 更方便的话，完全可以动手修改 ss-tproxy。加一行 `cat /etc/dnsmasq.conf` 就行了。

**Comment by WuSiYu** [comment]
这样的话，确实用两个 dnsmasq 进程会比较好，不过这样会有个小问题，ss-tporxy在stop或者restart的时候会把两个dnsmasq都kill掉，在systemd的dnsmasq.service中加入`Restart=always`可以一定程度上解决。不过这样我确实不如也换成dhcpd来作为dhcp server
