### ISSUE TITLE
多个代理同时运行时是如何进行透明代理的防火墙调整

### ISSUE THREAD

**Issue by i2like** [zfl9/ss-tproxy#131]
如果在一个Linux上同时运行多个代理进程，如ssr-1(localport:1080)和ssr-2(localport:2080)，分别用于转发目的为特定IP和特定地址以外的其他非中国IP，ipset里做了中国IP，特定IP地址区分，请问如何将目的为特定IP的redir到ssr-1进程，目标为特定地址以外的IP的redir到ssr-2进程？

**Comment by zfl9** [comment]
搜索 `-j REDIRECT`、`-j TPROXY` 相关的几行iptables规则，你做一个分支就可以了。

**Comment by i2like** [comment]
是的，我是按这个思路来的，但实际好像不行，iptables可以运行，但到specip的dst没有被转发，
这是目前iptables的配置，
*nat
......
-A PREROUTING -j SSTP_PREROUTING
-A OUTPUT -j SSTP_OUTPUT
-A POSTROUTING -j SSTP_POSTROUTING
-A SSTP_OUTPUT -p tcp -m addrtype --src-type LOCAL ! --dst-type LOCAL -j SSTP_RULE
-A SSTP_POSTROUTING -m addrtype ! --src-type LOCAL -m conntrack --ctstate SNAT,DNAT -j RETURN
-A SSTP_POSTROUTING -p tcp -m addrtype ! --src-type LOCAL -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -j MASQUERADE
-A SSTP_POSTROUTING -p udp -m addrtype ! --src-type LOCAL -m conntrack --ctstate NEW -j MASQUERADE
-A SSTP_POSTROUTING -p icmp -m addrtype ! --src-type LOCAL -m conntrack --ctstate NEW -j MASQUERADE
-A SSTP_PREROUTING -p tcp -m addrtype ! --src-type LOCAL ! --dst-type LOCAL -j SSTP_RULE
-A SSTP_RULE -m set --match-set specip dst -p tcp -m multiport --dports 1:65535 -m tcp -j REDIRECT --to-ports 1080
-A SSTP_RULE -d VPSIP -j RETURN
-A SSTP_RULE -m set --match-set chnroute dst -j RETURN
-A SSTP_RULE -p tcp -m multiport --dports 1:65535 -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -j REDIRECT --to-ports 2080
......
*mangle
-A PREROUTING -j SSTP_PREROUTING
-A FORWARD -o ppp0 -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1400:65495 -j TCPMSS --clamp-mss-to-pmtu
-A OUTPUT -j SSTP_OUTPUT
-A SSTP_OUTPUT -p udp -m addrtype --src-type LOCAL ! --dst-type LOCAL -j SSTP_RULE
-A SSTP_PREROUTING -i lo -m mark ! --mark 0x1/0x1 -j RETURN
-A SSTP_PREROUTING -p udp -m addrtype ! --src-type LOCAL ! --dst-type LOCAL -j SSTP_RULE
-A SSTP_PREROUTING -m set --match-set specip dst -p udp -j TPROXY --on-port 1080 --on-ip 0.0.0.0 --tproxy-mark 0x1/0x1
-A SSTP_PREROUTING -p udp -m mark --mark 0x1/0x1 -j TPROXY --on-port 2080 --tproxy-mark 0x1/0x1
-A SSTP_RULE -j CONNMARK --restore-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A SSTP_RULE -m mark --mark 0x1/0x1 -j RETURN
-A SSTP_RULE -d VPSIP -j RETURN
-A SSTP_RULE -d 114.114.114.114/32 -p udp -m udp --dport 53 -j RETURN
-A SSTP_RULE -m set --match-set chnroute dst -j RETURN
-A SSTP_RULE -p udp -m multiport --dports 1:65535 -m conntrack --ctstate NEW -j MARK --set-xmark 0x1/0x1
-A SSTP_RULE -j CONNMARK --save-mark --nfmask 0xffffffff --ctmask 0xffffffff
......

**Comment by zfl9** [comment]
把 ss-tproxy 修改的部分发上来看下，你只是姿势不对而已。你这种需求早已有人实现。

**Comment by i2like** [comment]
ss-tproxy.conf基本都是常规配置，config里没有增加有关第二个ss进程的配置。

mode='chnroute' # chnroute 模式 (白名单)

## ipv4/6
ipv4='true'     # true:启用ipv4透明代理; false:关闭ipv4透明代理
ipv6='false'    # true:启用ipv6透明代理; false:关闭ipv6透明代理

## tproxy
tproxy='false'  # true:TPROXY+TPROXY; false:REDIRECT+TPROXY

## tcponly
tcponly='false' # true:仅代理TCP流量; false:代理TCP和UDP流量

## selfonly
selfonly='false' # true:仅代理本机流量; false:代理本机及"内网"流量

## proxy
proxy_svraddr4='VPSIP'  # 服务器的 IPv4 地址或域名，允许填写多个服务器地址，空格隔开
proxy_svraddr6=()       # 服务器的 IPv6 地址或域名，允许填写多个服务器地址，空格隔开
proxy_svrport='xxxx'   # 服务器的监听端口，可填多个端口，格式同 ipts_proxy_dst_port
proxy_tcpport='1080'    # ss/ssr/v2ray 等本机进程的 TCP 监听端口，该端口支持透明代理
proxy_udpport='1080'    # ss/ssr/v2ray 等本机进程的 UDP 监听端口，该端口支持透明代理
proxy_startcmd='/ss-redir -c ss-config.json -u -f /var/run/ss-redir.pid'     # 用于启动本机代理进程>的 shell 命令，该命令应该能立即执行完毕
proxy_stopcmd='kill -9 $(pidof ss-redir)'      # 用于关闭本机代理进程的 shell 命令，该命令应该能立即执行完毕

## dns
dns_direct='223.5.5.5'          # 本地 IPv4 DNS，不能指定端口，也可以填组织、公司内部 DNS
dns_direct6='240C::6666'              # 本地 IPv6 DNS，不能指定端口，也可以填组织、公司内部 DNS
dns_remote='1.0.0.1#53'               # 远程 IPv4 DNS，必须指定端口，提示：访问远程 DNS 会走代理
dns_remote6='2001:4860:4860::8888#53' # 远程 IPv6 DNS，必须指定端口，提示：访问远程 DNS 会走代理

## dnsmasq
dnsmasq_bind_port='53'                  # dnsmasq 服务器监听端口，见 README
dnsmasq_cache_size='4096'               # DNS 缓存大小，大小为 0 表示禁用缓存
dnsmasq_cache_time='3600'               # DNS 缓存时间，单位是秒，最大 3600 秒
dnsmasq_query_maxcnt=()              # 设置并发 DNS 查询的最大数量，默认为 150
dnsmasq_log_enable='false'              # 记录详细日志，除非进行调试，否则不建议启用
dnsmasq_log_file='/var/log/dnsmasq.log' # 日志文件，如果不想保存日志可以改为 /dev/null
dnsmasq_conf_dir=()                     # `--conf-dir` 选项的参数，可以填多个，空格隔开
dnsmasq_conf_file='/etc/dnsmasq.conf'   # `--conf-file` 选项的参数，可以填多个，空格隔开
dnsmasq_conf_string=()                  # 自定义配置，一个数组元素就是一行配置，空格隔开
## chinadns
chinadns_bind_port='65353'               # chinadns-ng 服务器监听端口，通常不用改动
chinadns_timeout='3'                     # 等待上游 DNS 返回响应的超时时间，单位为秒
chinadns_repeat='1'                      # 向可信 DNS 发送几次 DNS 查询请求，默认为 1
chinadns_fairmode='false'                # 使用公平模式，具体看 chinadns-ng 的 README
chinadns_gfwlist_mode='false'            # gfwlist 模式，加载 gfwlist.txt/gfwlist.ext
chinadns_noip_as_chnip='false'           # 启用 chinadns-ng 的 `--noip-as-chnip` 选项
chinadns_verbose='false'                 # 记录详细日志，除非进行调试，否则不建议启用
chinadns_logfile='/var/log/chinadns.log' # 日志文件，如果不想保存日志可以改为 /dev/null
chinadns_privaddr4=()                    # IPv4 私有地址段，多个用空格隔开，具体见 README
chinadns_privaddr6=()                    # IPv6 私有地址段，多个用空格隔开，具体见 README

## dns2tcp
dns2tcp_bind_port='65454'               # dns2tcp 转发服务器监听端口，如有冲突请修改
dns2tcp_verbose='false'                 # 记录详细日志，除非进行调试，否则不建议启用
dns2tcp_logfile='/var/log/dns2tcp.log'  # 日志文件，如果不想保存日志可以改为 /dev/null

## ipts
ipts_if_lo='lo'                 # 环回接口的名称，在标准发行版中，通常为 lo，如果不是请修改
ipts_rt_tab='100'               # iproute2 路由表名或表 ID，除非产生冲突，否则不建议改动该选项
ipts_rt_mark='0x01/0x01'           # iproute2 策略路由的防火墙标记，除非产生冲突，否则不建议改动该选项
ipts_set_snat='true'           # 设置 iptables 的 MASQUERADE 规则，布尔值，`true/false`，详见 README
ipts_set_snat6='false'          # 设置 ip6tables 的 MASQUERADE 规则，布尔值，`true/false`，详见 README
ipts_reddns_onstop='true'       # ss-tproxy stop 后，是否将其它主机发至本机的 DNS 重定向至直连 DNS，详见 README
ipts_proxy_dst_port='1:65535'   # 黑名单 IP 的哪些端口走代理，多个用逗号隔开，冒号为端口范围(含边界)，详见 README

## opts
opts_ss_netstat='auto'                  # auto/ss/netstat，用哪个端口检测工具，见 README
opts_ping_cmd_to_use='auto'             # auto/standalone/parameter，ping 相关，见 README
opts_hostname_resolver='auto'           # auto/dig/getent/ping，用哪个解析工具，见 README
opts_overwrite_resolv='false'           # true/false/留空，如何操作 resolv.conf，见 README
opts_ip_for_check_net='114.114.114.114' # 检测外网是否可访问的 IP，ping，留空表示跳过此检查

## file
file_gfwlist_txt='/etc/ss-tproxy/gfwlist.txt'      # gfwlist/chnlist 模式预置文件
file_gfwlist_ext='/etc/ss-tproxy/gfwlist.ext'      # gfwlist/chnlist 模式扩展文件
file_ignlist_ext='/etc/ss-tproxy/ignlist.ext'      # global/chnroute 模式扩展文件
file_chnroute_set='/etc/ss-tproxy/chnroute.set'    # chnroute 地址段文件 (iptables)
file_chnroute6_set='/etc/ss-tproxy/chnroute6.set'  # chnroute6 地址段文件 (ip6tables)
file_dnsserver_pid='/etc/ss-tproxy/.dnsserver.pid' # dns 服务器进程的 pid 文件 (shell)

**Comment by zfl9** [comment]
把 ss-tproxy 修改的部分发上来看下。不是配置文件。

**Comment by i2like** [comment]
ss-tproxy修改的部分？
我并没有修改任何代码部分
只是用了ss-trpoxy启动一个ss进程（配置见上），另一个进程是手动启动的，就是防火墙部分不知道怎么配置

**Comment by zfl9** [comment]
...不建议在start之后手动改iptables规则。自己改一下ss-tproxy脚本，在TPROXY/REIRECT规则上做一下分流就行了。

**Comment by i2like** [comment]
ss-tproxy脚本是指的ss-tproxy.conf吧

**Comment by i2like** [comment]
哦，明白了，你指的ss-tproxy运行脚本

**Comment by zfl9** [comment]
> 哦，你指的ss-tproxy运行脚本
> 我看一下，thks

是的，那你之前已经理解错我的意思了。
