### ISSUE TITLE
发现一个某些情况下IP不走ss-redir的bug

### ISSUE THREAD

**Issue by cuteSakuraHime** [zfl9/ss-tproxy#133]
我这几天一直发现使用了一段时间后YouTube打不开的现象，于是在router上curl www.youtube.com。
![image](https://user-images.githubusercontent.com/10474077/76390784-fab45800-63a8-11ea-8b0d-c7b583029554.png)
当解析到172.217.24.14 YouTube打不开，为了避免是这个IP没有走代理，我特地去gfwlist.ext 加了 172.217.0.0/16 这一行规则。
随后我重启，过了一段时间又打不开了。我在router上curl 这个IP，然后去看了ss-redir的log，其中是没有这个记录的。
但是当我再一次重启的时候，就能在ss-redir.log里面找到对应的请求了。
![image](https://user-images.githubusercontent.com/10474077/76391069-9776f580-63a9-11ea-92e1-e440e23a3808.png)
![image](https://user-images.githubusercontent.com/10474077/76391084-9f369a00-63a9-11ea-922a-9cf1c99f53f1.png)

因而猜测是否会有一种可能使得某些IP不走代理？每次重启（不改配置）都能解决问题，但是我觉得这终究不是个办法...

**Comment by zfl9** [comment]
> 随后我重启，过了一段时间又打不开了。我在router上curl 这个IP，然后去看了ss-redir的log，其中是没有这个记录的。

你在此时看一下 gfwlist 这个 ipset 里面是否有对应 ip 不就知道真相了吗

**Comment by cuteSakuraHime** [comment]
我用的是 `chnroute` ， ipset list 然后找不到我写的那行，是我操作不对吗？
![image](https://user-images.githubusercontent.com/10474077/76391748-1d477080-63ab-11ea-9a75-871f12973aaf.png)

**Comment by zfl9** [comment]
chnroute模式下，gfwlist.ext 只有在 chinadns-ng 开启了gfwlist 模式才会加载，而且只加载域名模式。我不知道你只的重启是重启什么，描述详细点。配置啥的都发上来。日志啥的都发上来，尤其是chinadns-ng的详细日志（verbose开关打开）

**Comment by cuteSakuraHime** [comment]
我使用的命令是 `ss-tproxy restart` 即杀掉所有的程序并重来
我的 `gfwlist.ext` 里面的内容如下
![image](https://user-images.githubusercontent.com/10474077/76443778-f0707900-63fd-11ea-9e7b-67124b6e6ad8.png)
日志几个G实在不方便排查，我这个部署的router都是高负载的... 低负载的router没遇到过。
而且我认为和chinadns应该无关才对，因为我的YouTube都已经解析出来了，解析的IP是对的，就是ss-redir.log里面找不到这个请求。

**Comment by cuteSakuraHime** [comment]
我现在的解决方案是 crontab 中定时 `ss-tproxy restart`
这个IP不走ss-redir的情况只在超高负载的机器上才出现，其他机器都是工作正常的。
以及很奇怪的是，只有YouTube的IP才会有这个情况，Google首页是不会的。
日志是真的没办法翻，我只能用 `tail -f /var/log/ss-redir.log` 来确定出现故障的时候，这个IP不在这个log里面
![image](https://user-images.githubusercontent.com/10474077/76444451-f3b83480-63fe-11ea-8c0c-ada4d29f07cc.png)

**Comment by zfl9** [comment]
> 我使用的命令是 `ss-tproxy restart` 即杀掉所有的程序并重来
> 我的 `gfwlist.ext` 里面的内容如下
> ![image](https://user-images.githubusercontent.com/10474077/76443778-f0707900-63fd-11ea-9e7b-67124b6e6ad8.png)
> 日志几个G实在不方便排查，我这个部署的router都是高负载的... 低负载的router没遇到过。
> 而且我认为和chinadns应该无关才对，因为我的YouTube都已经解析出来了，解析的IP是对的，就是ss-redir.log里面找不到这个请求。

chnroute模式下，要生效gfwlist.txt/ext 需要打开 chinadns_gfwlist_mode 选项。你开了这个没。

**Comment by fbion** [comment]
mark

**Comment by cuteSakuraHime** [comment]
> > 我使用的命令是 `ss-tproxy restart` 即杀掉所有的程序并重来
> > 我的 `gfwlist.ext` 里面的内容如下
> > ![image](https://user-images.githubusercontent.com/10474077/76443778-f0707900-63fd-11ea-9e7b-67124b6e6ad8.png)
> > 日志几个G实在不方便排查，我这个部署的router都是高负载的... 低负载的router没遇到过。
> > 而且我认为和chinadns应该无关才对，因为我的YouTube都已经解析出来了，解析的IP是对的，就是ss-redir.log里面找不到这个请求。
> 
> chnroute模式下，要生效gfwlist.txt/ext 需要打开 chinadns_gfwlist_mode 选项。你开了这个没。

`chinadns_gfwlist_mode='true'`
看了下配置是开着的…

**Comment by zfl9** [comment]
```
$ curl -4sSkL https://172.217.24.14 -H"Host: www.youtube.com" -Iv
*   Trying 172.217.24.14:443...
* TCP_NODELAY set
* Connected to 172.217.24.14 (172.217.24.14) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=No SNI provided; please fix your client.; CN=invalid2.invalid
*  start date: Jan  1 00:00:00 2015 GMT
*  expire date: Jan  1 00:00:00 2030 GMT
*  issuer: OU=No SNI provided; please fix your client.; CN=invalid2.invalid
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x555e0b7bf820)
> HEAD / HTTP/2
> Host: www.youtube.com
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
HTTP/2 200 
< x-content-type-options: nosniff
x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
x-frame-options: SAMEORIGIN
< expires: Tue, 27 Apr 1971 19:44:06 GMT
expires: Tue, 27 Apr 1971 19:44:06 GMT
< content-type: text/html; charset=utf-8
content-type: text/html; charset=utf-8
< cache-control: no-cache
cache-control: no-cache
< p3p: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
p3p: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
< strict-transport-security: max-age=31536000
strict-transport-security: max-age=31536000
< date: Thu, 12 Mar 2020 06:13:44 GMT
date: Thu, 12 Mar 2020 06:13:44 GMT
< server: YouTube Frontend Proxy
server: YouTube Frontend Proxy
< x-xss-protection: 0
x-xss-protection: 0
< set-cookie: YSC=VdbEeDDrGhw; path=/; domain=.youtube.com; secure; httponly; samesite=None
set-cookie: YSC=VdbEeDDrGhw; path=/; domain=.youtube.com; secure; httponly; samesite=None
< set-cookie: VISITOR_INFO1_LIVE=bTzO090DJso; path=/; domain=.youtube.com; secure; expires=Tue, 08-Sep-2020 06:13:43 GMT; httponly; samesite=None
set-cookie: VISITOR_INFO1_LIVE=bTzO090DJso; path=/; domain=.youtube.com; secure; expires=Tue, 08-Sep-2020 06:13:43 GMT; httponly; samesite=None
< set-cookie: GPS=1; path=/; domain=.youtube.com; expires=Thu, 12-Mar-2020 06:43:43 GMT
set-cookie: GPS=1; path=/; domain=.youtube.com; expires=Thu, 12-Mar-2020 06:43:43 GMT
< alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
< accept-ranges: none
accept-ranges: none
< vary: Accept-Encoding
vary: Accept-Encoding

< 
* Connection #0 to host 172.217.24.14 left intact
****
```

**Comment by cuteSakuraHime** [comment]
我也可以的，但是就是会不定时boom，我试试看录个gif传上来

**Comment by cuteSakuraHime** [comment]
[ss-redir-1.mov.zip](https://github.com/zfl9/ss-tproxy/files/4323027/ss-redir-1.mov.zip)

**Comment by zfl9** [comment]
很奇怪，暂时无解。
