### ISSUE TITLE
奇怪的“断流”现象

### ISSUE THREAD

**Issue by JayceYang** [zfl9/ss-tproxy#134]
在Ubuntu 18.04主机上做的局域网透明代理（V2Ray），使用了差不多半年吧。一直有一个现象：
大概20分钟左右后，浏览器就不能走代理了，Chrome表现尤为明显，必须重启浏览器才好。
<img width="725" alt="image" src="https://user-images.githubusercontent.com/2830415/77058007-cdeaeb00-6a0f-11ea-9d16-38ca222f6cda.png">
Safari也会这样，但是概率相对较低。
为了进一步排查问题，我关闭ss-tproxy，转而使用V2rayU客户端，发现Chrome又没有问题。
因此，在这里抛出这个问题，希望作者能抽空看看。

**Comment by zfl9** [comment]
不看日志叫什么排查。你们都不会看日志的吗？去看v2ray日志啊。

**Comment by JayceYang** [comment]
不要这么急躁好吗？日志看了，没有error级别的，要改成info吗？

发自我的iPhone

**Comment by JayceYang** [comment]
以前挺敬重的一个人，原来也就这样。

发自我的iPhone

**Comment by zfl9** [comment]
随你评论，无所谓。我只说一句，我自己用了这个脚本用了一年多了，透明代理是自己写的一个不是ss/ssr/v2，根本就没有你所谓的运行超过20分钟就出现连接被拒的情况。你自己去看代理的配置吧。

**Comment by JayceYang** [comment]
我是公司环境下使用，规模大概50。
你的github我看了不下一百遍，每个issue我也几乎都看了。一开始确实啥都不懂，毕竟我之前只弄过前端。
都是搞技术的，我们应该都对“我这里没问题”很有感触吧？何况，我提issue只是让你抽空看看，并没一定就说是这个项目的问题。我这半年多，也时常向别人推荐你这个项目。

你做开源项目，为社区做共享，本来是好事。
但你的态度，我不敢苟同。
你在linux、运维方面可能是专家，每个人都有各自的特长，我希望我们之间的对话尽量平等。

算了，老哥。谁让您是作者。

发自我的iPhone

**Comment by zfl9** [comment]
不好意思我不是专家，我只是闲出屁写这个脚本。我承认我最近的一些issue回复很没耐心，但是一开始我并不是这样的（如果你真看过我每个issue的话），经历过啥，我也不想多说，我只能说累了吧，心累，说实在的，几乎总是那种“低质量”的issue，总是就一个标题，xxx有问题，xxx没法代理，等等，然后一个屁的描述都没有，我readme都不知道写了多少遍了，日志日志日志，可是我就没见过几个issue实实在在的贴上相应的日志。每次都是我不停的“主动”询问他们要他们的日志，慢慢的我没耐心了。我看到这种issue真的很有种立马想要close的冲动，但是大部分情况下我都忍住了。今天你这个issue确实我有点冲动急躁。我也并没有什么看不起在座的各位的任何意思。早知道“屁事”这么多，我又何必开源这些鬼东西。

回到正题，你去开启v2的日志（客户端和服务端都要），尽量开启详细的日志。透明代理这些鬼问题牵扯的面太多了，排查很繁琐，因为这个，每次我回答issue都回答的很累，很烦。

**Comment by JayceYang** [comment]
谢谢了。我今天提issue也是着急了些，确实没看到v2ray的错误日志，也忘记说明了。
我现在回到家了，明天再开启日志。不过，我的代理服务器不是自建的，搞不了服务端日志。

以下纯讨论、交流，哥你有时间、有精力就回复下：
我猜想应该跟udp有关，开篇不是说对比过V2rayU客户端嘛，它没有开启udp代理。
所以，我想请教下：**是不是客户端的不开启udp代理，底层也是使用了类似于你的dns2tcp的方案？**
另外，我搜索到V2Ray官方的一个透明代理的issue，也是udp的：https://github.com/v2ray/v2ray-core/issues/1432

**Comment by rampageX** [comment]
不玩特定游戏或者 PS4 这些主机游戏，完全没必要开 UDP 透明代理，全是坑（并不特指这个脚本）。

**Comment by JayceYang** [comment]
@zfl9 刚刚一来公司，修改v2ray的日志level，stop再srart代理进程后，Chrome就出现了拒绝youtue的错误，但是我立即用Safari就同样访问youtube没问题。
<img width="388" alt="image" src="https://user-images.githubusercontent.com/2830415/77129546-5c528180-6a8f-11ea-940b-890665b62f5b.png">

客户端的日志弄出来了，服务端没有。你看有没有分析的可能性？没有的话，我就关闭udp代理了。
`2020/03/20 09:35:22 [Debug] v2ray.com/core/app/log: Logger started
2020/03/20 09:35:22 [Warning] v2ray.com/core: V2Ray 4.21.3 started
2020/03/20 09:35:23 [Debug] [1971281267] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.51.206:49506
2020/03/20 09:35:23 [Info] [1971281267] v2ray.com/core/app/dispatcher: default route for tcp:74.125.204.188:5228
2020/03/20 09:35:23 [Info] [1971281267] v2ray.com/core/transport/internet/websocket: creating connection to tcp:vpshost:8081
2020/03/20 09:35:23 [Debug] [1494859857] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.51.206:49507
2020/03/20 09:35:23 [Debug] [2075023515] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.51.206:49508
2020/03/20 09:35:23 [Info] [1494859857] v2ray.com/core/app/dispatcher: default route for tcp:149.154.171.245:443
2020/03/20 09:35:23 [Info] [2075023515] v2ray.com/core/app/dispatcher: default route for tcp:149.154.171.245:443
2020/03/20 09:35:23 [Info] [2075023515] v2ray.com/core/transport/internet/websocket: creating connection to tcp:vpshost:8081
2020/03/20 09:35:23 [Info] [1494859857] v2ray.com/core/transport/internet/websocket: creating connection to tcp:vpshost:8081
2020/03/20 09:35:23 [Info] [1494859857] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:149.154.171.245:443 via tcp:vpshost:8081
2020/03/20 09:35:23 [Info] [2075023515] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:149.154.171.245:443 via tcp:vpshost:8081
2020/03/20 09:35:23 [Info] [1971281267] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:74.125.204.188:5228 via tcp:vpshost:8081
2020/03/20 09:35:54 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:172.217.25.14:443
2020/03/20 09:35:54 [Debug] [70750194] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.51.206:54406
2020/03/20 09:35:54 [Info] [70750194] v2ray.com/core/app/dispatcher: default route for udp:172.217.25.14:443
2020/03/20 09:35:54 [Info] [70750194] v2ray.com/core/transport/internet/websocket: creating connection to tcp:vpshost:8081
2020/03/20 09:35:54 [Info] [70750194] v2ray.com/core/proxy/vmess/outbound: tunneling request to udp:172.217.25.14:443 via tcp:vpshost:8081
2020/03/20 09:36:02 [Debug] [2330974] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.51.239:59529
2020/03/20 09:36:02 [Info] [2330974] v2ray.com/core/app/dispatcher: default route for tcp:172.217.24.46:443
2020/03/20 09:36:02 [Info] [2330974] v2ray.com/core/transport/internet/websocket: creating connection to tcp:vpshost:8081
2020/03/20 09:36:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:8.8.8.8:53
2020/03/20 09:36:02 [Debug] [2497525874] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.51.2:54055
2020/03/20 09:36:02 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:8.8.8.8:53
2020/03/20 09:36:02 [Info] [2497525874] v2ray.com/core/app/dispatcher: default route for udp:8.8.8.8:53
2020/03/20 09:36:02 [Info] [2497525874] v2ray.com/core/transport/internet/websocket: creating connection to tcp:vpshost:8081
2020/03/20 09:36:02 [Info] [2330974] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:172.217.24.46:443 via tcp:vpshost:8081
2020/03/20 09:36:02 [Info] [2497525874] v2ray.com/core/proxy/vmess/outbound: tunneling request to udp:8.8.8.8:53 via tcp:vpshost:8081
2020/03/20 09:36:02 [Debug] [1534318736] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.51.239:59530
2020/03/20 09:36:02 [Info] [1534318736] v2ray.com/core/app/dispatcher: default route for tcp:108.177.97.92:443
2020/03/20 09:36:02 [Info] [1534318736] v2ray.com/core/transport/internet/websocket: creating connection to tcp:vpshost:8081
2020/03/20 09:36:02 [Info] [1534318736] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:108.177.97.92:443 via tcp:vpshost:8081
2020/03/20 09:36:11 [Info] [70750194] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: c
onnection ends > context canceled
2020/03/20 09:36:11 [Info] [70750194] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.com
/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/03/20 09:36:17 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:172.217.24.196:443
2020/03/20 09:36:17 [Debug] [1230020319] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.51.206:52360
2020/03/20 09:36:17 [Info] [1230020319] v2ray.com/core/app/dispatcher: default route for udp:172.217.24.196:443
2020/03/20 09:36:17 [Info] [1230020319] v2ray.com/core/transport/internet/websocket: creating connection to tcp:vpshost:8081
2020/03/20 09:36:17 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:172.217.24.196:443
2020/03/20 09:36:17 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:172.217.24.196:443
2020/03/20 09:36:17 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:172.217.24.196:443
2020/03/20 09:36:17 [Debug] [1236971332] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.51.206:54148
2020/03/20 09:36:17 [Info] [1236971332] v2ray.com/core/app/dispatcher: default route for udp:172.217.24.196:443
2020/03/20 09:36:17 [Info] [1236971332] v2ray.com/core/transport/internet/websocket: creating connection to tcp:vpshost:8081
2020/03/20 09:36:17 [Info] [1230020319] v2ray.com/core/proxy/vmess/outbound: tunneling request to udp:172.217.24.196:443 via tcp:vpshost:8081
2020/03/20 09:36:17 [Info] [1236971332] v2ray.com/core/proxy/vmess/outbound: tunneling request to udp:172.217.24.196:443 via tcp:vpshost:8081
2020/03/20 09:36:18 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:172.217.25.14:443
2020/03/20 09:36:18 [Debug] [4257850215] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.51.206:54406
2020/03/20 09:36:18 [Info] [4257850215] v2ray.com/core/app/dispatcher: default route for udp:172.217.25.14:443
2020/03/20 09:36:18 [Info] [4257850215] v2ray.com/core/transport/internet/websocket: creating connection to tcp:vpshost:8081
2020/03/20 09:36:18 [Info] [4257850215] v2ray.com/core/proxy/vmess/outbound: tunneling request to udp:172.217.25.14:443 via tcp:vpshost:8081
2020/03/20 09:36:24 [Debug] [2022925016] v2ray.com/core/proxy/dokodemo: processing connection from: 192.168.51.206:49534
2020/03/20 09:36:24 [Info] [2022925016] v2ray.com/core/app/dispatcher: default route for tcp:172.217.24.196:443
2020/03/20 09:36:24 [Info] [2022925016] v2ray.com/core/transport/internet/websocket: creating connection to tcp:vpshost:8081
2020/03/20 09:36:24 [Info] [2022925016] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:172.217.24.196:443 via tcp:vpshost:8081
2020/03/20 09:36:27 [Info] [2497525874] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound:
 connection ends > context canceled
2020/03/20 09:36:27 [Info] [2497525874] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.c
om/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2020/03/20 09:36:27 [Info] [1230020319] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound:
 connection ends > context canceled
2020/03/20 09:36:27 [Info] [1236971332] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound:
 connection ends > context canceled
2020/03/20 09:36:27 [Info] [1230020319] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/dokodemo: connection ends > v2ray.c
om/core/proxy/dokodemo: failed to transport response > io: read/write on closed pipe`

**Comment by zfl9** [comment]
> Chrome就出现了拒绝youtue的错误，但是我立即用Safari就同样访问youtube没问题。

QUIC 的问题，quic 是基于udp的，chrome浏览器默认开启。其它浏览器一般都不支持，所以还是常规tls1.2/3（tcp），所以没问题。v2ray 的 udp 本来就有断流的 bug，你可以去 v2ray 下面看到很多这种 issue。

**Comment by zfl9** [comment]
有两种办法:
1. 关闭 chrome 的 quic
2. 使用 tcponly 模式

如果没有udp代理需求，用方式二最稳。

**Comment by fbion** [comment]
> 有两种办法:
> 
>     1. 关闭 chrome 的 quic
> 
>     2. 使用 tcponly 模式
> 
> 
> 如果没有udp代理需求，用方式二最稳。

uqic udp走kcp正常

**Comment by JayceYang** [comment]
> 有两种办法:
> 
> 1. 关闭 chrome 的 quic
> 2. 使用 tcponly 模式
> 
> 如果没有udp代理需求，用方式二最稳。

1+2同时修改了（并且"tproxy": "redirect"），Chrome还是抽风。
换回ss后，一切都好了。🤪
暂时先这样用着吧。感谢感谢！
