### ISSUE TITLE
如何连接到另一台机器上的socks5端口？

### ISSUE THREAD

**Issue by left4taco** [zfl9/ss-tproxy#135]
我本地网路有两台机器，10.0.0.100（A）和10.0.0.200（B）机器，其中A上运行了ssr，并且通过1086端口分享了socks5代理。这种情况下，如何配置才能使B机器通过A:1086进行透明代理呢？

谢谢

**Comment by zfl9** [comment]
B(ss-tproxy -> redsocks2/ipt2socks) ---> A(socks5-proxy-server)
