### ISSUE TITLE
本地能正常访问国内外，但对外只能打开国内网站

### ISSUE THREAD

**Issue by weargle** [zfl9/ss-tproxy#137]
我把dns布署在服务器上，服务器通过curl命令能正常获取网页源码，但把我电脑的dns修改为服务器的ip后国内网站正常打开，国外的不行。
服务器打开百度
![baidu](https://user-images.githubusercontent.com/26951765/77249232-9e8be680-6c7a-11ea-944e-766e921ce383.png)
服务器打开谷歌
![google](https://user-images.githubusercontent.com/26951765/77249245-b2374d00-6c7a-11ea-8c42-126c7134def9.png)

**Comment by weargle** [comment]
这是我用电脑打开谷歌dns生成的日志。
dnsmasq日志
![dnsmasq](https://user-images.githubusercontent.com/26951765/77313566-13c0ef80-6d3f-11ea-912e-2b1992a571f7.png)

chinadns日志
![chinadns](https://user-images.githubusercontent.com/26951765/77313599-21767500-6d3f-11ea-9655-0dee6106601a.png)

ss-redir日志
![ss-redir](https://user-images.githubusercontent.com/26951765/77313635-2b987380-6d3f-11ea-927b-b16f32cf3004.png)

配置文件参数我就改了代理部分的参数，其他没有任何改变。

**Comment by zfl9** [comment]
> 但把我电脑的dns修改为服务器的ip后国内网站正常打开，国外的不行。

光解决dns的污染不够，gfw哪有这么简单。你需要tcp也走代理。

**Comment by zfl9** [comment]
不然你拿到无污染的ip后，依旧无法访问他，gfw直接给你reset。

**Comment by weargle** [comment]
看了很久文档没有看懂，我是不是还要找个代理软件代理浏览器的流量才行

**Comment by zfl9** [comment]
那你不适合用这个，去找其它一键化脚本吧。
