### ISSUE TITLE
关于dnsmasq监听端口的疑问

### ISSUE THREAD

**Issue by hanson-l** [zfl9/ss-tproxy#139]
大佬你好，我是个小白，用了段时间有个疑问想请教一下。
`README`当中说如果`dnsmasq`监听端口已被占用则修改为其它未占用的端口，既然前提是`53`端口都被其他占用了，那脚本中`53`端口的流量却都重定向到了`dnsmasq`监听端口，这不就影响原来`53`端口的使用吗？
(顺带提一下，我现在使用DNS广告拦截监听`53`端口，然后上游DNS设置为`dnsmasq`监听的非标端口)

**Comment by zfl9** [comment]
> 那脚本中53端口的流量却都重定向到了dnsmasq监听端口，这不就影响原来53端口的使用吗？

如你所见，是的。

如果有更高级的需求，请自行修改脚本。需求有无数多，这这是一个非常简陋的透明代理脚本。

**Comment by hanson-l** [comment]
谢谢大佬的脚本，用得很方便
