### ISSUE TITLE
使用中遇到的2个问题，希望帮忙解决！

### ISSUE THREAD

**Issue by lmhdrive** [zfl9/ss-tproxy#140]
大侠你好：非常感谢能提供这么方便的软件！目前遇到2个问题：

1、软件使用chnroute模式能正常使用，由于流量有限，希望使用gfwlist模式，但切换到gfwlist模式无法正常使用，youtube能打开网站,但无法显示所有图片，google打不开。客户端上使用ipconfig/flushdns也不行。

2、是由于v2ray不好更换代理，我在同网段的另一虚拟机上安装了WINDOWS版本的V2RAY和CLASH并设置好了SOCKS5代理，希望用SS-TPORXY分流时外网直接转到WINDOWS虚拟机的SOCKS5代理端口上，这样更换代理方便些，SS-TPROXY机器只做透明代理，实现分流及智能转发功能，不安装v2ray代理软件了。SS-TPROXY的虚拟机IP为:192.168.2.1,另一个安装WINDOWS版V2RAY和CLASH的虚拟机IP为192.168.2.15，并已经设置好了socks5代理端口为10808。请大侠帮忙看看SS-TPROXY如何设置外网转发到192.168.2.15的SOCKS5代理端口10808上去。非常感谢能帮忙解决！如有机会进行捐助。

**Comment by zfl9** [comment]
第一个问题后面有时间再说。说下第二个问题，这个很好解决。redsocks2/ipt2socks 都可以。具体点就是在 ss-tproxy 主机运行 redsocks2/ipt2socks，监听60080透明代理端口，上游设置为你的socks5代理地址就行了。

**Comment by lmhdrive** [comment]
太好了！我去试试。希望大侠有时间帮忙解决第一个问题，再次感谢~

**Comment by lmhdrive** [comment]
大侠你好：我试了一下，用这条命令：
 /usr/local/bin/ipt2socks -b 0.0.0.0 -l 60080 -s 192.168.2.15 -p 10808
用systemctl stop v2ray关闭了v2ray.还是不行,打不开谷歌，麻烦帮忙看一下。

配置文件如下：
## mode
#mode='global'  # global 模式 (不分流)
#mode='gfwlist' # gfwlist 模式 (黑名单)
mode='chnroute' # chnroute 模式 (白名单)

## ipv4/6
ipv4='true'     # true:启用ipv4透明代理; false:关闭ipv4透明代理
ipv6='false'    # true:启用ipv6透明代理; false:关闭ipv6透明代理

## tproxy
tproxy='true'  # true:TPROXY+TPROXY; false:REDIRECT+TPROXY

## tcponly
tcponly='false' # true:仅代理TCP流量; false:代理TCP和UDP流量

## selfonly
selfonly='false' # true:仅代理本机流量; false:代理本机及"内网"流量

## proxy
proxy_svraddr4=(192.168.2.15) # V2RAY服务器的 IPv4 地址或域名，允许填写多个服务器地址，空格隔开
proxy_svraddr6=()        # 服务器的 IPv6 地址或域名，允许填写多个服务器地址，空格隔开
proxy_svrport='10808'   # V2RAY服务器的监听端口，可填多个端口，格式同 ipts_proxy_dst_port
proxy_tcpport='60080'    # ss/ssr/v2ray 等本机进程的 TCP 监听端口，该端口支持透明代理
proxy_udpport='60080'    # ss/ssr/v2ray 等本机进程的 UDP 监听端口，该端口支持透明代理

proxy_startcmd=''     # 用于启动本机代理进程的 shell 命令，该命令应该能立即执行完毕
proxy_stopcmd=''      # 用于关闭本机代理进程的 shell 命令，该命令应该能立即执行完毕

## dns
dns_direct='114.114.114.114'          # 本地 IPv4 DNS，不能指定端口，也可以填组织、公司内部 DNS
dns_direct6='240C::6666'              # 本地 IPv6 DNS，不能指定端口，也可以填组织、公司内部 DNS
dns_remote='8.8.8.8#53'               # 远程 IPv4 DNS，必须指定端口，提示：访问远程 DNS 会走代理
dns_remote6='2001:4860:4860::8888#53' # 远程 IPv6 DNS，必须指定端口，提示：访问远程 DNS 会走代理

**Comment by zfl9** [comment]
更新ipt2socks重新编译，刚才的版本有问题。

**Comment by lmhdrive** [comment]
好的，我刚才的SS-TPROXY虚拟机改乱了，正在重新恢复。一会儿重新编译一下，更新完看看，谢谢您了。

**Comment by lmhdrive** [comment]
大侠，我试了一下，用这两条命令都不行，传不过去。用IE代理设备套接字服务器就可以使用，您看看
/usr/local/bin/ipt2socks -b 0.0.0.0 -l 60080 -s 192.168.2.15 -p 10808
/usr/local/bin/ipt2socks -s 192.168.2.15 -p 10808
－－－－－－－－－－－－－－－－－
连接超时

www.youtube.com 的服务器响应时间过长。

**Comment by zfl9** [comment]
倒是把ipt2socks日志发来。信息田少

**Comment by lmhdrive** [comment]
可以了，等一会儿就好了，非常感谢！辛苦了！
第一个问题我估计可能还是解析的问题，网站被墙了。发现一个解决DNS污染的小工具，IP域名同步解析，速度快，我水平有限不知道能否解决，您如果感兴趣可以看看。https://github.com/IrineSistiana/mos-chinadns

**Comment by lmhdrive** [comment]
刚才是IE的代理没关，还是不行，日志我不会弄，回头我再看看吧，弄好了发给您。

**Comment by lmhdrive** [comment]
经过大侠提示，这回解决了，日志上写的，2020-05-05 15:42:26 ERR: [new_nonblock_sockfd] socket(AF_INET6, SOCK_STREAM): Address family not supported by protocol我刚开始没在意，觉得并不影响运行，但实际是停在那了，这回把命令加个－4参数就解决了， /usr/local/bin/ipt2socks  -b 127.0.0.1 -l 60080 -s 192.168.2.15 -p 10808 -4即可。
第一个问题麻烦大侠有时间帮忙解决，谢谢您了~

**Comment by zfl9** [comment]
第一个问题我需要更多的细节（日志、配置、调试细节）等等，不然我没法定位问题。
