### ISSUE TITLE
chn mode 下 添加黑名单

### ISSUE THREAD

**Issue by kun-qian** [zfl9/ss-tproxy#142]
请教下问题：

白名单模式下，添加了黑名单在gfwlist.ext中。执行 `ss-tproxy delete-gfwlist` , restart ss-tproxy.
在透明网关上访问 raw.githubusercontent.com没有问题，但是其他机器（指向透明网关）访问不了。

**Comment by zfl9** [comment]
![image](https://user-images.githubusercontent.com/22726048/82190533-b783e180-9923-11ea-86b5-86c084e43bd1.png)

**Comment by kun-qian** [comment]
@zfl9 谢谢。我update-gfwlist了。
后来找到问题了，我的路由器dhcp 只设置了gateway（透明网关），没有设置DNS（应该也是指向透明网关）。
