### ISSUE TITLE
trojan support?

### ISSUE THREAD

**Issue by kun-qian** [zfl9/ss-tproxy#143]
请问有支持 trojan 的打算吗？

**Comment by zfl9** [comment]
不限客户端。自由发挥。我觉得只要你看完了 readme 就能知道答案了。

**Comment by zfl9** [comment]
1. 如果proxy支持iptables(redirect/tproxy)传入协议，则直接类似ss-redir/v2(dokodemo-door)。
2. 如果proxy不支持iptables(redirect/tproxy传入协议（如只支持socks5传入），则使用redsocks2/ipt2socks+proxy解决。

**Comment by zfl9** [comment]
如果不支持 Udp，则启用 tcponly。

**Comment by cattyhouse** [comment]
troajn 的 nat 模式不支持 udp, 作者貌似在寻思改进... 等吧.

**Comment by kun-qian** [comment]
@zfl9 我试了 Trojan 的 client 模式，设置socks5代理，可以通。我改成 NAT 模式之后，一直有问题，首先DNS解析就有问题，还望指点一些排查思路。ss-tproxt.conf 如下：
`
## mode
mode='global'  # global 模式 (不分流)
#mode='gfwlist' # gfwlist 模式 (黑名单)
#mode='chnroute' # chnroute 模式 (白名单)

## ipv4/6
ipv4='true'     # true:启用ipv4透明代理; false:关闭ipv4透明代理
ipv6='false'    # true:启用ipv6透明代理; false:关闭ipv6透明代理

## tproxy
tproxy='true'  # true:TPROXY+TPROXY; false:REDIRECT+TPROXY

## tcponly
tcponly='true' # true:仅代理TCP流量; false:代理TCP和UDP流量

## selfonly
selfonly='false' # true:仅代理本机流量; false:代理本机及"内网"流量

## proxy
proxy_svraddr4=(www.example.ml) # 服务器的 IPv4 地址或域名，允许填写多个服务器地址，空格隔开
proxy_svraddr6=()        # 服务器的 IPv6 地址或域名，允许填写多个服务器地址，空格隔开
proxy_svrport='443'   # 服务器的监听端口，可填多个端口，格式同 ipts_proxy_dst_port
proxy_tcpport='1080'    # ss/ssr/v2ray 等本机进程的 TCP 监听端口，该端口支持透明代理
#proxy_udpport='1080'    # ss/ssr/v2ray 等本机进程的 UDP 监听端口，该端口支持透明代理
proxy_startcmd='/root/trojan/trojan -c /root/trojan/config.json &>>/var/log/trojan.log &'     # 用于启动本机代理进程的 shell 命令，该命令应该能立即执行完毕
proxy_stopcmd='kill -9 $(pidof trojan)'      # 用于关闭本机代理进程的 shell 命令，该命令应该能立即执行完毕

## dns
dns_direct='114.114.114.114'          # 本地 IPv4 DNS，不能指定端口，也可以填组织、公司内部 DNS
dns_direct6='240C::6666'              # 本地 IPv6 DNS，不能指定端口，也可以填组织、公司内部 DNS
dns_remote='8.8.8.8#53'               # 远程 IPv4 DNS，必须指定端口，提示：访问远程 DNS 会走代理
dns_remote6='2001:4860:4860::8888#53' # 远程 IPv6 DNS，必须指定端口，提示：访问远程 DNS 会走代理

## dnsmasq
dnsmasq_bind_port='60053'                  # dnsmasq 服务器监听端口，见 README
dnsmasq_cache_size='4096'               # DNS 缓存大小，大小为 0 表示禁用缓存
dnsmasq_cache_time='3600'               # DNS 缓存时间，单位是秒，最大 3600 秒
dnsmasq_query_maxcnt='1024'             # 设置并发 DNS 查询的最大数量，默认为 150
dnsmasq_log_enable='false'              # 记录详细日志，除非进行调试，否则不建议启用
dnsmasq_log_file='/var/log/dnsmasq.log' # 日志文件，如果不想保存日志可以改为 /dev/null
dnsmasq_conf_dir=()                     # `--conf-dir` 选项的参数，可以填多个，空格隔开
dnsmasq_conf_file=()                    # `--conf-file` 选项的参数，可以填多个，空格隔开
dnsmasq_conf_string=()                  # 自定义配置，一个数组元素就是一行配置，空格隔开

## chinadns
chinadns_bind_port='65353'               # chinadns-ng 服务器监听端口，通常不用改动
chinadns_timeout='5'                     # 等待上游 DNS 返回响应的超时时间，单位为秒
chinadns_repeat='1'                      # 向可信 DNS 发送几次 DNS 查询请求，默认为 1
chinadns_fairmode='false'                # 使用公平模式，具体看 chinadns-ng 的 README
chinadns_gfwlist_mode='true'            # gfwlist 模式，加载 gfwlist.txt/gfwlist.ext
chinadns_noip_as_chnip='false'           # 启用 chinadns-ng 的 `--noip-as-chnip` 选项
chinadns_verbose='false'                 # 记录详细日志，除非进行调试，否则不建议启用
chinadns_logfile='/var/log/chinadns.log' # 日志文件，如果不想保存日志可以改为 /dev/null
chinadns_privaddr4=()                    # IPv4 私有地址段，多个用空格隔开，具体见 README
chinadns_privaddr6=()                    # IPv6 私有地址段，多个用空格隔开，具体见 README

## dns2tcp
dns2tcp_bind_port='65454'               # dns2tcp 转发服务器监听端口，如有冲突请修改
dns2tcp_tcp_syncnt=''                   # dns2tcp 的 `-s` 选项，留空表示不设置此选项
dns2tcp_tcp_quickack='false'            # dns2tcp 的 `-a` 选项，选项取值为true/false
dns2tcp_tcp_fastopen='false'            # dns2tcp 的 `-f` 选项，选项取值为true/false
dns2tcp_verbose='false'                 # 记录详细日志，除非进行调试，否则不建议启用
dns2tcp_logfile='/var/log/dns2tcp.log'  # 日志文件，如果不想保存日志可以改为 /dev/null

## ipts
ipts_if_lo='lo'                 # 环回接口的名称，在标准发行版中，通常为 lo，如果不是请修改
ipts_rt_tab='233'               # iproute2 路由表名或表 ID，除非产生冲突，否则不建议改动该选项
ipts_rt_mark='0x2333'           # iproute2 策略路由的防火墙标记，除非产生冲突，否则不建议改动该选项
ipts_set_snat='false'           # 设置 iptables 的 MASQUERADE 规则，布尔值，`true/false`，详见 README
ipts_set_snat6='false'          # 设置 ip6tables 的 MASQUERADE 规则，布尔值，`true/false`，详见 README
ipts_reddns_onstop='true'       # ss-tproxy stop 后，是否将其它主机发至本机的 DNS 重定向至直连 DNS，详见 README
ipts_proxy_dst_port='1:65535'   # 黑名单 IP 的哪些端口走代理，多个用逗号隔开，冒号为端口范围(含边界)，详见 README

## opts
opts_ss_netstat='auto'                  # auto/ss/netstat，用哪个端口检测工具，见 README
opts_ping_cmd_to_use='auto'             # auto/standalone/parameter，ping 相关，见 README
opts_hostname_resolver='auto'           # auto/dig/getent/ping，用哪个解析工具，见 README
opts_overwrite_resolv='false'           # true/false/留空，如何操作 resolv.conf，见 README
opts_ip_for_check_net='114.114.114.114' # 检测外网是否可访问的 IP，ping，留空表示跳过此检查

## file
file_gfwlist_txt='/etc/ss-tproxy/gfwlist.txt'      # gfwlist/chnlist 模式预置文件
file_gfwlist_ext='/etc/ss-tproxy/gfwlist.ext'      # gfwlist/chnlist 模式扩展文件
file_ignlist_ext='/etc/ss-tproxy/ignlist.ext'      # global/chnroute 模式扩展文件
file_chnroute_set='/etc/ss-tproxy/chnroute.set'    # chnroute 地址段文件 (iptables)
file_chnroute6_set='/etc/ss-tproxy/chnroute6.set'  # chnroute6 地址段文件 (ip6tables)
file_dnsserver_pid='/etc/ss-tproxy/.dnsserver.pid' # dns 服务器进程的 pid 文件 (shell)
`

$ > ss-tproxy status

mode:     global
pxy/tcp:  [running]
dnsmasq:  [running]
dns2tcp4: [running]

**Comment by zfl9** [comment]
tproxy='true' 改为 false 试下。

**Comment by kun-qian** [comment]
@zfl9 搞定了，谢谢

**Comment by kun-qian** [comment]
@zfl9 大佬，我上次改完tproxy之后，只试了本机流量可以代理。今天试了一下作为网关，他不能代理其他机器的流量。但是我的selfonly='false'，应该是没有问题的。大佬能提供些排查思路吗？谢谢

**Comment by zfl9** [comment]
readme 都有写，监听地址改为0000

**Comment by kun-qian** [comment]
@zfl9 监听地址是0.0.0.0

后来在 wiki 里发现原因了。“有部分 Linux 系统会将 FORWARD 链的默认策略设为 DROP 状态，如果有这种情况，请进行一些合理的调整，如果对 iptables 不是很熟悉，请参照下面的步骤，配置 pre_start 钩子函数。” 参照这个解决了。

谢谢。

**Comment by blueveryday** [comment]
> @zfl9 搞定了，谢谢

兄弟，你怎么在padavan里面弄成功的？
我无法成功呢。

**Comment by blueveryday** [comment]
> kill -9 $(pidof trojan)

我按照你的修改，报错如下：
Sep  6 07:04:12 【ss_tproxy】: 运行 /etc/storage/script/sh_ss_tproxy.sh
Sep  6 07:04:12 【sh_ss_tproxy.sh】: start
Sep  6 07:04:12 【ss_tproxy】: 启动失败, 注意检查端口是否有冲突,程序是否下载完整,10 秒后自动尝试重新启动
