### ISSUE TITLE
dnsmasq问题

### ISSUE THREAD

**Issue by xinwf** [zfl9/ss-tproxy#144]
系统代理采用的是v2ray，v2ray配置按照给的示例文件配置的，正常启动没有问题，v2ray代理端口1080。
ss-tproxy改动配置如下，其它均保持默认：
```
mode='gfwlist'
tproxy='true'
selfonly='true'
proxy_svraddr4=(www.xxx.xx) #自己的服务器
proxy_tcpport='1080'
proxy_udpport='1080'
proxy_startcmd='systemctl start v2ray'
proxy_stopcmd='systemctl stop v2ray'  

dnsmasq_bind_port='60053' 
```
以上配置弄好后，通过`sudo ss-tproxy start`启动代理，启动时终端输出如下：
```
mode:     gfwlist
pxy/tcp:  [running]
pxy/udp:  [running]
dnsmasq:  [running]
```
一切正常，启动后再用`ss-tproxy status`查询，dnsmasq就stop了：
```
mode:     gfwlist
pxy/tcp:  [running]
pxy/udp:  [running]
dnsmasq:  [stopped]
```
切换到root用户下查询时，dnsmasq是`running`状态。
刚启动时可以正常打开Google和Twitter，但过了2,3分钟就不行了，各种状态还是如之前所述，dnsmasq在启动时也未报错误。
![Screenshot from 2020-06-08 14-21-40](https://user-images.githubusercontent.com/41889613/83999515-7c5e5680-a995-11ea-8256-f718ba994561.png)
![Screenshot from 2020-06-08 14-22-48](https://user-images.githubusercontent.com/41889613/83999525-7ff1dd80-a995-11ea-9b42-12e8a9ab6127.png)

**Comment by xinwf** [comment]
在我发完这个issue后，这次大概坚持了半个小时，然后又彻底挂了，中间用谷歌搜索一次，等了一会是连接失败，然后自己又刷新出来搜索结果了， 后面又过几分钟就彻底挂了，dnsmasq日志无错误，和之前的内容一样，status也与之前描述的现象一样

**Comment by xinwf** [comment]
今天有点闲就稍微看了下脚本，我先来自己回答一下这个dnsmasq状态显示的问题，因为脚本里面很多命令都是需要root权限的，所以用`sudo`执行的`ss-tproxy start`命令，这样的话里面的进程就是以root身份运行的，如果检查状态时直接输入`ss-tproxy status`，显然普通用户是无法`kill root`用户的进程的，因为检查状态的函数是这样判断的：
```bash
process_is_running() {
    kill -0 "$1" &>/dev/null
}
```
所以用`root`用户检查或者`sudo ss-tproxy status`检查，dnsmasq就是running状态，这也只能说明3个进程(`pxy/tcp, pxy/udp, dnsmasq`)状态都是正常的，但是代理服务依然是运行一段时间就不行了，大部分情况下很短，2-3分钟后可能就不能用了，先自己查一下吧

**Comment by zfl9** [comment]
去看下v2日志

**Comment by zfl9** [comment]
再读一遍readme最后一段，我相信你有所收获

**Comment by cattyhouse** [comment]
> 今天有点闲就稍微看了下脚本，我先来自己回答一下这个dnsmasq状态显示的问题，因为脚本里面很多命令都是需要root权限的，所以用`sudo`执行的`ss-tproxy start`命令，这样的话里面的进程就是以root身份运行的，如果检查状态时直接输入`ss-tproxy status`，显然普通用户是无法`kill root`用户的进程的，因为检查状态的函数是这样判断的


No, dnsmasq 需要用root启动, 但是启动之后, 默认是 nobody 身份运行的, 如果它的配置里面用了 `user=` `groupd=` 那么就是指定的用户身份运行.

`ps -ef | grep -E "[d]nsmasq" | awk '{print $1}'` 可以查看身份.

**Comment by zfl9** [comment]
自己检查下 /etc/resolv.conf，是否被其他进程改了。以及跟踪 dnsmasq/v2ray 等日志。

**Comment by zfl9** [comment]
刚启动时可以正常打开Google和Twitter，但过了2,3分钟就不行了，各种状态还是如之前所述，dnsmasq在启动时也未报错误。

不要光盯着 dnsmasq，多看看其它的配置，如 resolv.conf，以及 ps -ef | grep dnsmasq，以及 v2ray 的日志，都可以看看，以及 iptables 规则看下是否被改了，等等。我只能提供这么多信息，祝你好运。
