### ISSUE TITLE
有关默认启用了libvirtd的发行版，如何使ss-tproxy的dnsmasq和它的dnsmasq不发生端口冲突的讨论

### ISSUE THREAD

**Issue by tzwjkl** [zfl9/ss-tproxy#146]
首先libvirtd这个服务，不一定人人都在用，至少我其实根本就没在用，所以不用它的话，`systemctl disable libvirtd --now`永久并立即禁用它，并重启系统或杀掉它创建的dnsmasq进程就好了。
**但是现在不用不代表以后也不会去用，所以我还是想发起这个讨论，寻求高见。**
以下是我知道的，同时使用ss-tproxy和libvirtd时不发生dnsmasq端口冲突的办法：
1. 首先最简单的办法，就是更改ss-tproxy配置里的dnsmasq端口号。但是如 #139 所说，如果这么做了，libvirtd的dns貌似也会被重定向到ss-tproxy的dnsmasq里，感觉这样做并不好。
2. 按照[Running your own dnsmasq with libvirtd](https://wiki.libvirt.org/page/Libvirtd_and_dnsmasq)里所说，修改dnsmasq的配置。但是我发现修改过后仍然会发生冲突导致ss-tproxy启动失败，主要是在运气不好libvirtd的dnsmasq比ss-tproxy先启动的情况下。于是我在libvirtd.service配置文件里，添加了`Requires=ss-tproxy.service`，再也没有出现libvirtd抢先启动dnsmasq导致ss-tproxy启动dnsmasq失败的情况发生了，但是我发现libvirtd创建了dnsmasq进程，却并没有监听任何地址，我不确定这样对libvirtd有没有影响？（libvirtd貌似不但依靠dnsmasq进行解析，还依靠它的dhcp功能为虚拟机分配ip地址？）

**Comment by zfl9** [comment]
> 但是我发现libvirtd创建了dnsmasq进程，却并没有监听任何地址，我不确定这样对libvirtd有没有影响

没有影响的。两种方法都可以其实，具体由你们自己评估。

**Comment by tzwjkl** [comment]
> > 但是我发现libvirtd创建了dnsmasq进程，却并没有监听任何地址，我不确定这样对libvirtd有没有影响
> 
> 没有影响的。两种方法都可以其实，具体由你们自己评估。

好的。感觉还是第二种方法靠谱点。
这个issue我也先关了。
开这个issue一是希望遇到相同状况的用户能够搜索到并获得帮助，二是希望大佬们看到后能给出最标准合理的处理方法。
