### ISSUE TITLE
src-type LOCAL 没有到匹配到任何包。

### ISSUE THREAD

**Issue by Mad-Devil** [zfl9/ss-tproxy#149]
进行的操作:脚本安装完成运行正常（ chnroute），执行wget www.baidu.com。
结果：iptables中的NAT表
![image](https://user-images.githubusercontent.com/25190072/85418270-2d264180-b5a3-11ea-9ec7-eca5f33ade60.png)
问题：百度应该在白名单之中，匹配SSTP_RULE的第4条规则，实际却走了OUTPUT的默认规则。发给百度的数据包的源ip地址是本机地址，不在127.0.0.0/8中，没有匹配 SSTP_OUTPUT的第二条规则。

**Comment by zfl9** [comment]
src-type LOCAL 或 dst-type LOCAL 不是匹配 127.0.0.1，是匹配本机拥有的所有网络接口上的 ip 地址。

**Comment by zfl9** [comment]
请把配置完整发来，iptables规则完整发来
