### ISSUE TITLE
请教一下这个mode变更是不是个bug？

### ISSUE THREAD

**Issue by blueveryday** [zfl9/ss-tproxy#153]
```shell
## mode
#mode='global'  # global 模式 (不分流)
#mode='chnlist' # 回国模式 (china走代理)
#mode='gfwlist' # gfwlist 模式 (黑名单)
mode='global' # chnroute 模式 (白名单)
```

HIBOY的padavan固件，发现个问题。
我设置tproxy为走gfwlist模式，设置好以后，mode='gfwlist'是正确的。
然后不启动第三方dns程序，直接用8035口，应用保存以后，这个mode值就变成global了，而非之前设置的gfwlist值。
然后我感觉网络好像也有些问题，走路由器IP地址打开页面就很慢。有些视频解析网站也很慢。
请教如何确定tproxy是走gfwlist模式了呢？
谢谢。

**Comment by zfl9** [comment]
不了解，可去请教下 hiboy。

**Comment by blueveryday** [comment]
> 不了解，可去请教下 hiboy。

谢谢
