### ISSUE TITLE
客户端纯IPv4网络是否支持IPv6透明代理

### ISSUE THREAD

**Issue by wyf88** [zfl9/ss-tproxy#154]
作者您好，

想请教个问题：服务端支持IPv4与IPv6，客户端纯IPv4网络，现已通过ss-redir与ss-tproxy成功搭建IPv4透明代理。那么能否使透明代理支持IPv6，使得客户端可以访问IPv6网站？尝试过naive地在设置中开启`ipv6="true"`似乎是不够的：
```
$ wget ipv6.google.com
--2020-07-13 00:46:14--  http://ipv6.google.com/
Resolving ipv6.google.com (ipv6.google.com)... 2404:6800:4005:804::200e
Connecting to ipv6.google.com (ipv6.google.com)|2404:6800:4005:804::200e|:80... failed: Network is unreachable.
```
因此想请教下，此用法能否实现？能否给个思路？非常感谢！

**Comment by zfl9** [comment]
> failed: Network is unreachable.

这个错误可能是因为你本地没有配置 ipv6 路由表（我猜）

**Comment by zfl9** [comment]
纯v4的话，估计有点麻烦，也许可以支持，但是我目前没有这种测试环境，所以也帮不了你。

**Comment by wyf88** [comment]
好的谢谢！
