### ISSUE TITLE
ss-tproxy和你推荐的dig命令有冲突

### ISSUE THREAD

**Issue by Takea3** [zfl9/ss-tproxy#157]
安装dnsutils后proxy_svraddr4这一项填写域名大于两个就无法使用了，只填一个域名也是时灵时不灵的。程序症状是，运行start 命令后，程序就不动了，感觉就是死了，啥都不输出，就停在那了。然后把dnsutils卸载（还卸载了一个自动安装的包）后一切正常

**Comment by zfl9** [comment]
什么系统，dnsutils里面有什么命令。卡住了就加上 -x 参数，把输出发过来。。。服了你们。
