### ISSUE TITLE
请教padavan里面trojan的透明代理问题

### ISSUE THREAD

**Issue by blueveryday** [zfl9/ss-tproxy#159]
在padavan里面，已经可以通过路由器的1080端口代理上网了。
但是无法实现透明代理。

看了很久的ss-tproxy说明，这一点看不懂，求教。
如下部分内容怎么设置才可以让trojan的1080端口实现透明代理呢？
谢谢。

## proxy
proxy_all_svraddr='0.0.0.0' # 服务器的地址或域名的配置文件，会自动处理分类IPv4、IPv6，允许填写多个服务器地址(文件里面每一行一个服务器地址)
proxy_svraddr4="0.0.0.0" # 服务器的 IPv4 地址或域名的配置文件，允许填写多个服务器地址(文件里面每一行一个服务器地址)
proxy_svraddr6="/opt/app/ss_tproxy/conf/proxy_svraddr6.conf" # 服务器的 IPv6 地址或域名的配置文件，允许填写多个服务器地址(文件里面每一行一个服务器地址)
proxy_svrport='1:65535' # 服务器的监听端口，可填多个端口，格式同 ipts_proxy_dst_port
proxy_tcpport='1080' # ss/ssr/v2ray 等本机进程的 TCP 监听端口，该端口支持透明代理
#proxy_udpport='1080' # ss/ssr/v2ray 等本机进程的 UDP 监听端口，该端口支持透明代理
proxy_startcmd='nohup /media/AiDisk_a1/trojan/trojan -c /media/AiDisk_a1/trojan/config.json &' # 用于启动本机代理进程的 shell 命令，该命令应该能立即执行完毕
proxy_stopcmd='kill -9 $(pidof trojan)' # 用于关闭本机代理进程的 shell 命令，该命令应该能立即执行完毕

**Comment by zfl9** [comment]
`已经可以通过路由器的1080端口代理上网了`。你这个是通过 socks5 代理的吧。透明代理和socks5代理不一样。认真看下文档，或者去 trojan 那里请问下如何设置透明代理的端口，没用过 trojan。

**Comment by blueveryday** [comment]
> `已经可以通过路由器的1080端口代理上网了`。你这个是通过 socks5 代理的吧。透明代理和socks5代理不一样。认真看下文档，或者去 trojan 那里请问下如何设置透明代理的端口，没用过 trojan。

是通过本地的socks5服务的，想把这个服务做成透明代理。

**Comment by zfl9** [comment]
需要借助ipt2socks/redsocks2

**Comment by zfl9** [comment]
文档都有写的，认证看。
