### ISSUE TITLE
透明代理性能

### ISSUE THREAD

**Issue by IMconnor** [zfl9/ss-tproxy#160]
不是针对这个脚本，借用该issue想问问大家用透明代理有没有遇到其性能不稳定的状况，本人有点不知道是什么环节出现问题了。
网络环境是这样

- openwrt (192.168.1.1),

- v2ray box (192.168.1.200) with socks 5 and transparent proxy enabled.

v2ray设备由ss-tproxy来设置，openwrt做策略路由将特定流量转发至v2ray设备，在其它LAN设备（比如192.168.1.198）上测试网络速度

- 策略路由，在openwrt执行
`ip rule add from 192.168.1.198 table 200`
`ip route add default via 192.168.1.200 table 200 dev br-lan`
LAN设备网络（甚至国内流量，这基本可以排除是v2ray的问题）速度很不稳定，时快时慢。往上游排查，v2ray设备的自身透明代理速度比较稳定（排除ss-tproxy的问题），在LAN设备用socks 5代理也很稳定。为什么将其作网关就拉跨了，着实费解，是路由器的问题吗？看上去像是v2ray设备当网关性能不得劲？求解…

**Comment by zfl9** [comment]
没有遇到过，不用v2ray。未察觉。
