### ISSUE TITLE
2020.12.01拉去ss-redir以支持TCP、UDP全走TRPOXY，但上标注错误

### ISSUE THREAD

**Issue by haochenghhc** [zfl9/ss-tproxy#168]
https://github.com/zfl9/ss-tproxy/wiki

> 先说 ss/ssr 透明代理吧，ss-redir 是 ss-libev、ssr-libev 中的一个工具，配合 iptables 可以在 Linux 上实现 ss、ssr 透明代理，ss-redir 的 TCP 透明代理是通过 REDIRECT 方式实现的，而 UDP 透明代理是通过 TPROXY 方式实现的。注意：ss-redir 只存在于 libev 版本。

这里需要跟新一下了，ss-redir以支持TCP、UDP全走TRPOXY，只需要加入-T参数
而且功能还是hub主加入的，wiki建议同时更新

**Comment by zfl9** [comment]
已更新， 感谢。

**Comment by cattyhouse** [comment]
> https://github.com/zfl9/ss-tproxy/wiki
> 
> > 先说 ss/ssr 透明代理吧，ss-redir 是 ss-libev、ssr-libev 中的一个工具，配合 iptables 可以在 Linux 上实现 ss、ssr 透明代理，ss-redir 的 TCP 透明代理是通过 REDIRECT 方式实现的，而 UDP 透明代理是通过 TPROXY 方式实现的。注意：ss-redir 只存在于 libev 版本。
> 
> 这里需要跟新一下了，ss-redir以支持TCP、UDP全走TRPOXY，只需要加入-T参数
> 而且功能还是hub主加入的，wiki建议同时更新

哈哈, 这个 -T 功能就是 ss-tproxy 作者 zfl9 加进去的...
