### ISSUE TITLE
B站电影无法播放提示您所在的地区无法观看本片

### ISSUE THREAD

**Issue by tefiszx** [zfl9/ss-tproxy#170]
最终充值了哔哩哔哩大会员，结果在开启ss-tproxy的情况下看电影，会出现区域限制。应该是我的代理地址访问了b站，才会导致上述情况。也不知道是B站哪个IP网段被加入了代理列表。我参照[这个列表](https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/Ruleset/Bilibili.list)尝试着把这些域名和网段加入ignlist.ext，重启ss-tproxy，依然如故。
请问@zfl9，有什么方法可以修正这个问题吗？

**Comment by zfl9** [comment]
关闭b站客户端，手机开关一下飞行模式，再试？

**Comment by zfl9** [comment]
可能是手机或者app有dns缓存吧

**Comment by zfl9** [comment]
还有ignlist.ext只有在global/chnroute模式下生效哦。

**Comment by zfl9** [comment]
1.先关闭b站相关客户端
2.最好开一下飞行模式（可选）
3.然后往ignlist里面添加这些网段及域名（虽然不确定你引用的那个页面里的ip和域名是否仍然有效）
4.然后重启ss-tproxy
5.关闭飞行模式
6.开启B站客户端看下

**Comment by tefiszx** [comment]
> 1.先关闭b站相关客户端
> 2.最好开一下飞行模式（可选）
> 3.然后往ignlist里面添加这些网段及域名（虽然不确定你引用的那个页面里的ip和域名是否仍然有效）
> 4.然后重启ss-tproxy
> 5.关闭飞行模式
> 6.开启B站客户端看下

无论如何，谢谢作者及时而不厌其烦地回复。我是在PC上看B站出现的这个问题，ss-tporxy使用的是chnroute模式。这个情况在我的软路由上也发生了，我再研究研究。谢谢。关闭这个issue了。
