### ISSUE TITLE
是不是可以考虑使用-m owner来替代单独制定服务器ip来避免死循环？

### ISSUE THREAD

**Issue by cjwddtc** [zfl9/ss-tproxy#174]
显示的指定ip后通过在iptables指定该ip不走代理的这种方式有一个很致命的问题，就是必须显示确定服务器的ip地址。

而iptables支持一种更为方便的分流方式，那就是通过-m owner选项指定对某一个uid或某一个gid的所有进程的流量进行操作。
这样通过将代理程序运行在一个特定的gid下（这里是因为很多时候代理软件可能会需要root权限，因此最好不要修改uid）,并通过iptables将这个gid的所有流量都return就，可以避免回环的问题。
这样能够简化配置（减少一个需要手动输入的配置）

**Comment by zfl9** [comment]
应该是可以的，有时间弄下

**Comment by zfl9** [comment]
想起个东西，v2ray客端貌似每次连接server之前，都会去解析server的ip地址（如果填写的是域名的话），而又因为启动代理后，/etc/resolv.conf里面的nameserver已经指向了127.0.0.1（dnsmasq -> ... -> v2ray-client），会造成死循环。
PS: 我现在想起来了为啥之前不使用uid/gid来pass代理自身流量的原因了。不过其实也有办法，就是在output/nat处，加一条规则，将代理软件发出的目的地址为127.0.0.1/53的dns请求dnat到114等常规dns去。

**Comment by Jaivv** [comment]
> 想起个东西，v2ray客端貌似每次连接server之前，都会去解析server的ip地址（如果填写的是域名的话），而又因为启动代理后，/etc/resolv.conf里面的nameserver已经指向了127.0.0.1（dnsmasq -> ... -> v2ray-client），可能会造成死循环（与dnsmasq以及相关dns组件里面的分流规则有关系）。不知道现在v2ray是不是依旧每次连接server前都会去解析server域名的ip。很久没用了。
> 
> PS: 我现在想起来了为啥之前不使用uid/gid来pass代理自身流量的原因了。不过其实也有办法，就是在output/nat处，加一条规则，将代理软件发出的目的地址为127.0.0.1/53的dns请求dnat到114等常规dns去（具体还没测试，理论上是这样）。

配置文件里设置了就会用，没有就是用/etc/resolv.conf的dns

**Comment by zfl9** [comment]
> 想起个东西，v2ray客端貌似每次连接server之前，都会去解析server的ip地址（如果填写的是域名的话），而又因为启动代理后，/etc/resolv.conf里面的nameserver已经指向了127.0.0.1（dnsmasq -> ... -> v2ray-client），可能会造成死循环（与dnsmasq以及相关dns组件里面的分流规则有关系）。不知道现在v2ray是不是依旧每次连接server前都会去解析server域名的ip。很久没用了。
> 
> PS: 我现在想起来了为啥之前不使用uid/gid来pass代理自身流量的原因了。不过其实也有办法，就是在output/nat处，加一条规则，将代理软件发出的目的地址为127.0.0.1/53的dns请求dnat到114等常规dns去（具体还没测试，理论上是这样）。

在本地简陋的测试了一下，因为resolv.conf中的nameserver是127.0.0.1，在nat/OUTPUT链DNAT到114.114.114.114之后，会出现`socket.c:1738: internal_send: 127.0.0.1#53: Invalid argument` 报错(dig测试)，猜测原因应该是src地址为127.0.0.1而dst地址被DNAT改为了114.114.114.114（一个local地址一个public地址），为了验证这个猜想，我将resolv.conf里面的nameserver改为了192.168.1.1(本机ens33网卡的ip)，然后测试DNAT正常（去程确实DNAT到114去了，并且回程也没问题，正常SNAT回来了）。

然后，我想到有2个方式，处理这个问题：
1. 将resolv.conf的nameserver改为非127.0.0.1的监听地址，比如192.168.1.1，但是粗略的看了下ss-tproxy里面的规则，很多都是直接默认nameserver为127.0.0.1，如果要强行改为192.168.1.1这种地址，应该有点麻烦，甚至会有未预想到的bug，所以暂时不考虑此方式。
2. 用C语言写一个简易的dns转发器，此转发器运行在sstproxy主机，监听127.0.0.1:53/udp，分别指定两个上游dns，一个是原先的dnsmasq（监听端口改为非53，比如54），一个是114.114.114.114:53这种公共dns。具体的分流思路为：
  - iptables通过owner模块匹配本机代理程序向127.0.0.1:53/udp发出的dns请求包，对其设置ip_tos值，比如0xFC。
  - 然后在此dns转发器内，通过ip_tos的值，区分是本机代理程序的dns请求还是其他常规程序的dns请求，如果是代理程序发出的，则将其转发给114.114.114.114公共dns（跳过相关的代理，走直连），如果是常规程序发出的，则将其转发给dnsmasq（54端口），走原有的代理以及分流逻辑（gfwlist、chnroute等）。

**Comment by zfl9** [comment]
ref: https://serverfault.com/questions/646522/port-forward-with-iptables

看样子只要设置`net.ipv4.conf.all.route_localnet=1`内核参数就行了，不需要那个转发器了(明天我测试下)

**Comment by zfl9** [comment]
测试成功，开始改脚本了，新增【uid/gid放行proxy进程传出流量】的方式，原先的ip/hostname也留着，兼容旧版本。

**Comment by zfl9** [comment]
已更新，v4.6.1。目前个人测试正常。

**Comment by flyhigherpi** [comment]
华硕路由iptables不支持owner，4.6可以避免output回环？

**Comment by zfl9** [comment]
不支持那就使用proxy_svraddr+port传统模式咯（最好还是先办法支持iptables owner模块，应该是少了什么模块没加载而已吧）

**Comment by zfl9** [comment]
> 华硕路由iptables不支持owner，4.6可以避免output回环？

一直都支持避免output回环，只是4.6.1新增了一种方式而已，现在4.6.1有两种方式可选，4.6只有一种（那就是指定svraddr+svrport）

**Comment by elvisw** [comment]
Openwrt会不会也不支持
