### ISSUE TITLE
大佬，提个建议，能否加入Qos功能

### ISSUE THREAD

**Issue by yeguhe** [zfl9/ss-tproxy#176]
大佬好，这套脚本用着效果很好，稳定运行近一年了。实际使用中发现一些场景，带宽总因个别用户无节制下载造成其它网内用户上网体验卡死，可否增加一个限制所有网内用户的每ip 带宽峰值的功能，比如需要代理的ip段每ip最多跑到固定的几兆。大佬如果没有时间帮忙实现，也可给个实现思路，不胜感激！！！

**Comment by zfl9** [comment]
可以看下，关键字 tc 流量控制
https://www.v2ex.com/t/519896

**Comment by yeguhe** [comment]
好的，非常感谢！
