### ISSUE TITLE
大佬好，遇到bug，可否帮忙分析下

### ISSUE THREAD

**Issue by yeguhe** [zfl9/ss-tproxy#177]
现象：在 chroute 模式下，钉钉的 oa 审批页面时不时的打不开，微信的朋友圈，时不时打不开，排查发现， 两个功能使用的网址 故障时被解析到的国外ip上，大部分情况下解析到国内ip时一切正常，不确定是不是 chinadns-ng 的 bug  ，查看了 chinadns-ng 的文档，发现有chnlist-file ，可以把国内域名加里面解决解析异常的问题，但 ss-tproxy 里没有这个文件，只有一个  ignlist.ext ，不确定是不是与 chnlist-file文件对应？ chinadns-ng里提到的公平模式似乎能缓解这一问题，但不确定是否有效果，尚需测试.

**Comment by zfl9** [comment]
ignlist.ext 有用的，是通过 dnsmasq 处理的。

**Comment by zfl9** [comment]
chinadns-ng里提到的公平模式 + ignlist.ext白名单，应该就可以了。（记得清空dns缓存再测）

**Comment by yeguhe** [comment]
好的，感谢大佬!
