### ISSUE TITLE
大佬求助下tproxy代理tcp后导致端口转发失效

### ISSUE THREAD

**Issue by flyhigherpi** [zfl9/ss-tproxy#178]
外网入站，比如远程桌面这些都失败了。
看的v2ray小白文的，用了这个tproxy配置，遇到这个问题刚好谷歌到这个项目

**Comment by zfl9** [comment]
所以？用的不是sstproxy脚本咯？那这个问题请找v2ray小白文作者，sstproxy我印象中是没有这个问题的。

**Comment by flyhigherpi** [comment]
> 所以？用的不是sstproxy脚本咯？那这个问题请找v2ray小白文作者，sstproxy我印象中是没有这个问题的。

是啊。啃SSTPRPXY源码中，看下入站TCP怎么绕开。不懂再来请教

**Comment by flyhigherpi** [comment]
> 所以？用的不是sstproxy脚本咯？那这个问题请找v2ray小白文作者，sstproxy我印象中是没有这个问题的。

DONE.clash配合大佬的TPROXY处理iptables规则，VPN正常，TPROXY代理TCP UDP正常，远程桌面正常
