### ISSUE TITLE
新版4.61新增的proxy_procuser/proxy_procgroup方式只适合 REDIRECT 模式吗？

### ISSUE THREAD

**Issue by bluehj777** [zfl9/ss-tproxy#180]
请问下，我的服务端是ss-libev 3.35,，启用的是 纯 TPROXY 模式 ，在4.60下一切正常。但升级了4.61，在纯 TPROXY 模式下，如果启用proxy_procuser/proxy_procgroup，proxy -c"（xxxxxxxxxx ）的话，不能成功代理了，换回原来的proxy_svraddr/proxy_svrport方式没有问题。

**Comment by zfl9** [comment]
你是不是没有使用setcap给ss-redir设置net_admin、bind_service特权？

**Comment by zfl9** [comment]
按理来说都支持的，你看下readme的ss-redir启动命令，那里，有些的

**Comment by bluehj777** [comment]
我的印象里用这个命令给过权限的。我再试试。还有请问下新增这个参数比原来的方式有何优势呢？文档里写的是推荐方式

**Comment by zfl9** [comment]
优势就是方便切换节点，之前的方式切换节点需要同时修改ss的配置文件指向，以及ss-tproxy的svraddr/port。现在的方式只需要切换ss的配置文件指向即可。

**Comment by bluehj777** [comment]
好的，谢谢.
