### ISSUE TITLE
只代理局域网机器

### ISSUE THREAD

**Issue by ztoofar** [zfl9/ss-tproxy#182]
你好,我需要代理局域网机器,本机的话不是很需要,这个脚本的话selfonly我不管选择哪个选项都会导致我局域网内要做透明代理的这台机器上的服务公网无法访问,比如我想在家外面连接ssh或者连接我自己搭建的网盘,请问有什么方法吗

**Comment by fbi007130** [comment]
请问是不打算做这个feature吗？我自己也有这个需求。

**Comment by zfl9** [comment]
https://github.com/zfl9/ss-tproxy/blob/ad43070cd3f8c241dfd478c4d8ac1106bfbcbb69/ss-tproxy.conf#L31
