### ISSUE TITLE
不能代理局域网流量（主要是无线网络，应该与路由器设置有关）

### ISSUE THREAD

**Issue by ansoda** [zfl9/ss-tproxy#183]
![image](https://user-images.githubusercontent.com/5748600/110886213-45054780-8323-11eb-9873-20b15c8a72d4.png)
本机流量代理没有问题，但是局域网流量不能代理。
ip_forward也置成1了

**Comment by zfl9** [comment]
看文档，ipts_set_snat/snat6 改为true看下

**Comment by ansoda** [comment]
我也改了，还是不行。你测试没有问题？

**Comment by ansoda** [comment]
仔细研究了，怎么配置都不行，我怀疑这个代理局域网流量有问题

**Comment by ansoda** [comment]
我是通过虚拟机装ubuntu做的旁路代理，主机windows的网关和dns都设置成这个ubuntu的ip了，还是不行，不知道哪里有问题。

**Comment by Roundygg** [comment]
我这边类似。debian10做网关。

**Comment by Roundygg** [comment]
我这边类似，debian10做网关，白名单模式。本身流量可以正确的国内外分流。但是局域网流量只能上外网，，看到dns已正确解析，国内网站打不开。ipts_set_snat/snat6 已改为true，本机代理监听地址为0.0.0.0，已修改 /etc/sysctl.conf，开启net.ipv4.ip_forward=1。也是不知道哪里有问题。

**Comment by zfl9** [comment]
https://github.com/zfl9/ss-tproxy/wiki/Linux-%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by zfl9** [comment]
把pre_start这个钩子函数加上(见链接里面的)

**Comment by zfl9** [comment]
> 我这边类似，debian10做网关，白名单模式。本身流量可以正确的国内外分流。但是局域网流量只能上外网，，看到dns已正确解析，国内网站打不开。�ipts_set_snat/snat6 已改为true，本机代理监听地址为0.0.0.0，已修改 /etc/sysctl.conf，开启net.ipv4.ip_forward=1。也是不知道哪里有问题。

你这个现象，90%的概率都是FORWARD链被默认DROP了。

**Comment by ansoda** [comment]
@zfl9 你说的方法我都试过了，还是不行，怎么都不能代理局域网流量，我自己先研究下脚本吧。

**Comment by zfl9** [comment]
> 我也改了，还是不行。你测试没有问题？

肯定是没问题的，我一直都用的很正常。

**Comment by ansoda** [comment]
> > 我也改了，还是不行。你测试没有问题？
> 
> 肯定是没问题的，我一直都用的很正常。

好的，谢谢，我再研究下吧

**Comment by ansoda** [comment]
> > 我这边类似，debian10做网关，白名单模式。本身流量可以正确的国内外分流。但是局域网流量只能上外网，，看到dns已正确解析，国内网站打不开。�ipts_set_snat/snat6 已改为true，本机代理监听地址为0.0.0.0，已修改 /etc/sysctl.conf，开启net.ipv4.ip_forward=1。也是不知道哪里有问题。
> 
> 你这个现象，90%的概率都是FORWARD链被默认DROP了。参考wiki里面的faq，将pre_start钩子设置好就可以了。

全局代理模式下，我在ubuntu20.04上直接局域网代理不出去，本机没有问题；在ubuntu16.04下面，局域网能上google，其他上不了，本机都没有问题。

**Comment by Roundygg** [comment]
> > 我这边类似，debian10做网关，白名单模式。本身流量可以正确的国内外分流。但是局域网流量只能上外网，，看到dns已正确解析，国内网站打不开。�ipts_set_snat/snat6 已改为true，本机代理监听地址为0.0.0.0，已修改 /etc/sysctl.conf，开启net.ipv4.ip_forward=1。也是不知道哪里有问题。
> 
> 你这个现象，90%的概率都是FORWARD链被默认DROP了。参考wiki里面的faq，将pre_start钩子设置好就可以了。

感谢！解决了我的问题。

**Comment by ansoda** [comment]
> > 我也改了，还是不行。你测试没有问题？
> 
> 肯定是没问题的，我一直都用的很正常。

你好，我发现问题在哪里了，我在vmware中通过桥接的方式安装了ubuntu A，配置好了ss-tproxy，此ubuntu A本机能正常代理。然后我在vmware中又通过桥接的方式安装了ubuntu B，将ubuntu A设置成其网关，此ubuntu B也能正常代理，说明ss-tproxy配置都是没有问题的。
但是我通过其他的iphone，mac等设备连接wifi后将网关设置成ubuntu A就不可以代理上网。请问下，通过虚拟机桥接的方式将ubuntu做网关，是不是有什么我没有注意到因素，导致iphone，mac等代理不出去呢？
感谢作者，脚本是好用的，没有问题。

**Comment by zfl9** [comment]
你在其他设备(iphone/mac)上能正常访问vmware的ubuntu-A主机吗（正常网关/dns的情况下，能否正常访问ubuntu-A主机？）

**Comment by ansoda** [comment]
> 你在其他设备(iphone/mac)上能正常访问vmware的ubuntu-A主机吗（正常网关/dns的情况下，能否正常访问ubuntu-A主机？）

可以访问，mac和ubuntu-A属于同一个网段，可以互相ping通，但是不能通过ubuntu-A作为网关代理(iphone/mac)。

**Comment by zfl9** [comment]
暂时先关了，有新反馈再reopen吧。

**Comment by liangzhdp** [comment]
> > > 我也改了，还是不行。你测试没有问题？
> > 
> > 
> > 肯定是没问题的，我一直都用的很正常。
> 
> 你好，我发现问题在哪里了，我在vmware中通过桥接的方式安装了ubuntu A，配置好了ss-tproxy，此ubuntu A本机能正常代理。然后我在vmware中又通过桥接的方式安装了ubuntu B，将ubuntu A设置成其网关，此ubuntu B也能正常代理，说明ss-tproxy配置都是没有问题的。
> 但是我通过其他的iphone，mac等设备连接wifi后将网关设置成ubuntu A就不可以代理上网。请问下，通过虚拟机桥接的方式将ubuntu做网关，是不是有什么我没有注意到因素，导致iphone，mac等代理不出去呢？
> 感谢作者，脚本是好用的，没有问题。

楼主解决了吗？我也是本机代理、分流均正常，局域网可访问国内网，但翻不了。

**Comment by sunlewuyou** [comment]
@zfl9 跟这位楼主的问题一样，物理机安装Ubuntu做旁路由，按照上面的解决方法试了个遍，还是不能让局域网其他主机代理，Ubuntu本机是可以代理的。

**Comment by zfl9** [comment]
snat 设置为true看看

**Comment by zfl9** [comment]
如果ss-tproxy所在的主机是通过`WLAN`连接局域网，目前无法代理，具体原因不清楚，估计是无线网卡需要设置什么。

> 而且因为 无线(WLAN) 不能像 有线(LAN) 这样全双工，所以即使上述情况能调通，性能也不佳。

**Comment by zfl9** [comment]
除了WLAN这个情况，另一个常见原因就是某些 交换机/路由器 比较特殊，如果不在 ss-tproxy 主机上设置 SNAT 规则，那么对应的包会被丢弃，无法通过 交换机。

> 客户机 -> [交换机] -> tproxy主机 -> [交换机] -> [路由器] -> 外网

应该是第二个 **交换机** 这里，把包丢弃了，可能是 `src mac address` 与通过 `src ip`反查出来的`mac address` 不匹配，因为`src ip`是客户机的，但`src mac address`是tproxy主机的。

**Comment by sunlewuyou** [comment]
@zfl9 snat、pre_start 都设置了，防火墙也确认了默认策略都是放行的，只是我装Ubuntu的笔记本网卡是接的有线，不过网线是接到一个无线中继过来的路由器上的，不知道是不是这也有影响。
然后请问：
```
## proxy
# user/group(#1,推荐) vs svraddr+port(#2), user/group选其中一个填写(不建议都填)
proxy_procuser='proxy'   # 本机代理进程的 user/uid，用来放行本机代理进程传出的流量
proxy_procgroup=''       # 本机代理进程的 group/gid，用来放行本机代理进程传出的流量
proxy_svraddr4=()        # 服务器的 IPv4 地址或域名，允许填写多个服务器地址，空格隔开
proxy_svraddr6=()        # 服务器的 IPv6 地址或域名，允许填写多个服务器地址，空格隔开
proxy_svrport=''         # 服务器的监听端口，可填多个端口，格式同 ipts_proxy_dst_port
proxy_tcpport='60080'    # ss/ssr/v2ray 等本机进程的 TCP 监听端口，该端口支持透明代理
proxy_udpport='60080'    # ss/ssr/v2ray 等本机进程的 UDP 监听端口，该端口支持透明代理
```
上面这段配置，我用的naive代理，代理本机是没问题的，代理其他局域网主机需要改动哪里吗？proxy_svraddr4=() proxy_svrport='' 这里要填国外主机的IP和端口吗？因为我这里没填本机也能代理，所以不知这两个配置的意义何在，谢谢解答。

**Comment by zfl9** [comment]
proxy_svraddr、proxy_svrport 是老版本的，新版本不建议使用。留着只是为了兼容。所以不填是没有问题的（新机制是procuser/group）

**Comment by zfl9** [comment]
局域网是无法代理，还是无法连接到网络（局域网、或者公网），现象不同，则原因可能不同。

**Comment by sunlewuyou** [comment]
@zfl9 局域网主机，我用手机测试设置其为路由后，无法上网，通过其他电脑cmd下测试dns好像也正常：
```
C:\Users\Administrator>nslookup www.google.com 192.168.10.2
服务器:  UnKnown
Address:  192.168.10.2

非权威应答:
名称:    www.google.com
Addresses:  2607:f8b0:4007:80a::2004
          142.250.188.228
···

**Comment by zfl9** [comment]
dns正常是可以理解的，因为dns解析过程就是个简单的 client <-> server 交互，没有其他复杂的网络拓扑。

**Comment by sunlewuyou** [comment]
@zfl9 手机修改其为路由后，微信是能发送信息的，应该是dns的问题。

**Comment by sunlewuyou** [comment]
@zfl9 等下有时间直接接同一台路由上测试看看正不正常。先谢谢了。感谢及时回复！

**Comment by zfl9** [comment]
那打开 dnsmasq 的 verbose 日志（ss-tproxy.conf），然后观察其日志，看是否有收到 客户机的请求，如果正常，再查下一级（比如是chnroute分流，则查chinadns-ng）

**Comment by sunlewuyou** [comment]
谢谢授人以渔。

**Comment by sunlewuyou** [comment]
@zfl9 经过多次测试，我甚至在笔记本Ubuntu系统利用docker搭建openwrt旁路由也是一样的状况，最终还是有线方式接到同一台路由器下解决问题，实验证明看来用笔记本自带wifi或是用两个路由器无线中继连网线的方式都不成功，不知道这里面具体的原因在哪里，略表遗憾。

**Comment by zfl9** [comment]
嗯，感觉只要涉及到无线网，就不好使。

**Comment by sunlewuyou** [comment]
> 除了WLAN这个情况，另一个常见原因就是某些 交换机/路由器 比较特殊，如果不在 ss-tproxy 主机上设置 SNAT 规则，那么对应的包会被丢弃，无法通过 交换机。
> 
> > 客户机 -> [交换机] -> tproxy主机 -> [交换机] -> [路由器] -> 外网
> 
> 应该是第二个 **交换机** 这里，把包丢弃了，可能是 `src mac address` 与通过 `src ip`反查出来的`mac address` 不匹配，因为`src ip`是客户机的，但`src mac address`是tproxy主机的。

@zfl9 普通家用tp路由，找了找没看到什么有可能关联的设置项。

**Comment by sunlewuyou** [comment]
> 嗯，感觉只要涉及到无线网，就不好使。

@zfl9 嗯。学习了，底层知识看来只有大佬搞得清了，早点休息哟~

**Comment by zfl9** [comment]
> 

这个一般家用路由找不到设置项的，只能通过在ss-tproxy主机开启snat选项来解决。

**Comment by sunlewuyou** [comment]
> 嗯，感觉只要涉及到无线网，就不好使。

@zfl9 [关于旁路由设置后，主路由WIFI无法上网的问题](https://cloud.tencent.com/developer/article/2036952)
这篇文章解释了我的疑惑，与君分享。

**Comment by zfl9** [comment]
先关了。
