### ISSUE TITLE
全局模式下，能否弄个开完关闭dnsmasq解析？

### ISSUE THREAD

**Issue by ansoda** [zfl9/ss-tproxy#184]
1、全局模式下，能否做个开关关闭dnsmasq解析，直接把53端口流量路由给v2ray，这里面可以配置更复杂的dns解析规则。
2、全局模式下，关闭了dns解析后不需要校验是否安装了dnsmasq和chinadns-ng等插件。

**Comment by zfl9** [comment]
暂时没时间弄，抱歉。

**Comment by aliyuchang33** [comment]
同求，最近也遇上这个需求了

**Comment by zfl9** [comment]
> 1、全局模式下，能否做个开关关闭dnsmasq解析，直接把53端口流量路由给v2ray，这里面可以配置更复杂的dns解析规则。 2、全局模式下，关闭了dns解析后不需要校验是否安装了dnsmasq和chinadns-ng等插件。

**Comment by xtccc** [comment]
需要这个功能， 我想用 smartdns 替换dnsmasq 和 chinadns-ng

**Comment by zfl9** [comment]
> 1、全局模式下，能否做个开关关闭dnsmasq解析，直接把53端口流量路由给v2ray，这里面可以配置更复杂的dns解析规则。 2、全局模式下，关闭了dns解析后不需要校验是否安装了dnsmasq和chinadns-ng等插件。

你说的这个方案，其实没有必要上 ss-tproxy 脚本，因为只需要几条简单的 iptables 规则，将全部流量导给v2ray，并且dns也指向v2ray，分流和dns相关逻辑全部由 v2ray 负责。这种做法我认为很多教程都有，实施起来也不是很复杂。

**Comment by zfl9** [comment]
> 需要这个功能， 我想用 smartdns 替换dnsmasq 和 chinadns-ng

这种需求就需要自己修改脚本了，不考虑加入主线脚本。
因为此类需求无穷无尽，dns解决方案太多了，很难全部实现。
