### ISSUE TITLE
执行ss-tproxy start后显示waiting for network available...

### ISSUE THREAD

**Issue by livinghub** [zfl9/ss-tproxy#190]
我的环境是没有网的，需要使用代理才能连上网。因为觉得每次都要手动连接代理来上网很不方便，所以才想弄一个透明代理，但是在配置好conf后，执行ss-tproxy start却显示waiting for network available。
请问我可以如何解决这个问题？谢谢。

**Comment by zfl9** [comment]
提示很明显了，需要你的机器有互联网。

**Comment by livinghub** [comment]
> 提示很明显了，需要你的机器有互联网。

是的，我知道。我想知道有无选项可以跳过这个联网检测。

**Comment by zfl9** [comment]
readme有写
> opts_ip_for_check_net：指定一个允许 Ping 的 IP 地址（IPv4 或 IPv6 都行），用于检查外部网络的连通情况，如果此选项留空则表示跳过网络可用性检查（不建议）。默认为 114.114.114.114，注意这个 IP 地址应该为公网 IP，如果你填一个私有 IP，即使检测成功，也不能保证外网是可访问的，因为这仅代表我可以访问这个内网。根据实际网络环境进行更改，一般改为延迟较低且较稳定的一个 IP。

**Comment by zfl9** [comment]
我并不想回答readme中可以找到答案的问题。

**Comment by livinghub** [comment]
抱歉，谢谢你

> 我并不想回答readme中可以找到答案的问题。
