### ISSUE TITLE
透明代理客户端 DNS 设置和使用 clash 分流问题

### ISSUE THREAD

**Issue by m2acgi** [zfl9/ss-tproxy#193]
您好，请教两个问题:
1. 正常情况下，ss-tproxy 的透明代理客户端（局域网要使用透明代理服务器的 PC）DNS 如何设置，是设置为透明代理服务器即 ss-tproxy 的 IP 地址吗？

2. 想使用 ss-tproxy 作为公司各分支机构的透明代理网关，用于代替硬件 VPN 与总部互连。现在假设有一个无污染的 DNS Server, 所有 PC 都在使用这个 DNS 服务器 (不使用 chinadns + dnsmasq 这一套)，然后 ss-tproxy 使用全局模式，分流由 clash 的 IP 规则处理。请问要如何配置 ss-tproxy 呢？

这个项目很有用，建议放置一个捐赠的二维码。

**Comment by zfl9** [comment]
> 正常情况下，ss-tproxy 的透明代理客户端（局域网要使用透明代理服务器的 PC）DNS 如何设置，是设置为透明代理服务器即 ss-tproxy 的 IP 地址吗？

dns和网关都设置为ss-tproxy机器的ip（readme都有写的）

**Comment by zfl9** [comment]
> 想使用 ss-tproxy 作为公司各分支机构的透明代理网关，用于代替硬件 VPN 与总部互连。现在假设有一个无污染的 DNS Server, 所有 PC 都在使用这个 DNS 服务器 (不使用 chinadns + dnsmasq 这一套)，然后 ss-tproxy 使用全局模式，分流由 clash 的 IP 规则处理。请问要如何配置 ss-tproxy 呢？

clash不太了解，如果clash是ss/v2ray等传统代理软件的封装的话，那其实和设置ss/ssr/v2ray的步骤没有差别，具体看readme有详细说明，只不过把ss/ssr/v2ray替换为clash(包括运行的用户id、监听的端口、启动和停止的shell命令等）。然后其它要走代理的主机，把网关改为ss-tproxy主机的ip（dns不变，还是指向原先的无污染dns服务器）。

**Comment by m2acgi** [comment]
clash 和 ss 的区别是在于 clash 根据自己的规则配置文件进行了分流，所以我想跟您请教的是，是不是在 ss-tproxy 中设置了跑 clash 进程的用户 proxy_procuser，clash 自己的分流规则就不会受到 iptables 规则的影响？

另外，有个建议，可以把 dns 交给  overture 这种 (可以搭建无污染的 dns server), 分流交给 clash 这种 (对于普通用户来说规则更简单灵活), ss-tproxy 只做 iptables 规则，这样也更符合 linux 哲学 KISS（keep it simple, stupid），不知是否有可行性？感觉现在的 ss-tproxy 很强大，但是略为臃肿，不够灵活。

**Comment by zfl9** [comment]
> 感觉现在的 ss-tproxy 很强大，但是略为臃肿，不够灵活。

说到这个，我个人的想法是这样的：

ss-tproxy本身只是一个shell脚本，shell脚本其实就是一个粘合剂，就是用来组合各种linux命令/程序的(也就是这里提到的ss/ssr/v2ray/dnsmasq/chinadns-ng等等)。所以我并不觉得一个shell脚本需要符合所谓的KISS哲学，因为不适用。那些被shell脚本所用到的各个linux程序，我觉得才有必要遵循KISS原则，而chinadns-ng/ipt2socks/dns2tcp这些我自己写的小工具，我认为我是遵循了KISS原则的，都是很精简的小程序。

至于你说的ss-tproxy脚本很臃肿，这个其实我也没办法，因为用户的需求是无穷无尽的，五花八门的，有些人喜欢用这种组合，有些人喜欢用另外一些组合，为了尽可能满足各种需求（其实ss-tproxy远没有满足这么多需求，只是实现了比较常见的一些需求而已），脚本自然就会变得复杂和所谓的臃肿。

ss-tproxy脚本对代理软件(ss/ssr/v2ray等等)的要求其实很简单：
1. 不需要你去做分流操作，安安心心的通过你的私有代理协议去与你的代理服务器进行交互即可
2. 也不需要你去处理dns污染，因为这个也是由其他组件去完成了（目前的方案是dnsmasq+chinadns-ng）

至于你说的，dns交给overture，分流交给clash，自然也是一个好的方案（并没有说ss-tproxy自带的组合是唯一的方式）。但是我不太想集成进来，或许是没有足够的时间去做，或许是我已经习惯了当前的这种方案，我觉得性能还蛮凑合的。。。

**Comment by m2acgi** [comment]
非常感谢您的快速回复。您说得是对的，shell 脚本是粘合剂，我把 ss-tproxy 当作普通的 linux 程序了。你认为现在这种方式最优的，那么应该就是最优的。我研究下，看能不能实现我的需求，非常感谢！

**Comment by zfl9** [comment]
> 你认为现在这种方式最优的，那么应该就是最优的。

额，其实我并没有说当前这种组合方案是所谓最优方案。我也不认为这是“最优方案”，因为一种方案/技术不可能在任意情况下都是最优的。只是我个人比较习惯这样用而已，我不是很喜欢把个人的喜好强加给别人。如果你不想用目前的方案，当然是可以改的，ss-tproxy欢迎你们进行修改和扩展。。。
