### ISSUE TITLE
mount -o bind 修改resolv.conf造成该文件的硬链接数为0

### ISSUE THREAD

**Issue by tefiszx** [zfl9/ss-tproxy#194]
最近遇到了一个问题，发现Linux的steam客户端用proton5.13及以上的版本启动游戏，会发生bwrap can't mount oldroot/etc/resolv.conf newroot/etc/resolv.confxo错误。错误的原因是ss-tproxy脚本启动时，以mount -o bind的方式修改了dns设置，这导致/etc/resolv.conf的硬链接数变为0，如果能让resolv.conf的硬链接数恢复正常（正常为1）steam的这个错误就不会发生了。

**Comment by zfl9** [comment]
![image](https://user-images.githubusercontent.com/22726048/131780237-e8f0104e-59df-4382-8925-28327e1f99a5.png)

**Comment by tefiszx** [comment]
谢谢作者及时又高质量的回复。我想我真应该好好的阅读一下文档。
