### ISSUE TITLE
can tproxy run on a vm but not on a router? if it can't, what should I do?

### ISSUE THREAD

**Issue by jockerxlj** [zfl9/ss-tproxy#2]

**Comment by zfl9** [comment]
你的意思是 -> "ss-tproxy 是否可以在 虚拟机 上运行" 吗？如果是，我的回答是：当然可以，我本人就是这么做的！

**Comment by jockerxlj** [comment]
我现在是这样的情况，我在我其中一台VM上部署了ss-tproxy之后，在这台vm可以访问google了，但是我其他的vm通过设置export http_proxy https_proxy指向那台ss-tproxy vm仍无法访问成功google，我还做做什么额外的设置么？

**Comment by zfl9** [comment]
是在 VMware 上的 VM 吗

**Comment by zfl9** [comment]
`export http_proxy=xxx https_proxy=xxx`不适合 ss-tproxy。你应该将网关指向部署了 ss-tproxy 的 VM

**Comment by jockerxlj** [comment]
在openstack上的虚拟机，我之前使用的方案是ss-local + polipo(将socks协议转成http的程序)，然后其他虚拟机通过export http_proxy https_proxy进行指向就可以代理成功，但是这样有一个问题，就是如果我访问一些内网的ip比如 192.168.1.66 它也会走proxy，所以我就试了ss-tproxy。但是现在proxy可以访问google，但是其他vm访问不了了

**Comment by zfl9** [comment]
不过，如果你愿意，也可以在每台 VM 上部署 ss-tproxy

**Comment by jockerxlj** [comment]
那台做proxy的vm（假设ip:192.168.1.10/24）跟我其他vm是现在是在同一个子网的，他们默认路由都指向了集群的网关（假设192.168.1.1）,我现在要修改其他vm上的默认路由让他指向（192.168.1.10）么？修改默认网关可能会断网所以没有试过。

**Comment by zfl9** [comment]
了解了，我感觉可以在其他 VM 上利用 iptables 规则，TCP 数据包被 DNAT 至部署了 ss-tproxy 的VM的 ss-redir 上，UDP （DNS除外）做 iptables-TPROXY 至部署了 ss-tproxy 的 VM 的 ss-redir 上。最后将 DNS 指向部署了的 VM 的 53 端口（即 dnsforwarder）

**Comment by jockerxlj** [comment]
具体要怎么做呢？ 方便加个QQ么？ 156082052，有图片觉得好说一点。
