### ISSUE TITLE
请教一下clash上域名全部被解析成ip，导致分流规则失效的问题？

### ISSUE THREAD

**Issue by rebron1900** [zfl9/ss-tproxy#205]
我看了下clash的面板，上面几乎只显示ip，不会显示域名，（google，github这种大公司的域名能识别）。
这导致我订阅的分流规则里面的所有根据域名匹配的规则全部失效，不能正确分流，请问是怎么回事？

![image](https://user-images.githubusercontent.com/7929884/165123560-3b55fb89-dd28-459c-8090-de7475b370f2.png)

我在一些群里也问过，有人说是DNS的问题，但是padavan的dns设置选项太多了，不知道更改那部分的dns设置。
希望坛子里的大佬能解惑一下

![image](https://user-images.githubusercontent.com/7929884/165123573-d4281fa1-70fe-4403-8f3a-d79b16c29141.png)

![image](https://user-images.githubusercontent.com/7929884/165123585-8dc76c97-3b01-4e53-8b89-1fe5abde2c5c.png)

**Comment by rebron1900** [comment]
已解决，sstporxy的config文件里设置查询端口为8053即可。

**Comment by wmpluto** [comment]
> 已解决，sstporxy的config文件里设置查询端口为8053即可。
 
在sstproxy的配置里设置ext_ss_pdnsd_all为1，也就是把图里的使用代理服务查询全部DNS的选项勾选上。

**Comment by rebron1900** [comment]
@wmpluto 你的意思是你只勾选了查询全部DNS就可以了？我之前也试过，但是没用。改了ssproxy的监听端口才恢复正常

**Comment by wmpluto** [comment]
> @wmpluto 你的意思是你只勾选了查询全部DNS就可以了？我之前也试过，但是没用。改了ssproxy的监听端口才恢复正常

对的。我目前设置web界面，1勾选查询全部DNS，2取消国内域名DNS加速。让所有域名的DNS都走clash自带的，由clash进行规则分流。搞了很久，总归是能用了。

**Comment by yangn0** [comment]
请问下大佬们 ss_tproxy 和 clash结合使用的意义是什么？ clash本身不就有分流规则吗？#209
