### ISSUE TITLE
A little idea, use it with VPN

### ISSUE THREAD

**Issue by yecgaa-n** [zfl9/ss-tproxy#206]
Run a VPN (Wireguard or OpenVPN，not support the front agent) in Linux virtual machines, and then use TT-Proxy + IPT2SOCKS to send VPN traffic through the SOCKS5 agent of another virtual machine in the local area network.
(PS: From a certain level, VPN is more useful. With DANTED and other SOCKS5 positive proxy, VPN can be used like a SOCKS5 proxy. It means that VPN can be separated from machines and applications that need proxy))

Thanks for ZFL9's great script :)

**Comment by zfl9** [comment]
没懂你的意思
