### ISSUE TITLE
OpenWrt上是否考虑复用已有的Dnsmasq

### ISSUE THREAD

**Issue by fengqi** [zfl9/ss-tproxy#208]
我自己魔改了一下，能正常运行，我改动的地方有下面几个：

- restore_resolvconf 和  modify_resolvconf 可以跳过，内置的 dnsmasq 本身会处理 /etc/resolv.conf
- status 需要获取系统的 dnsmasq pid，而且需要动态获取，而不是读取 $status_dnsmasq_pid，因为luci下修改会导致重启
- start_dnsserver_chnroute 和 start_dnsserver_gfwlist 的启动一个新的dnsmasq实例，需要改为把 ipset 放到内置 dnsmasq 的conf-dir目录下（目前看来是 /tmp/dnsmasq.d），并重启内置的dnsmasq
- stop_dnsserver 里面的 kill -9 需要跳过 dnsmasq，因为内置的dnsmasq还用作dhcp等，需要保留
- 配置文件的dns server需要替换内置的dns，内置的配置在 /var/etc/dnsmasq.conf.cfg01411c 内，也可通过luci修改

不知道还有没有遗漏的地方

**Comment by zfl9** [comment]
感觉通用性较低（必须针对各种系统/发行版，做定制化修改），所以暂不考虑哈
