### ISSUE TITLE
请问下ss_tproxy和clash结合使用的意义是什么？

### ISSUE THREAD

**Issue by yangn0** [zfl9/ss-tproxy#209]
大佬们 请问下ss_tproxy和clash结合使用的意义是什么？
clash本身不是有分流规则吗？
像padavan固件 开启clash会强制开启ss_tproxy。那么 ss_tproxy配置的分流规则 和 clash内部规则不是冲突了吗？
还是说 会根据ss_tproxy规则去覆写clash规则？

**Comment by zfl9** [comment]
不清楚哦，这些固件上的sstproxy我并不知情
