### ISSUE TITLE
IPv6模式下，端口号与IPv6地址表达模糊，无法转发v6地址

### ISSUE THREAD

**Issue by jsyzdej** [zfl9/ss-tproxy#210]
具体表现在ss-tproxy主程序的1019、1023、1026与1030行

对于一般IPv4地址而已，使用$loopback_addr:$proxy_tcpport可以明确表明IP地址与端口号，如127.0.0.1:60080，但是对于IPv6而言，冒号(:)是ip地址的一部分，不能精确表达地址与端口关系，即::1:60080并不等价于[::1]:60080

![Snipaste_2022-08-28_00-29-19](https://user-images.githubusercontent.com/13121137/187039269-20e7572f-d54f-4bff-99a2-346395e756b8.png)

个人的修改方案：
添加了if判断是否开启了ipv6，若是，则将ip与端口关系改为[$loopback_addr]:$proxy_tcpport，若否则不变。

**Comment by zfl9** [comment]
感谢反馈，已修复(v4.6.3)，期待你的测试验证。

**Comment by jsyzdej** [comment]
感谢作者，该问题已解决。

现在遇到新问题，但是该问题理应不属于该issue，因此仅在此进行描述，当想到解决方案时reopen或者提交新issue。
程序正常运行后，在网关主机上测试时可以正常取得vps的ipv6地址，如图1所示。
![Snipaste_2022-08-28_15-07-27](https://user-images.githubusercontent.com/13121137/187062044-eed6acf3-c09d-486d-8758-31c4b6e33fa5.png)
而到其他设备时，ipv4能正常代理，而ipv6则不能，如图2所示
![photo_2022-08-28_15-04-38](https://user-images.githubusercontent.com/13121137/187061980-d86cfe73-4087-4a2a-92ba-86586ec998cb.jpg)

**以下内容仅为猜测**
参考了xray的[白话文教程](https://xtls.github.io/Xray-docs-next/document/level-2/iptables_gid.html#_4-%E8%AE%BE%E7%BD%AE-iptables-%E8%A7%84%E5%88%99)，其中提到采用`ip address | grep -w "inet6" | awk '{print $2}'`获得网关所在ipv6网段。相较于ipv4网段，不难发现在ipv6网段中有一行为公网地址，如图3所示。
![Snipaste_2022-08-28_15-12-31](https://user-images.githubusercontent.com/13121137/187062319-e071b8c1-7497-448f-bb40-585064350e1f.png)
但是按照白话文教程中的命令添加，依旧不能在其他主机上代理ipv6，或许该问题的正确解法与ipv6网段中公网地址无关。

**Comment by zfl9** [comment]
ss-tproxy主机上能正常代理，说明相关配置是没问题的。其它主机上之所以v6没被代理，我猜测应该是这些主机的v6默认网关没有指向ss-tproxy主机的v6本地地址（类似v4这样），可以使用 `ip -6 route` 看看v6的默认网关是什么。或者你可以tcpdump抓包看看流量发到哪个机器了。

**Comment by jsyzdej** [comment]
感谢作者的回复。
确实和您猜测的一样，其余主机的默认v6网关没有指向ss-tproxy主机。
