### ISSUE TITLE
配置有误

### ISSUE THREAD

**Issue by ansongd** [zfl9/ss-tproxy#22]
// as ss-redir
        {
            "port": 60080,
            "protocol": "dokodemo-door",
            "settings": {
                "network": "tcp,udp",
                "followRedirect": true,
                "domainOverride": ["quic"]
            }
        },
        // as ss-tunnel
        {
            "port": 60053,
            "protocol": "dokodemo-door",
            "settings": {
                "address": "8.8.8.8",
                "port": 53,
                "network": "udp",
                "followRedirect": false
            }
        },

这个配置settings中漏了一个参数："domainOverride": ["tls","http"],

**Comment by zfl9** [comment]
这个参数有什么作用？好像加不加都没影响。

**Comment by zfl9** [comment]
官方文档也没说明具体作用，先关了哈

**Comment by ansongd** [comment]
不加这一条只能连国外，如果加了一行国内国外都能连。
但是udp一直提示链接失败，不知道什么原因

**Comment by zfl9** [comment]
什么 mode？不应该吧，我没加这行正常使用，别人也是
