### ISSUE TITLE
chnlist转存到ignlist.ext后启动速度非常慢

### ISSUE THREAD

**Issue by dream-gavin** [zfl9/ss-tproxy#223]
你好
采用的是chnroute模式，把通过ss-tproxy update-chnlist更新后的gfwlist.txt内容转存到ignlist.ext里，再ss-tproxy update-gfwlist；
然后启动ss-tproxy，发现启动速度非常慢(不转存chnlist，启动速度瞬间完成)。
启动速度非常慢的原因是什么？如何解决？
VPS-2C2G的配置
谢谢

**Comment by zfl9** [comment]
为什么要 **通过ss-tproxy update-chnlist更新后的gfwlist.txt内容转存到ignlist.ext里**

这句话什么意思，我没看明白。

另外把 `ss-tproxy start -x` 输出日志发来下，我看下是哪里慢了。

**Comment by dream-gavin** [comment]
> ****
> 
> 这句话什么意思，我没看明白。
谢谢回复
chnlist是国内域名，配置到ignlist.ext里，是想通过域名加强下国内访问的定义，有时候访问淘宝登录账号的时候，会出现检测到ip在国外的情况，还有偶尔的国内域名也会出现通过代理访问的情况。

**Comment by dream-gavin** [comment]
ipset = /zzzzzz.me/privaddr'
++ echo 4872
++ dnsmasq --keep-in-foreground --conf-file=-
^C+ status_dnsmasq_pid=4872

到这里速度就慢下来了，CPU的负载也高起来了

**Comment by zfl9** [comment]
那是因为dnsmasq不支持过多数量的server记录。
所以这里卡了，cpu使用率高。

要解决你说的某些国内网站会走代理的bug，把chinadns-ng的gfwlist模式打开即可。
```bash
chinadns_fairmode='true'                 # 使用公平模式，具体看 chinadns-ng 的 README
chinadns_gfwlist_mode='true'             # gfwlist 模式，加载 gfwlist.txt/gfwlist.ext
```

**Comment by dream-gavin** [comment]
谢谢
测试下效果

**Comment by zfl9** [comment]
dnsmasq上不能配置过多的server记录，不然会很卡。

目前ss-tproxy上的chinadns-ng只会加载gfwlist.txt。

鉴于你这个情况，我会在这几天，给ss-tproxy上的chinadns-ng也启用chnlist，这样你这类dns问题应该就能杜绝了。

> 你之所以想将chnlist.txt的内容加至ignlist.ext，我猜测就是为了这个目的吧(chnlist.txt走国内dns，gfwlist.txt走国外dns)。所以我后面提供一个配置，让chinadns-ng来处理这个列表，而不是dnsmasq。

**Comment by zfl9** [comment]
> 谢谢 测试下效果

记得先清空dns缓存（客户端的，防止受dns缓存影响）

**Comment by dream-gavin** [comment]
> dnsmasq上不能配置过多的server记录，不然会很卡。
> 
> 目前ss-tproxy上的chinadns-ng只会加载gfwlist.txt。
> 
> 鉴于你这个情况，我会在这几天，给ss-tproxy上的chinadns-ng也启用chnlist，这样你这类dns问题应该就能杜绝了。
> 
> > 你之所以想将chnlist.txt的内容加至ignlist.ext，我猜测就是为了这个目的吧(chnlist.txt走国内dns，gfwlist.txt走国外dns)。所以我后面提供一个配置，让chinadns-ng来处理这个列表，而不是dnsmasq。
> 
> 这样 chinadns-ng 就是完整版了：gfwlist.txt + chnlist.txt + chnroute + chnroute6。
你之所以想将chnlist.txt的内容加至ignlist.ext，我猜测就是为了这个目的吧(chnlist.txt走国内dns，gfwlist.txt走国外dns)--是这个目的。
所以我后面提供一个配置，让chinadns-ng来处理这个列表，而不是dnsmasq --- 666
感觉使用刚更新的chinadns-ng后，访问网站速度快了点。

另外，刚更新的chinadns-ng的no-ipv6选项在ss-tproxy.conf里没有找到对应的配置选项
## chinadns
chinadns_bind_port='65353'               # chinadns-ng 服务器监听端口，通常不用改动
chinadns_timeout='5'                     # 等待上游 DNS 返回响应的超时时间，单位为秒
chinadns_repeat='1'                      # 向可信 DNS 发送几次 DNS 查询请求，默认为 1
chinadns_fairmode='true'                # 使用公平模式，具体看 chinadns-ng 的 README
chinadns_gfwlist_mode='true'            # gfwlist 模式，加载 gfwlist.txt/gfwlist.ext
chinadns_noip_as_chnip='false'           # 启用 chinadns-ng 的 `--noip-as-chnip` 选项
chinadns_verbose='false'                 # 记录详细日志，除非进行调试，否则不建议启用
chinadns_logfile='/var/log/chinadns.log' # 日志文件，如果不想保存日志可以改为 /dev/null
chinadns_privaddr4=()                    # IPv4 私有地址段，多个用空格隔开，具体见 README
chinadns_privaddr6=() 

前几天，突然遇到不能访问google的问题，进代理查看，给出了google的ipv6的地址，不知道什么原因。重启服务解决了。

**Comment by zfl9** [comment]
> 另外，刚更新的chinadns-ng的no-ipv6选项在ss-tproxy.conf里没有找到对应的配置选项

确实，忘了同步ss-tproxy这边了，过几天整一下。
