### ISSUE TITLE
在 gfwlist 里的域名不走代理（openai/chatgpt），应该是 http3/quic 问题

### ISSUE THREAD

**Issue by codecasex** [zfl9/ss-tproxy#224]
作者 您好
我是在 Padavan 固件里配合 v2Ray 使用 ss_tproxy 这个应用 模式是 gfwlist
之前用的都蛮好
最近无法访问 openai.com 和 openai.org 
以为是不在 gfwlist 里
尝试在 opt/app/ss_tproxy/gfwlist.ext 里加入上面两个域名 还是不行
后来发现 opt/app/ss_tproxy/rule/gfwlist.txt 其实已经有这两个域名了
但是都无法访问
确认梯子是没问题的
不知道哪里出问题了

**Comment by zfl9** [comment]
其它gfw域名(gfwlist.txt/gfwlist.ext中的)是否正常？

如果其它正常（比如google.com），那可能是客户机的dns缓存。

对于 windows：先关闭相关软件，然后命令行 `ipconfig /flushdns`，再试
对于手机，建议关闭相关软件，然后打开飞行模式，再关闭，再试。

**Comment by zfl9** [comment]
如果global模式可以访问google但不能访问openai，并且在排除了dns缓存的情况下，那我觉得不可思议。

**Comment by codecasex** [comment]
> 我 ssh 到国外 vps 上试了下:
> 
> ```
> curl -L http://chat.openai.com
> error code: 1020
> ```
> 
> ```
> curl -L http://openai.com
> OK
> ```
> 
> ```
> curl -L http://openai.org
> curl: (6) Could not resolve host: openai.org
> ```
> 
> **也许根本不是代理问题. 是人家本身就不提供服务给你的 ip**

谢谢您的建议
我的代理节点的 IP 是确认肯定提供服务的 已经通过其他软件但是同个节点 正常使用了

**Comment by codecasex** [comment]
> 如果global模式可以访问google但不能访问openai，并且在排除了dns缓存的情况下，那我觉得不可思议。

确实很奇怪
所以来向您请教
我这边再多试试
padavan 和 v2ray 的配置对 ss-tproxy 的正常运行会产生影响吗

**Comment by zfl9** [comment]
v2ray的配置可能会影响，所以当你使用ss-tproxy分流时，请让v2ray保持最简配置，不要让其参与分流。

**Comment by codecasex** [comment]
> v2ray的配置可能会影响，所以当你使用ss-tproxy分流时，请让v2ray保持最简配置，不要让其参与分流。

收到 感谢您的建议
我重置 V2RAY 配置再试试

**Comment by hack2012** [comment]
我有个类似的问题，就是我只要开了v2ray+ss-tproxy，我连接我司的一个VPN通道就老是超时，而且只有电信的节点会超时，其它的不会，但是当我重启ss-tproxy时就好了，但是仅能维持一段时间就又不行了，不知是何原因。

**Comment by zfl9** [comment]
> 我有个类似的问题，就是我只要开了v2ray+ss-tproxy，我连接我司的一个VPN通道就老是超时，而且只有电信的节点会超时，其它的不会，但是当我重启ss-tproxy时就好了，但是仅能维持一段时间就又不行了，不知是何原因。 后来我在ss-tproxy 用b绕过此ip也还是不行

没看明白，你说的问题。是v2ray的服务器节点访问不了超时还是什么超时？

**Comment by hack2012** [comment]
我说的不准，就是无法连接的意思，软件上显示是超时的，到是我只要重启一下ss_tproxy就立马可以了，大概过一天或者几个小时就又不行了。实际上节点都是好的，其他人都没问题。

**Comment by hack2012** [comment]
> 作者 您好
> 我是在 Padavan 固件里配合 v2Ray 使用 ss_tproxy 这个应用 模式是 gfwlist
> 之前用的都蛮好
> 最近无法访问 openai.com 和 openai.org
> 以为是不在 gfwlist 里
> 尝试在 opt/app/ss_tproxy/gfwlist.ext 里加入上面两个域名 还是不行
> 后来发现 opt/app/ss_tproxy/rule/gfwlist.txt 其实已经有这两个域名了
> 但是都无法访问
> 确认梯子是没问题的
> 不知道哪里出问题了

你这个问题可以试一下用safiri浏览器，chrome浏览器就是不行。

**Comment by zfl9** [comment]
> 我说的不准，就是无法连接的意思，软件上显示是超时的，到是我只要重启一下ss_tproxy就立马可以了，大概过一天或者几个小时就又不行了。实际上节点都是好的，其他人都没问题。

那可以试试单独重启v2ray，如果单独重启v2后正常，可能就是v2这边问题

**Comment by zfl9** [comment]
但最好还是看一下v2ray日志，以及dns相关日志，排查问题

**Comment by codecasex** [comment]
> > 一个很简单的判断方法：
> > 
> > * 如果google.com正常，但是openai.com不正常，并且排除了dns缓存问题，那就是和代理节点有关了。
> > * 如果google.com等gfw域名也不正常，并排除了dns缓存问题，那应该是ss-tproxy相关组件出问题了，比如代理不支持udp了，导致基于udp的remote_dns解析失败；或者其它bug。
> > * 也可临时修改为global模式，在确认清空dns缓存后，测试openai是否可访问，如果不行，切换节点再试。
> > 
> > > 修改gfwlist.ext需要重启生效，并且注意客户机dns缓存的影响。
> 
> > 谢谢您的回复 我这边的情况是这样的 在 gfwlist 模式下 google.com 可以访问 但是访问 chat.openai.com 的时候 页面提示我的访问地址为运营商分配给我的中国内地的地址所以阻挡访问 然后我使用 Windows 上的 v2ray 客户端 配置同一个代理节点 把 openai.com 和 openai.org 加入需要走代理的域名列表里 此时访问 chat.openai.com 就可以正常使用 曾经在 global 和 chnroute 模式 也可以正常使用 chat.openai.com 不过 刚刚我试了现在也不行了 所以我觉得代理节点应该是正常的 可能是 ss-tproxy 的问题
> 
> 你路由开启ipv6支持了吗？这个被阻止的中国运营商地址是ipv6吗？
> 
> 我也遇到类似问题。不同的是我确定我的路由是开启ipv6的。我的lan上的pc被分配了运营商国内的公网ipv6地址，pc（win10）访问网站解析dns时是先解析v6的。即使我ss-tproxy使用全局模式，也会被chat.openai.com识别为国内的这个v6地址而被阻止访问。另外我的v2ray节点只支持ipv4，ss-tproxy.conf文件里也屏蔽了所有ipv6相关的部分。我疑惑的是同样这个情况，我访问谷歌或者netflix时，本地pc都是解出ipv6地址的，但是都会按预期走我的这个ipv4 的v2ray节点的，完全正常访问。只有chat.openai.com访问会出现问题，会被识别出我真实的ipv6国内地址，应该是没有走ss-tproxy里的v2ray节点吧。 但我在路由上关闭ipv6后。在纯ipv4环境下，一切都是正常。
> 
> 还有我注意到chat.openai.com或者ai.com都是套在cloudflare下的，所以@codecasex要是在gfwlist模式下使用是否还要考虑把cloudflare的ip段加入到gfwlist.ext里？我这里是加了的。在纯ipv4环境下，用ss-tproxy+v2ray访问chatgpt是没有问题的。 @zfl9 @codecasex

感谢您的帮助
我这边 IPv6 是关闭的
cf 的 ip 段倒是没加入 gfwlist.ext 打算试试这个方法
请教一下 cf 的 ip 段如何获取？

**Comment by bluehj777** [comment]
> > > 一个很简单的判断方法：
> > > 
> > > * 如果google.com正常，但是openai.com不正常，并且排除了dns缓存问题，那就是和代理节点有关了。
> > > * 如果google.com等gfw域名也不正常，并排除了dns缓存问题，那应该是ss-tproxy相关组件出问题了，比如代理不支持udp了，导致基于udp的remote_dns解析失败；或者其它bug。
> > > * 也可临时修改为global模式，在确认清空dns缓存后，测试openai是否可访问，如果不行，切换节点再试。
> > > 
> > > > 修改gfwlist.ext需要重启生效，并且注意客户机dns缓存的影响。
> > 
> > 
> > > 谢谢您的回复 我这边的情况是这样的 在 gfwlist 模式下 google.com 可以访问 但是访问 chat.openai.com 的时候 页面提示我的访问地址为运营商分配给我的中国内地的地址所以阻挡访问 然后我使用 Windows 上的 v2ray 客户端 配置同一个代理节点 把 openai.com 和 openai.org 加入需要走代理的域名列表里 此时访问 chat.openai.com 就可以正常使用 曾经在 global 和 chnroute 模式 也可以正常使用 chat.openai.com 不过 刚刚我试了现在也不行了 所以我觉得代理节点应该是正常的 可能是 ss-tproxy 的问题
> > 
> > 
> > 你路由开启ipv6支持了吗？这个被阻止的中国运营商地址是ipv6吗？
> > 我也遇到类似问题。不同的是我确定我的路由是开启ipv6的。我的lan上的pc被分配了运营商国内的公网ipv6地址，pc（win10）访问网站解析dns时是先解析v6的。即使我ss-tproxy使用全局模式，也会被chat.openai.com识别为国内的这个v6地址而被阻止访问。另外我的v2ray节点只支持ipv4，ss-tproxy.conf文件里也屏蔽了所有ipv6相关的部分。我疑惑的是同样这个情况，我访问谷歌或者netflix时，本地pc都是解出ipv6地址的，但是都会按预期走我的这个ipv4 的v2ray节点的，完全正常访问。只有chat.openai.com访问会出现问题，会被识别出我真实的ipv6国内地址，应该是没有走ss-tproxy里的v2ray节点吧。 但我在路由上关闭ipv6后。在纯ipv4环境下，一切都是正常。
> > 还有我注意到chat.openai.com或者ai.com都是套在cloudflare下的，所以@codecasex要是在gfwlist模式下使用是否还要考虑把cloudflare的ip段加入到gfwlist.ext里？我这里是加了的。在纯ipv4环境下，用ss-tproxy+v2ray访问chatgpt是没有问题的。 @zfl9 @codecasex
> 
> 感谢您的帮助 我这边 IPv6 是关闭的 cf 的 ip 段倒是没加入 gfwlist.ext 打算试试这个方法 请教一下 cf 的 ip 段如何获取？

https://www.cloudflare.com/ips/
官方就有

**Comment by codecasex** [comment]
> > > > 一个很简单的判断方法：
> > > > 
> > > > * 如果google.com正常，但是openai.com不正常，并且排除了dns缓存问题，那就是和代理节点有关了。
> > > > * 如果google.com等gfw域名也不正常，并排除了dns缓存问题，那应该是ss-tproxy相关组件出问题了，比如代理不支持udp了，导致基于udp的remote_dns解析失败；或者其它bug。
> > > > * 也可临时修改为global模式，在确认清空dns缓存后，测试openai是否可访问，如果不行，切换节点再试。
> > > > 
> > > > > 修改gfwlist.ext需要重启生效，并且注意客户机dns缓存的影响。
> > > 
> > > 
> > > > 谢谢您的回复 我这边的情况是这样的 在 gfwlist 模式下 google.com 可以访问 但是访问 chat.openai.com 的时候 页面提示我的访问地址为运营商分配给我的中国内地的地址所以阻挡访问 然后我使用 Windows 上的 v2ray 客户端 配置同一个代理节点 把 openai.com 和 openai.org 加入需要走代理的域名列表里 此时访问 chat.openai.com 就可以正常使用 曾经在 global 和 chnroute 模式 也可以正常使用 chat.openai.com 不过 刚刚我试了现在也不行了 所以我觉得代理节点应该是正常的 可能是 ss-tproxy 的问题
> > > 
> > > 
> > > 你路由开启ipv6支持了吗？这个被阻止的中国运营商地址是ipv6吗？
> > > 我也遇到类似问题。不同的是我确定我的路由是开启ipv6的。我的lan上的pc被分配了运营商国内的公网ipv6地址，pc（win10）访问网站解析dns时是先解析v6的。即使我ss-tproxy使用全局模式，也会被chat.openai.com识别为国内的这个v6地址而被阻止访问。另外我的v2ray节点只支持ipv4，ss-tproxy.conf文件里也屏蔽了所有ipv6相关的部分。我疑惑的是同样这个情况，我访问谷歌或者netflix时，本地pc都是解出ipv6地址的，但是都会按预期走我的这个ipv4 的v2ray节点的，完全正常访问。只有chat.openai.com访问会出现问题，会被识别出我真实的ipv6国内地址，应该是没有走ss-tproxy里的v2ray节点吧。 但我在路由上关闭ipv6后。在纯ipv4环境下，一切都是正常。
> > > 还有我注意到chat.openai.com或者ai.com都是套在cloudflare下的，所以@codecasex要是在gfwlist模式下使用是否还要考虑把cloudflare的ip段加入到gfwlist.ext里？我这里是加了的。在纯ipv4环境下，用ss-tproxy+v2ray访问chatgpt是没有问题的。 @zfl9 @codecasex
> > 
> > 
> > 感谢您的帮助 我这边 IPv6 是关闭的 cf 的 ip 段倒是没加入 gfwlist.ext 打算试试这个方法 请教一下 cf 的 ip 段如何获取？
> 
> https://www.cloudflare.com/ips/ 官方就有

不好意思 刚收到推送 再次感谢您的帮助

**Comment by zfl9** [comment]
#237

**Comment by everschen** [comment]
非常蹊跷的一个问题，SSR plus全局模式是好的（说明代理没问题），GFW模式不行，两个模式google和youtube都是好的。
所以怀疑有一些内容在GFW模式走了国内IP，但是找不出来。

**Comment by everschen** [comment]
发现了一个solution和大家分享：把ssr plus+强制走代理的内容清空，重启动软路由，我上面说的情况的问题解决，可以访问chatgpt了。
