### ISSUE TITLE
启动失败：错误码127

### ISSUE THREAD

**Issue by LingHime** [zfl9/ss-tproxy#225]
ss-tproxy start
/usr/local/bin/ss-tproxy: line 651: cmd: command not found
[ERROR] failed to start local proxy process, exit-code: 127

大佬请问这个是怎么回事呢

**Comment by zfl9** [comment]
`/etc/ss-tproxy/ss-tproxy.conf`的`proxy_startcmd`配的不对（默认就是cmd，假命令）
