### ISSUE TITLE
流程过于繁琐…望出 docker 或者优化流程。

### ISSUE THREAD

**Issue by YeungKC** [zfl9/ss-tproxy#23]
昨天折腾了五六个小时…除了网速原因还有就是流程太繁琐了…
ss 不是编译安装还跑不起来…希望优化流程或者出 docker 版本吧，一个新机子，装个 docker 然后直 run 就能当一个网关，我想作者也是希望使用越来越方便的

**Comment by zfl9** [comment]
建议先收下了，但是最近没啥时间弄这个，所以，你们想将就着。

**Comment by YeungKC** [comment]
(´･_･`) 嗯嗯，很感谢作者的这个分享…最后我到今天也没跑起来 emmm…T_T

**Comment by zfl9** [comment]
不会吧，你是哪个步骤编译不了？

**Comment by YeungKC** [comment]
其实主要是我的问题，我一开始直接按官方安装 ss，然后发现启动失败，错误信息为 

Unrecognized option: "--reuse-port "
Unrecognized option: "--fast-open "
Unrecognized option: (null)

因为我已经重置了树莓派…更详细的 log 无法重现了

对了流程繁琐除了很多编译命令以外，其实很重要一点就是网速，拉取这些依赖的速度简直太痛苦了…

**Comment by zfl9** [comment]
获取依赖的确很痛苦，基本上网速都是几 kb/s，这个我深有体会。

**Comment by YeungKC** [comment]
对的…所以如果有个 docker…就大家都不用那么痛苦了………………
我其实也试过做这一块的东西，最后各种网络问题处理不了就放弃了…，网络这一块并不是很熟悉…

btw
我今晚弄弄尝试换国内镜像
