### ISSUE TITLE
新版关于本机代理进程的proxy_procgroup和dns_procgroup问题

### ISSUE THREAD

**Issue by bluehj777** [zfl9/ss-tproxy#235]
新版是不是需要手动设置一下所使用的代理程序的dns_procgroup组权限？
ss-tproxy.conf里已经设置了

```
proxy_procgroup='proxy_ss_tproxy' 
........
dns_procgroup='proxy_ss_tproxy_dns' 
```

然后重启ss-tproxy 
发现chinadns-ng 这个执行文件可以被自动附上 拥有者 root [0]，组 proxy_ss_tproxy_dns [1001]  权限：2755，即使手动改一下
下次启动还是可以改回来的。

对于其他要使用的代理程序，还是保留原来的权限，比如v2ray xray ss-redir等

这里需要事先手动设置下吗？

注意到这个问题的缘由是：

开始并未注意这个问题做过特殊处理，只是在ss-tproxy.conf里设置了

```
proxy_procgroup='proxy_ss_tproxy' 
........
dns_procgroup='proxy_ss_tproxy_dns' 
```

然后开始测试，原来4.6x里的xray，v2ray的客户端程序JSON配置文件，直接挪过来都可以直接使用，唯有一台v2ray的服务器死活连不上，但可以确保这台服务器肯定是在线没问题的，因为旁边的4.6x的一台服务器正在使用这个v2ray节点的配置没问题。然后开始排查原因，好久才发现，我代理程序的权限还都是用原先的root [0]。最后手动给了V2RAY执行文件的组 proxy_ss_tproxy_dns [1001]  权限：2755，这台服务器才正常。诡异的是，我不明白即使我不给proxy_ss_tproxy_dns [1001]  权限的时候，都用 root[0]，也不是所有v2ray配置的服务器节点都不好用，有的很多都没问题一样使用。

**Comment by zfl9** [comment]
楼上正解。README 也有写。set_proxy_group /path/to/v2ray 即可。

**Comment by bluehj777** [comment]
> #233

谢谢，只是疑惑为啥最初我并没有设置set_proxy_group /path/to/xray,v2ray,ss-redir 也能用呢？不应该都用不了吗

**Comment by zfl9** [comment]
不可能吧，建议检查下 Gid （`/proc/进程PID/status` 文件）。没有放行肯定会出现死循环的，除非，你的v2服务器的ip正好位于白名单，没有走代理。所以没有死循环。。

**Comment by bluehj777** [comment]
> 不可能吧，建议检查下 Gid （`/proc/进程PID/status` 文件）。没有放行肯定会出现死循环的，除非，你的v2服务器的ip正好位于白名单，没有走代理。所以没有死循环。。

 我大概想起来应该是这样引起这个问题的，这台机器我可能用过setcap处理过  #180    当时没调成功，就换回以前的方式继续用了

```
proxy_svraddr4=( ) # 
proxy_svrport='' 
```
所以开始不设置 set_proxy_group 也能用起来
