### ISSUE TITLE
chnroute/gwflist模式时google play无法下载app的解决

### ISSUE THREAD

**Issue by bluehj777** [zfl9/ss-tproxy#239]
近期才发现，chnroute/gwflist模式时，android手机上google play无法下载更新app。表现为进入play浏览和搜索都没问题
但是下载或更新时一直是0%
经过研究是发现 play在下载时需要解析services.googleapis.cn这个域名，然后返回给 xxxx-xxxx.xn--ngstr-lra8j.com具体区域的服务器开始下载。而services.googleapis.cn给解析到上海的IP了，所以xxxx-xxxx.xn--ngstr-lra8j.com也对应去往上海的地址。所以无法下载

可以把他们添加到/ss-tproxy/gfwlist.ext里即可解决了。
@googleapis.cn
@xn--ngstr-lra8j.com

但我的印象中以前即使googleapis.cn被解析到大陆IP，play也是下载更新都没问题的，这个问题好像是近期才出现的

**Comment by zfl9** [comment]
有测试过只加入 `@googleapis.cn` 吗？是否有效？为避免dns缓存影响，关闭google play，开关飞行，重连wifi。

@bluehj777

**Comment by bluehj777** [comment]
> 有测试过只加入 `@googleapis.cn` 吗？是否有效？为避免dns缓存影响，关闭google play，开关飞行，重连wifi。
> 
> @bluehj777

晚上回家测一下看看

**Comment by bluehj777** [comment]
> 有测试过只加入 `@googleapis.cn` 吗？是否有效？为避免dns缓存影响，关闭google play，开关飞行，重连wifi。
> 
> @bluehj777

简单搭了个环境，测试只加@googleapis.cn也可以。

**Comment by zfl9** [comment]
好的，感谢，后面默认给加到 gfwlist.ext 去

**Comment by zfl9** [comment]
https://github.com/gfwlist/gfwlist/issues/464

看了下，是 gfwlist 上游的问题，没有包含这两个域名。

**Comment by zfl9** [comment]
xn--ngstr-lra8j.com 这个域名我看了，gfwlist.txt 已经存在，所以不加没问题。

**Comment by zfl9** [comment]
v4.7.4 版本已添加 googleapis.cn 域名。
