### ISSUE TITLE
内网端口映射到公网失败

### ISSUE THREAD

**Issue by 5high** [zfl9/ss-tproxy#24]
ip rule add fwmark 0x01/0x01 table 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -N V2RAY
iptables -t mangle -I V2RAY -d 192.168.1.0/24 -j RETURN
iptables -t mangle -I V2RAY -d 127.0.0.1/32 -j RETURN
iptables -t mangle -A V2RAY -p udp -j TPROXY --on-port 12345 --tproxy-mark 0x01/0x01
iptables -t mangle -A V2RAY -p tcp -j TPROXY --on-port 12345 --tproxy-mark 0x01/0x01
iptables -t mangle -A PREROUTING -j V2RAY

按照上面例子可以实现V2RAY TCP和UDP全部走tproxy，但是端口映射会失败。

我感觉好像所有流量去了TPROXY之后都送给了dokodemo-door才会这样，有没有什么办法不送某个端口流量给dokodemo-door.

我v2ray地址上的某个端口映射到了公网，用上面的例子无法成功映射。

求方法让私网映射端口工作正常。

**Comment by zfl9** [comment]
试试把你本机（你应该是在网关上设置的规则吧）的 IP 添加到 V2RAY 自定义链中，放行它，即：
```bash
iptables -t mangle -I V2RAY -d $public_ipaddr -j RETURN
```

**Comment by 5high** [comment]
测试了一下，还是不行，我主路由器192.168.1.1 （有公网IP） 映射 4000 端口到 192.168.1.10 （V2RAY 服务器）

**Comment by zfl9** [comment]
那我也不知道，iptables 规则单靠说是很难调试得当的，必须自己会调试才行。

**Comment by 5high** [comment]
ip route add local 0.0.0.0/0 dev lo table 100

是否可以通过这个形式排除掉某个目标地址

**Comment by zfl9** [comment]
请参考 ip rule 的语法，`ip rule help`

**Comment by zfl9** [comment]
忘了一点，将最后一条规则改为：
```bash
iptables -t mangle -A PREROUTING -i $内网网卡 ! -s 192.168.1.10/32 -j V2RAY
```

**Comment by 5high** [comment]
ip rule add fwmark 0x01/0x01 table 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -N V2RAY
iptables -t mangle -I V2RAY -d 192.168.1.0/24 -j RETURN
iptables -t mangle -I V2RAY -d 127.0.0.1/32 -j RETURN
iptables -t mangle -A V2RAY -p udp -j TPROXY --on-port 12345 -s !192.168.1.10 --tproxy-mark 0x01/0x01
iptables -t mangle -A V2RAY -p tcp -j TPROXY --on-port 12345 -s !192.168.1.10 --tproxy-mark 0x01/0x01
iptables -t mangle -A PREROUTING -j V2RAY

改成上面这个样子端口映射就恢复正常了
