### ISSUE TITLE
特定网站第一次访问无法打开,接下来都无法打开,除非重起路ss-tproxy

### ISSUE THREAD

**Issue by sophauer** [zfl9/ss-tproxy#245]
硬件平台:树梅4 Linux 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

DNS方案chinadns-ng rev [2023.06.01](https://github.com/zfl9/chinadns-ng/releases/tag/2023.06.01)
mode :chnroute tcp only
 
问题描述:
访问特定网站,如https://www.15haoku.com/ (国内站)
第一次网络不通时,无法访问(这当然是正常的),当网络通了,再度访问,依然无法访问
FLUSHＤＮＳ也没用
但在树梅上 curl  https://www.15haoku.com/
显示能正常访问

**Comment by zfl9** [comment]
客户机 dns 有缓存吧，刷新下。

**Comment by zfl9** [comment]
你这个网站 `走代理的` 还是 `走直连的` ？

**Comment by zfl9** [comment]
没有相关日志，我也没法帮你分析。

**Comment by zfl9** [comment]
客户机浏览器 在无法访问时，显示的什么错误？要根据具体错误来分析原因。

**Comment by zfl9** [comment]
另外，你说的 **网络不通**，具体是什么不通？完全断网了？还是如何？

**Comment by zfl9** [comment]
根据你的描述，我猜测还是 解析出的ip 有问题。

对比下 树莓派上的解析结果（可以使用 dig、curl -v）、客户机上的解析结果（多测几次，因为可能有多个 ip）

如果两者的解析结果不一致，建议先检查下客户机的 dns 配置，或者缓存（如 windows，则 ipconfig /flushdns）
