### ISSUE TITLE
请教如何配置xray reality

### ISSUE THREAD

**Issue by sophauer** [zfl9/ss-tproxy#250]
如标题,
我把v2ray替换成xray,怎么配置都失败.,
检查过端口,也不行,.
确认线路跟配置是正常的.可以在其他机器上正常使用

求大神在wiki里增加xray配置范本

**Comment by zfl9** [comment]
按理来说xray和v2ray的配置差不多，你是不是少了 sudo ss-tproxy set-proxy-group xray 这一步？

**Comment by zfl9** [comment]
我待会搞个 xray 环境，readme 增加 xray 示例。

**Comment by zfl9** [comment]
xray 配置和 v2ray 一样，我本地测试了。

你需要注意的是 systemctl edit xray（看 代理软件配置 一节，有详细说明）

**Comment by zfl9** [comment]
不是，但 ss-tproxy 并不关心 代理软件 的 传出协议 是什么，只关心 本地进程的 传入协议（redirect/tproxy）。
