### ISSUE TITLE
ss-redir默认单线程运行, 可使用--reuse-port启用多进程负载均衡，发挥多核性能

### ISSUE THREAD

**Issue by sophauer** [zfl9/ss-tproxy#252]
同办公室用户约50人,如果运行在ss-redir.会产生一个问题
ss-redir只用了一个CPU核心,导致网络卡死,
所以是不是有可能设置一次运行多个ss-redir,通过port reuse解决这个问题?

**Comment by zfl9** [comment]
当然可以: https://github.com/shadowsocks/shadowsocks-libev?tab=readme-ov-file#usage

给 ss-redir 的命令行参数加上 --reuse-port，然后启动多个 ss-redir 进程就好了（每个进程的启动参数一致）。

**Comment by zfl9** [comment]
有多少个cpu核心，就启动多少个ss-redir进程（每个都设置--reuse-port），充分发挥多核性能。

**Comment by zfl9** [comment]
启动 ss-tproxy 之后启动 ss-redir 进程也可以，也可以在 ss-tproxy.conf 的 proxy_startcmd 中启动，比如：

```bash

proxy_startcmd='start_ss'
proxy_stopcmd='stop_ss'

start_ss() {
    # 设置 setgid 权限位 (只需执行一次)
    set_proxy_group ss-redir

    # 启动$nproc个ss-redir进程（cpu核心数个）
    for i in $(seq 1 $(nproc)); do
        (ss-redir -c /etc/ss.json -u --reuse-port </dev/null &>>/var/log/ss-redir.log &)
    done
}

stop_ss() {
    kill -9 $(pidof ss-redir) &>/dev/null
}
```

**Comment by zfl9** [comment]
ok，后面整理到 wiki。
