### ISSUE TITLE
无法启动proxy/tcp和proxy/udp

### ISSUE THREAD

**Issue by forgiveboo** [zfl9/ss-tproxy#253]
![1](https://github.com/zfl9/ss-tproxy/assets/31067422/400a6188-bb28-4df9-919f-e099266be23c)
请问这是为什么啊 配置文件就是你文档里clash的基本配置文件
系统是Arch 桌面环境是dwm

**Comment by zfl9** [comment]
ss-tproxy.conf和clash配置发出来看下

**Comment by zfl9** [comment]
ss-tproxy start -x
执行此命令，然后把输出发一下

**Comment by forgiveboo** [comment]
[text.txt](https://github.com/zfl9/ss-tproxy/files/13198520/text.txt)
这个里面就是全部输出内容

**Comment by forgiveboo** [comment]
不好意思 我没看到你说把配置文件发出来 我电脑现在不在身边 明天发

**Comment by zfl9** [comment]
ss-tproxy.conf 都没配置完整呀

```
# 这两个配置我看你都是空的，按照 readme (clash那里）配置下就好了。
proxy_startcmd=''
proxy_stopcmd=''
```

**Comment by forgiveboo** [comment]
> ss-tproxy.conf 都没配置完整呀
> 
> ```
> # 这两个配置我看你都是空的，按照 readme (clash那里）配置下就好了。
> proxy_startcmd=''
> proxy_stopcmd=''
> ```

我之前就是按照那样配置的 不行 然后又删了的 还是不行 我再试试

**Comment by forgiveboo** [comment]
![1](https://github.com/zfl9/ss-tproxy/assets/31067422/e70e8d50-b061-42fd-ac7d-d907be721e71)
然后这是我执行readme文件里检查gid的结果

**Comment by zfl9** [comment]
这是因为你启动了两个clash进程，一个pid=527，一个pid=384

**Comment by zfl9** [comment]
`for pid in $(pidof clash); do grep Gid /proc/$pid/status; done`
执行这个看下

**Comment by zfl9** [comment]
另外，clash 配置文件发一下。是否配置了 tproxy-port: 60080 这行？

**Comment by forgiveboo** [comment]
[config.txt](https://github.com/zfl9/ss-tproxy/files/13201816/config.txt)
这是clash配置文件
[ss-tproxy.txt](https://github.com/zfl9/ss-tproxy/files/13201821/ss-tproxy.txt)
这是ss-tproxt配置文件

**Comment by forgiveboo** [comment]
> `for pid in $(pidof clash); do grep Gid /proc/$pid/status; done` 执行这个看下（待会我修改下 readme 的关于 Gid 检查命令，兼容多个 pid 的情况）

![1](https://github.com/zfl9/ss-tproxy/assets/31067422/1986fef1-4ad7-4cf8-b03e-b90ae1b2b8ff)
这是执行结果

**Comment by zfl9** [comment]
现在 ss-tproxy status 什么情况，还是 proxy/tcp proxy/udp stopping ?

如果我没看错，你的 clash 配置文件有问题。

**Comment by zfl9** [comment]
最后一行，`- MATCH PROXY`，把 PROXY 改为你的代理节点（组）的name，比如`自动选择`、`故障转移`。你这里显然没有一个名为 `PROXY` 节点（组），你仔细看 readme 中的 clash.yaml 例子，里面之所以是 MATCH PROXY，是因为我给 节点组 命名为了 PROXY。

**Comment by zfl9** [comment]
![image](https://github.com/zfl9/ss-tproxy/assets/22726048/98ebb909-795d-4ea8-8601-43eb86b689f0)

**Comment by zfl9** [comment]
https://dreamacro.github.io/clash/configuration/outbound.html

**Comment by zfl9** [comment]
https://dreamacro.github.io/clash/configuration/rules.html#policy

**Comment by forgiveboo** [comment]
> 现在 ss-tproxy status 什么情况，还是 proxy/tcp proxy/udp stopping ?
> 
> 如果我没看错，你的 clash 配置文件有问题。

好的 我改一下

**Comment by forgiveboo** [comment]
![1](https://github.com/zfl9/ss-tproxy/assets/31067422/c510e7b1-30a1-458b-a31b-b0fd9a9605ef)
现在又变成这样了 这样算是成功了吗

**Comment by zfl9** [comment]
检查 clash 是否监听了 60080 端口，检查 clash 的日志，看是否有报错，有没有显示监听了 tprxoy 60080 端口。

**Comment by zfl9** [comment]
`ss -ltunpe | grep clash`

**Comment by zfl9** [comment]
你改完重启了 clash 没有，clash 配置检查了没

**Comment by zfl9** [comment]
如果是先启动 ss-tproxy，那么此时 status 显示 proxy/tcp、proxy/udp 是 stopping 是正常的（因为你 clash 进程还没启动呢），此时你只需要再执行 systemctl start clash，把 clash 启动，然后再次执行 sudo ss-tproxy status 查看状态，如果配置无误，对应状态应该是 running 的。如果还是 stopped，那么请检查 clash 配置、日志。

**Comment by forgiveboo** [comment]
clash没有监听60080端口好像
![1](https://github.com/zfl9/ss-tproxy/assets/31067422/bf13afb2-cfa5-49e8-811a-89298bd595db)
这是为啥啊 我的配置文件出错了吗

**Comment by zfl9** [comment]
执行这个命令，看下服务文件

systemctl cat clash

**Comment by zfl9** [comment]
你这个报错应该就是service文件没写好，没有权限执行tproxy操作

**Comment by forgiveboo** [comment]
![1](https://github.com/zfl9/ss-tproxy/assets/31067422/65fc316f-3edb-4cff-a789-19c084f03e2f)
是这样的

**Comment by forgiveboo** [comment]
> > 另外，如果service文件不是官方的，我觉得不必强行上systemd管理，直接按照readme命令行启动就完事。配置startcmd和stopcmd。
> 
> 我在之前就是用的readme里的配置搞的 也按照文档里的方法配置好了startcmd和stopcmd 还重启了电脑 依然是这样 我以为是我的节点不支持udp 我还把配置改成了只用tcp模式 还是不行 clash配置我也把你说的那里改成了我配置文件里的策略组 真的不知道哪里除了问题 难道是节点的问题？而且我在重启后start了ss-tproxy之后 还运行了`grep proxy /etc/group`和`grep Gid /proc/$(pidof clash)/status` 输出结果一致

另外 你不是说如果先 ss-tproxy start 的话还要再 systemctl start clash 吗？我也试过了  依然不行 而且我的理解是 ss-tproxy start 之后系统会自动启动clash服务 再 systemctl start clash 的话就会导致执行 grep Gid /proc/$(pidof clash)/status 的时候会出现两个pid 关键是我试过 在 ss-tproxy start  之后可以科学上网 只是没有实现透明代理。

**Comment by zfl9** [comment]
不用说之前，你就现在改一下startcmd和stopcmd，按照readme配一下start/stop_clash函数，clash配置不要动。

然后 systemctl stop clash，ss-tproxy restart即可

**Comment by zfl9** [comment]
我要睡觉了。明天再说

**Comment by zfl9** [comment]
> 真的不知道哪里除了问题

问题就是你上面发的那个clash报错呀。。。

应该就是启动方式不对，clash没有权限执行tproxy操作(估摸着)

**Comment by forgiveboo** [comment]
> > 真的不知道哪里除了问题
> 
> 问题就是你上面发的那个clash报错呀。。。
> 
> 应该就是启动方式不对，clash没有权限执行tproxy操作(估摸着)

大佬 搞定了 谢谢你！！！你那句没有权限执行提醒我了 我把配置文件复制一份到了/etc/clash里就好了 另外我想请教一下 如果我把～/.config/clash里的config.yaml直接软链接一下到/etc/clash里是不是和复制一份一样啊 还是说要先更改家目录下的clash配置文件的权限再软链接 真的感谢！！！

**Comment by zfl9** [comment]
> 如果我把～/.config/clash里的config.yaml直接软链接一下到/etc/clash里是不是和复制一份一样啊 还是说要先更改家目录下的clash配置文件的权限再软链接

不确定，自己试下不就知道了。

为什么不修改 clash.service 文件，将 -d /etc/clash 改为 -d /home/xxx/.config/clash 呢

**Comment by forgiveboo** [comment]
> -d /home/xxx/.config/clash

好的 谢谢大佬 那我是不是也可以改start_clash函数 改成-d /home/xxx/.config/clash啊

**Comment by forgiveboo** [comment]
> > -d /home/xxx/.config/clash
> 
> 好的 谢谢大佬 那我是不是也可以改start_clash函数 改成-d /home/xxx/.config/clash啊

我试过了 可以的 太好了 谢谢你
