### ISSUE TITLE
设置透明代理后，Docker容器中无法联网

### ISSUE THREAD

**Issue by Xmagicer** [zfl9/ss-tproxy#26]
设置监听的内网网段是(192.168.0.0/16 172.17.0.0/16)
现状：
（1）主机可以使用代理
（2）Docker容器中无法使用代理，甚至无法联网

**Comment by zfl9** [comment]
请提供具体信息，比如：docker 容器是否可以 ping 114，是否可以解析 DNS，还是说 TCP 有问题

**Comment by vexetron** [comment]
run命令加 `--net host`，build加`--network host`

**Comment by linkdesu** [comment]
> run命令加 `--net host`，build加`--network host`

折腾了几天，最后你这个才是最简单的正确答案啊，感谢

**Comment by langzigyq** [comment]
我只能说2026还有这个问题，只不过我用的是nikki。算了反正是自家用，又没几个容器要跑，都用host网络吧
