### ISSUE TITLE
Question.请问如何配置DNS

### ISSUE THREAD

**Issue by sophauer** [zfl9/ss-tproxy#262]
在ss-tproxy.conf里
dns_direct='223.5.5.5#53'             # 直连DNS(v4环境使用)，必须指定端口，可使用本地/内网服务器
dns_remote='8.8.8.8#53'               # 远程DNS(v4环境使用)，必须指定端口，可使用本地/内网服务器

这里似乎只能用一个DNS服务器,请问如何配置两个服务器,担心一个死了,网就停了

**Comment by zfl9** [comment]
目前只能填一个。

因为一些dns组件限制了dns上游的数量。

如chinadns-ng，一组上游目前只能设置2个，但是这两个其中一个是给ipv4用的，一个是给ipv6用的，所以实际上在v4only或v6only下，只有一个位置可用。

不过目前正在开发 chinadns-ng 1.0/2.0，预计可以解决这个问题。
到时候可能会替换 dnsmasq + chinadns-ng + dns2tcp/dnsproxy 套娃。

**Comment by zfl9** [comment]
但也不必过于担心（公共）dns不可用的问题，基本上没遇到过。

因为对于很多操作系统，如 linux，在 /etc/resolv.conf 中配置的多个 nameserver 实际上是按照顺序请求的，也就是总是先使用第一个 nameserver，只有第一个 nameserver 查询超时后（一般是5秒超时）才会使用第二个 nameserver。

**Comment by zfl9** [comment]
见最新版本。
