### ISSUE TITLE
是否有并发线程限制?

### ISSUE THREAD

**Issue by sophauer** [zfl9/ss-tproxy#264]
如标题,
有个旁路由供给办公室用享,最近人多了,
发现并发线程数上去了,网页会产生连接重置,并发线程下去后(人少了),就一切正常

请问哪个组件可以配置并发线程?

**Comment by zfl9** [comment]
ss-tproxy 这边本身只是设置代理环境、代理规则，真正的运行过程，特别是处理能力，取决于代理自身。

**Comment by zfl9** [comment]
那就要看看 ss-tproxy 主机自身的内核参数配置、特别是要结合日志分析，要看是什么原因导致链接重置，只看现象没帮助。

看你描述，你的代理是跑在其他主机上（native）上吗？也就是说，ss-tproxy 主机和你的 native 主机不是同一个？

这种情况下，你是在 ss-tproxy 主机上使用了 ipt2socks 对接 native 主机上的 socks5 端口么？

**Comment by zfl9** [comment]
那就检查 ipt2socks 日志，估计是 nofile 达到 limit 了。可以使用 ipt2socks 的 `--nofile-limit 100000` 提高下（需要 root 权限）

```
$ ipt2socks --help
 -j, --thread-nums <num>            number of the worker threads, default: 1
 -n, --nofile-limit <num>           set nofile limit, may need root privilege
```

另外建议指定 `-j` 选项，启用多线程（SO_REUSEPORT）。

**Comment by zfl9** [comment]
可以使用 `prlimit -p ipt2socks进程ID` 来检查 NOFILE 行（SOFT 列），是否设置生效。

通常来说，如果设置失败，ipt2socks 会打印一条错误信息的，如果没有错误（比如你这个），就是成功了。
