### ISSUE TITLE
教程修改建议,关于naive,.

### ISSUE THREAD

**Issue by sophauer** [zfl9/ss-tproxy#266]
Naive支持redir模式,
Client端配置
{
  "listen": "redir://127.0.0.1;60080",
  "proxy": "https://用户:密码@naive服务器域名"
}

配置 ss-tproxy.conf
tproxy='false' # ipt2socks 默认使用纯 tproxy 模式
tcponly='true' # naive 不支持 udp 代理
proxy_startcmd='start_naive'
proxy_stopcmd='stop_naive'
start_naive() {
    # 设置 setgid 权限位 (只需执行一次)
    set_proxy_group naive
    #set_proxy_group ipt2socks  // 不需要启动
    (naive /etc/naive.json </dev/null &>>/var/log/naive.log &)
    # (ipt2socks </dev/null &>>/var/log/ipt2socks.log &) //不需要启动
}

stop_naive() {
    kill -9 $(pidof naive) $(pidof ipt2socks) &>/dev/null
}

这样配置的好处是降低性能损耗,

**Comment by zfl9** [comment]
我没有naive环境，按照推理，使用naive自己的redir模式时，tproxy='true'应该要改为'false'吧？

**Comment by zfl9** [comment]
好的，后面更新下readme。

**Comment by zfl9** [comment]
已更新。
