### ISSUE TITLE
我制作了一个docker镜像 tcp可以代理，但是udp出现了些问题 

### ISSUE THREAD

**Issue by YahuiWong** [zfl9/ss-tproxy#27]
使用的ssr 代理
ss-tproxy.conf 配置如下

![image](https://user-images.githubusercontent.com/32868945/48332808-21b52980-e690-11e8-87d5-f53e2cf9a019.png)

启动之后 

tcp网络的可以
![image](https://user-images.githubusercontent.com/32868945/48332838-3d203480-e690-11e8-819f-36c5e0b6a9ab.png)

但是运行 udp透明代理的时候 
![image](https://user-images.githubusercontent.com/32868945/48332747-e9155000-e68f-11e8-83cc-71fc50e93e62.png)

 2018-11-12 15:28:05 ERROR: [udp] remote_recv_bind: Address already in use
 2018-11-12 15:28:05 ERROR: [udp] remote_recv_bind: Address already in use
 2018-11-12 15:28:05 ERROR: [udp] remote_recv_bind: Address already in use

这个是啥很么问题呢? 望解答，谢谢。

**Comment by YahuiWong** [comment]
@zfl9 还请指教斧正，谢谢

**Comment by zfl9** [comment]
obfs 应该是拼写错误，`origin`
你测试 UDP 透明代理时，测试的是 53 端口吗？还是？
地址被占用这个错误有点眼熟，我曾经遇到过。

**Comment by YahuiWong** [comment]
现在ssr-local.json的配置我改过来了 好像没啥影响 还是有这个错误

**Comment by YahuiWong** [comment]
@zfl9 已经是最新版本的了 

这个是我所有端口占用情况

[root@da2397dc6a8a ~]# netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:60080           0.0.0.0:*               LISTEN      2323/ssr-redir      
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      2336/dnsmasq        
tcp6       0      0 :::53                   :::*                    LISTEN      2336/dnsmasq        
[root@da2397dc6a8a ~]# netstat -nupl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
udp        0      0 0.0.0.0:38409           0.0.0.0:*                           2323/ssr-redir      
udp        0      0 0.0.0.0:53              0.0.0.0:*                           2336/dnsmasq        
udp        0      0 0.0.0.0:55354           0.0.0.0:*                           2323/ssr-redir      
udp        0      0 0.0.0.0:55387           0.0.0.0:*                           2323/ssr-redir      
udp        0      0 0.0.0.0:32870           0.0.0.0:*                           2323/ssr-redir      
udp        0      0 0.0.0.0:60080           0.0.0.0:*                           2323/ssr-redir      
udp        0      0 0.0.0.0:50911           0.0.0.0:*                           2323/ssr-redir      
udp        0      0 0.0.0.0:57678           0.0.0.0:*                           2323/ssr-redir      
udp        0      0 0.0.0.0:34661           0.0.0.0:*                           2323/ssr-redir      
udp        0      0 0.0.0.0:39823           0.0.0.0:*                           2323/ssr-redir      
udp        0      0 0.0.0.0:59306           0.0.0.0:*                           2323/ssr-redir      
udp        0      0 0.0.0.0:42442           0.0.0.0:*                           2323/ssr-redir      
udp        0      0 0.0.0.0:53244           0.0.0.0:*                           2323/ssr-redir      
udp6       0      0 :::53                   :::*                                2336/dnsmasq

**Comment by zfl9** [comment]
估计是 dnsmasq 占用了 0.0.0.0:53 端口的原因，可是我之前测试的时候，测试环境与你完全一样，却没有这个地址被占用问题，好奇怪。

**Comment by YahuiWong** [comment]
> 估计是 dnsmasq 占用了 0.0.0.0:53 端口的原因，可是我之前测试的时候，测试环境与你完全一样，却没有这个地址被占用问题，好奇怪。

你的udp测试方式是什么 可以告诉我下吗？我使用相同的方式试下

**Comment by zfl9** [comment]
`dig @208.67.222.222 -p443 www.google.com`

**Comment by YahuiWong** [comment]
> `dig @208.67.222.222 -p443 www.google.com`
> `dig @8.8.8.8 -p53 www.google.com`

```SH
[root@da2397dc6a8a ~]# dig @208.67.222.222 -p443 www.google.com

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7_5.1 <<>> @208.67.222.222 -p443 www.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31490
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.com.                        IN      A

;; ANSWER SECTION:
www.google.com.         300     IN      A       216.58.217.196

;; Query time: 247 msec
;; SERVER: 208.67.222.222#443(208.67.222.222)
;; WHEN: Mon Nov 12 18:58:56 CST 2018
;; MSG SIZE  rcvd: 59

[root@da2397dc6a8a ~]# dig @8.8.8.8 -p53 www.google.com

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7_5.1 <<>> @8.8.8.8 -p53 www.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63660
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.google.com.                        IN      A

;; ANSWER SECTION:
www.google.com.         97      IN      A       216.58.216.36

;; Query time: 275 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Nov 12 18:59:03 CST 2018
;; MSG SIZE  rcvd: 59
```
这个是我的返回结果

**Comment by zfl9** [comment]
ssr-redir.log 日志呢？显示什么？正常还是？

**Comment by YahuiWong** [comment]
> ssr-redir.log 日志呢？显示什么？正常还是？

```SH
 2018-11-12 19:05:23 INFO: obfs plain
 2018-11-12 19:05:23 INFO: obfs_param 
 2018-11-12 19:05:23 INFO: initializing ciphers... rc4-md5
 2018-11-12 19:05:23 INFO: tcp port reuse enabled
 2018-11-12 19:05:23 INFO: UDP relay enabled
 2018-11-12 19:05:23 INFO: udp port reuse enabled
 2018-11-12 19:05:23 INFO: listening at 0.0.0.0:60080
 2018-11-12 19:05:23 INFO: running from root user
 2018-11-12 19:05:30 INFO: [udp] redir to 208.67.222.222:443 from 172.17.0.2:57190
 2018-11-12 19:05:30 INFO: [udp] cache miss: 208.67.222.222:443 <-> 172.17.0.2:57190
 2018-11-12 19:05:31 INFO: [udp] recv 208.67.222.222:443 via 45.62.124.190:6789
 2018-11-12 19:05:49 INFO: [udp] redir to 8.8.8.8:53 from 172.17.0.2:35498
 2018-11-12 19:05:49 INFO: [udp] cache miss: 8.8.8.8:53 <-> 172.17.0.2:35498
 2018-11-12 19:05:49 INFO: [udp] recv 8.8.8.8:53 via 45.62.124.190:6789
```

**Comment by zfl9** [comment]
你这不是没问题吗，完全正常啊。

**Comment by YahuiWong** [comment]
可以当我使用另外一个udp通讯的程序的时候 

![image](https://user-images.githubusercontent.com/32868945/48343840-6b147180-e6ae-11e8-9ea6-f966aeab5fd4.png)

费解……

**Comment by zfl9** [comment]
那我就不清楚了，这个问题应该问 ssr-libev 或者 Google。ss-tproxy 规则是没问题的。
