### ISSUE TITLE
怎么排查dns路由错误？

### ISSUE THREAD

**Issue by wnpllrzodiac** [zfl9/ss-tproxy#273]
proxy 软件不支持dns的代理。但是从proxy的日志里面看到53的dns请求错误的打到proxy软件上去了。
怎么排查问题？
以前一直正常工作的，今天突然不通了。baidu能正常访问，goo不行

```
May 30 16:17:47 aml naive[1645]: [0530/161747.441617:INFO:naive_connection.cc(273)] Connection 4 to 8.8.8.8:53
May 30 16:17:47 aml naive[1645]: [0530/161747.447885:INFO:naive_connection.cc(273)] Connection 5 to 8.8.8.8:53
```

```
ss-tproxy status
mode:           gfwlist
proxy/tcp:      [running]
dnsmasq:        [running]
dns2tcp4:       [running]
```

**Comment by zfl9** [comment]
naive日志没问题，访问remote dns就是要走naive代理才能避免污染。

dig google.com 显示什么？超时？

换个 dns，比如 1.1.1.1，看看如何。

另外，使用如下方法测试是否是代理问题：

```bash
sg proxy_dns 'dig @1.1.1.1 +tcp google.com'
```

如果超时，那么说明 tcp 代理有问题，也就是后端的 naive 不通，检查代理的日志。

**Comment by wnpllrzodiac** [comment]
我的情况是同一个网络环境，一台linux机器有问题，一台正常。比较了下ss-tproxy的配置，也是一模一样的。

**Comment by wnpllrzodiac** [comment]
dig google.com

; <<>> DiG 9.11.5-P4-5-Debian <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29999
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             600     IN      A       93.46.8.90

;; Query time: 4 msec
;; SERVER: 240e:58:c000:1600:180:168:255:118#53(240e:58:c000:1600:180:168:255:118)
;; WHEN: Thu May 30 17:14:20 CST 2024
;; MSG SIZE  rcvd: 44

**Comment by wnpllrzodiac** [comment]
sg proxy_dns 'dig @1.1.1.1 +tcp google.com'
;; communications error to 1.1.1.1#53: connection reset

**Comment by zfl9** [comment]
如果超时/出错，那么说明 tcp 代理有问题，也就是后端的 naive 不通，检查代理的日志。

**Comment by zfl9** [comment]
240e:58:c000:1600:180:168:255:118#53

怎么是这个dns？未开启ipv6代理时，不会设置 iptables 规则（将发往“任意dns”的流量重定向至 dns_mainport，即dnsmasq），dns 可能会受到污染。

修改下 /etc/resolv.conf，删除 ipv6 地址的 dns。

**Comment by wnpllrzodiac** [comment]
有问题的机器的dns设置 /etc/resolv.conf
# Generated by NetworkManager
nameserver 192.168.1.1
nameserver 240e:58:c000:1600:180:168:255:118
nameserver 240e:58:c000:1000:116:228:111:18

正常的机器的dns设置 （有两个网卡，一个连了和问题机器一样的光猫，一个连了无线路由器的wifi）
# Generated by NetworkManager
nameserver 192.168.1.1
nameserver 240e:58:c000:1600:180:168:255:118
nameserver 240e:58:c000:1000:116:228:111:18
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver 192.168.5.1
nameserver fe80::5%wlan0

**Comment by wnpllrzodiac** [comment]
curl -L youtube.com -x socks5://127.0.0.1:9966
curl: (56) Recv failure: Connection reset by peer

**Comment by zfl9** [comment]
> curl -L youtube.com -x socks5://127.0.0.1:9966 curl: (56) Recv failure: Connection reset by peer

你这个就说明是代理本身有问题，检查 naive 配置、日志。自己对比下。

**Comment by zfl9** [comment]
> curl -L youtube.com -x socks5://127.0.0.1:9966 curl: (56) Recv failure: Connection reset by peer
> 
> 我的代理的问题？不明白的是，curl的dns解析是谁做的？是不是curl解析到的ip已经是污染的了

curl -x socks5:// 时，dns解析由curl完成。
curl -x socks5h:// 时，dns解析由socks5服务器完成。

**Comment by wnpllrzodiac** [comment]
奇怪的问题。。。

**Comment by zfl9** [comment]
在没有开启 ipv6 透明代理的情况下，请确保 resolv.conf 中没有 ipv6 地址的 nameserver。

最简单有效的方式：
- 启动时，将 resolv.conf 修改为 nameserver 127.0.0.1，停止时，还原为之前的 resolv.conf。
- 可以在 ss-tproxy.conf 的 post_start 函数中执行此操作，在 post_stop 函数中还原 resolv.conf。

原因：未开启 ipv6 透明代理，但 resolv.conf 有 ipv6 地址的 nameserver，则：
- ipv4='true'，会设置 iptables 规则（将 ipv4 路径上的 本机dns请求 重定向至 dnsmasq）
- ipv6='false'，不会设置 ip6tables 规则（将 ipv6 路径上的 本机dns请求 重定向至 dnsmasq）
- 若本机进程链接的是 glibc，可能正常情况下无法察觉此问题（或者说没问题），因为 glibc 始终尝试第一个 nameserver，如果第一个恰好是 ipv4 地址，那么会被上述 iptables 规则命中，重定向至 dnsmasq，不会有污染。
- 若本机进程链接的是 musl，则极有可能受到污染，因为 musl 会针对所有 nameserver 并发进行 dns 请求，由于 musl 的策略是采纳最先返回的结果，而收到污染的dns响应（ipv6路径）通常会先于其他server返回。

**Comment by zfl9** [comment]
> curl -L youtube.com -x socks5://127.0.0.1:9966 curl: (56) Recv failure: Connection reset by peer
> 
> 我的代理的问题？不明白的是，curl的dns解析是谁做的？是不是curl解析到的ip已经是污染的了

把 socks5:// 改为 socks5h://，如果 curl 仍然失败，说明代理有问题。

**Comment by zfl9** [comment]
> Connection 28 closed: ERR_PROXY_CONNECTION_FAILED 代理报这个有点奇怪啊。代理应该直接出去啊。怎么代理还有PROXY

它意思应该是 proxy server 连接失败吧。。。看看附近的其他日志？

**Comment by zfl9** [comment]
问题不在 dns，在于“代理”链路不通。dns 出错是因为 dns 解析请求要走代理，但是代理不同，导致 dns 出错。

**Comment by wnpllrzodiac** [comment]
curl -I https://MY_PROXY_SERVER.com:6243
HTTP/2 200
accept-ranges: bytes
content-type: text/html; charset=utf-8
etag: "d1ciskapkflnh0"
last-modified: Sat, 18 May 2024 05:27:26 GMT
server: Caddy

没问题啊

**Comment by wnpllrzodiac** [comment]
要么就是这台设备的6243的请求访问被过滤掉了，其他设备没事。

**Comment by zfl9** [comment]
dns 是一个应用层协议，来到 dnsmasq 之后进行分流：

- gfwlist域名，走dns2tcp，然后走naive代理出去（tcp），在代理这里，这就是一个常规 tcp 代理请求，他不关心这是什么应用层协议。
- 其他域名，走direct dns，因此不会走代理。

**Comment by wnpllrzodiac** [comment]
感觉要拿一下代理server那里的请求日志。看看dns请求过来没有

**Comment by zfl9** [comment]
> /etc/resolv.conf 改成 127.0.0.1 ping google.com ping: google.com: Name or service not known
> 
> 是代理的dns请求发不出去，所以dns解析也失败了？dnsmasq是用的代理出去的吧？

突然意识到，不能改为 127.0.0.1，最妥当的方式就是删除 resolv.conf 中的 ipv6 nameserver，留下 ipv4 的。

**Comment by wnpllrzodiac** [comment]
> > /etc/resolv.conf 改成 127.0.0.1 ping google.com ping: google.com: Name or service not known
> > 是代理的dns请求发不出去，所以dns解析也失败了？dnsmasq是用的代理出去的吧？
> 
> 突然意识到，不能改为 127.0.0.1，最妥当的方式就是删除 resolv.conf 中的 ipv6 nameserver，留下 ipv4 的。
> 
> 因为 resolv.conf 会被所有程序读取，当然包括 naive。设置为 127.0.0.1 可能会导致死循环：
> 
>     * 因为 naive server 的域名可能会被分流到 remote dns，然后走tcp代理出去，来到naive。。

对，我也觉得。还有个问题。
/etc/resolv.conf是什么时候有效，什么时候无效的？
如果dnsmasq 设置了全局dns为 127.0.0.1:53， 然后通过dns2tcp转发到代理。那/etc/resolv.conf 不就没用了？还是只有代理软件解析代理服务器ip的时候才会用到？naive的服务器地址必须是域名，不然就没法上ssl了。

**Comment by wnpllrzodiac** [comment]
感觉是我的光猫被加了规则，给禁止了。

问题的机器
netstat -ant|grep 16243
tcp        0   1821 192.168.1.5:35434       1.2.3.4:16243    FIN_WAIT1  
tcp        0   1725 192.168.1.5:35440       1.2.3.4:16243    FIN_WAIT1  

正常的机器
netstat -ant|grep 16243
tcp        0      0 192.168.1.16:4926       1.2.3.4:16243    ESTABLISHED

**Comment by zfl9** [comment]
基本上，程序都是使用 getaddrinfo C 库接口来解析域名，getaddrinfo（gai）会读取 /etc/resolv.conf。因此可以说 /etc/resolv.conf 对所有使用了 getaddrinfo C接口的程序都有效；什么情况下“无效”，那就是程序自己处理了 dns 解析，比如 dnsmasq、chinadns-ng 这种 dns 工具。

ss-tproxy 针对以下 3 类进程做了不同的 iptables 重定向策略：

1. proxy、proxy_dns 这两个组的进程（如ipt2socks、naive、dnsmasq、chinadns-ng、dns2tcp），发起的 dns 请求（目标端口为 53 的 tcp/udp 流量），**不会被重定向**。
2. 其他进程（比如 curl），发起的 dns 请求，会被 iptables 规则**重定向**到 127.0.0.1:dns_mainport，也就是 dnsmasq（或者 v4.8+ 的 chinadns-ng），进行分流，国内域名走direct dns（如223.5.5.5），要代理的域名走remote dns（如8.8.8.8），ss-tproxy 会设置iptables规则，访问remote dns会走代理出去，防止污染。

这里的“dns重定向”，才是魔法发生的地方（但是要注意，ipv6=false时，/etc/resolv.conf不能有ipv6地址，否则会失效，有漏网之鱼，具体我已经在前面做了详细解释）。

**Comment by wnpllrzodiac** [comment]
> 1. 如ipt2socks、naive、dnsmasq、chinadns-ng、dns2tcp

你的意思是上述列出的bin都需要是 proxy、proxy_dns group的属性？这个以前没有注意过

**Comment by zfl9** [comment]
是的，因为这是对进程进行“分类”的一个最简单、可移植的方法。

**Comment by wnpllrzodiac** [comment]
我发现我正常的机器上的nai也不是proxy group的，也能正常工作

-rwxr-xr-x 1 root root 8257504 Nov 20  2023 /opt/naive/naive*

ps aux|grep naive
nobody   2854330  0.0  0.1 33587628 7208 ?       Ssl  May30   0:20 /opt/naive/naive /opt/naive/config.json

User=nobody
ExecStart=/opt/naive/naive /opt/naive/config.json

**Comment by wnpllrzodiac** [comment]
换了个代理工具(配置相同的server)，就正常了。还是多备几个工具，有备无患。
