### ISSUE TITLE
Question:如何只重启代理?

### ISSUE THREAD

**Issue by sophauer** [zfl9/ss-tproxy#274]
需求:
因为众所周知的原因,宽带会劣化连接,过段时间后,产生无数据进出(Connection drop).过几分钟之后会自动恢复.
经验上,只需要重启一下代理软件,就好了

解决方案:所以,我写了这么一个脚本.每隔一分钟检测是否能连接Google,如果不能,则重启SS_TPROXY

#!/bin/bash
url="https://www.google.com"
log_file="/var/log/check_google.log"
current_time=$(date '+%Y-%m-%d %H:%M:%S')
if ! curl -s --head --request GET $url | grep "Connection established" > /dev/null; then
echo "$current_time: Unable to access $url. Restarting ss-tproxy.service..." >> $log_file
    systemctl restart ss-tproxy.service
    if [ $? -eq 0 ]; then
        echo "$current_time: Successfully restarted ss-tproxy.service." >> $log_file
    else
        echo "$current_time: Failed to restart ss-tproxy.service." >> $log_file
    fi
fi

但是这样的话也产生另一个问题
就是整个网络会感觉瞬间断开.体验很差.
请问如何只启动代理软件?

谢谢

**Comment by zfl9** [comment]
你把 start_xx、stop_xx 的命令抽出来，放到一个 shell 脚本，就可以了。你把事情想复杂了。

> 唯一值得注意的是，set_proxy_group 替换为 ss-tproxy set-proxy-group。

**Comment by zfl9** [comment]
或者，可以考虑增加一个指令 `ss-tproxy restart-proxy`，该指令本质上也是：先执行 proxy_stopcmd，然后执行 proxy_startcmd，完成代理进程的重启。这样用户也不必单独写个脚本处理这个问题，这种需求感觉还是挺常见的。

**Comment by wnpllrzodiac** [comment]
各种甲方的需求层出不穷，啊哈哈哈哈

**Comment by xtccc** [comment]
我是这么解决的，启动两个代理(hy) 1086 1087
使用nginx tcp代理功能，代理这两个代理到1080
然后ss–tproxy 使用1080代理

有人想要，我就补一个配置
另外nginx(njet) 支持api访问代理信息，
我写了个程序，重启代理软件(hy)
