### ISSUE TITLE
有兴趣做singbox吗？

### ISSUE THREAD

**Issue by wtfllix** [zfl9/ss-tproxy#275]
刚刚用这套脚本成功实现了，之前是拿tpclash做的，老感觉配置有问题。
有兴趣用singbox实现吗，singbox也可以做dns分流，只是配置需要手搓。
感谢！

**Comment by zfl9** [comment]
dns分流我这边只专注于chinadns-ng，对于其他方案，可以选择用自定义dns方案接入。wiki有一个页面举了详细的例子。

代理接入singbox应该没啥问题，参照readme里面的 代理软件配置，依葫芦画瓢即可。
