### ISSUE TITLE
如何设置指定域名的DNS转发规则？

### ISSUE THREAD

**Issue by KoalaJas** [zfl9/ss-tproxy#277]
需求背景：环境中存在企业私有域名，由windows dns服务器负责解析。
在更新ss-tproxy v4.8.1前，我是在dnsmasq里写转发规则的。
在更新v4.8.1后，只用chinadns-ng的情况下，如何让指定域名转发到某个上游DNS服务器去？
我看了下chinadns-ng的readme，请大佬帮我看看方法是否正确：
1、ss-tproxy.conf中增加额外的配置文件
chinadns_config_files='forward.conf'   ##这个扩展名有要求吗？
2、forward.conf内使用group配置自定义上游
```
group crop
group-dnl crop.txt
group-upstream 10.1.1.2
```
3、crop.txt里的域名格式参考”域名列表“的说明
```
a.com
b.com
```

是不是做完以上配置就可以了？如果没问题的话，crop.txt的内容是动态加载吗？修改后即时生效还是需要restart-dns才能生效？

**Comment by zfl9** [comment]
1、ss-tproxy.conf中增加额外的配置文件
chinadns_config_files='forward.conf' ##这个扩展名有要求吗？

扩展名没要求，一般为 `*.conf`。

---

是的，按照你给出的 forward.conf 就可以了。

crop.txt 不是动态加载的，chinadns-ng 只在启动时加载，如果有修改，执行 ss-tproxy restart-dns 生效。

**Comment by zfl9** [comment]
如果有疑问，可以打开 chinadns_verbose 开关，然后手动解析（如使用 dig）下相关域名（crop.txt中的），观察 /var/log/chinadns.log 输出。

**Comment by KoalaJas** [comment]
感谢指导
