### ISSUE TITLE
xray开启了任意门以及socks5

### ISSUE THREAD

**Issue by Angel0726** [zfl9/ss-tproxy#284]
我有软件想走socks5端口，那么这个端口会走再走一次ss-tproxy吗。

**Comment by zfl9** [comment]
不会，本机通信、局域网通信会自动放行（即：直连）。

**Comment by Angel0726** [comment]
那如果nps走的本机socks，这一部分没做代理。
socks通往外网的服务器，这一步会被ss-tproxy代理吗？

**Comment by zfl9** [comment]
不会，代理进程(proxy组)传出的流量自动放行

**Comment by Angel0726** [comment]
> 不会，代理进程(proxy组)传出的流量自动放行

谢谢
