### ISSUE TITLE
ChinaDNS-ng protocol not supported

### ISSUE THREAD

**Issue by asaarashi** [zfl9/ss-tproxy#289]
Hi , thank you for the great work. I try running ss-tproxy. While the other two components work well as shown by "ss-tproxy status", for chinadns-ng it shows "stopped". Checking the logs, the error is "Protocol not supported". 

Any ideas?

**Comment by zfl9** [comment]
执行 `chinadns-ng -V` 查看版本，以及 chinadns-ng 的相关完整 log 贴一下？

**Comment by asaarashi** [comment]
![image](https://github.com/user-attachments/assets/9a4be4e5-7618-4642-a56e-e52cc0c98588)
The logs with verbose=true and the chinadns-ng version are as above. Thanks.

**Comment by zfl9** [comment]
尝试 aarch64 generic+v8a 版本，看是否正常。
如果还不行，可能你的内核缺少某些模块。

**Comment by asaarashi** [comment]
It can't run with aarch64 generic+v8a but can with i386-linux-musl@i686.

**Comment by zfl9** [comment]
如果你的 CPU 是 x86_64 的，请选择 [chinadns-ng+wolfssl@x86_64-linux-musl@x86_64@fast+lto](https://github.com/zfl9/chinadns-ng/releases/download/2024.10.14/chinadns-ng+wolfssl@x86_64-linux-musl@x86_64@fast+lto)

**Comment by zfl9** [comment]
我猜测你安装了 qemu，否则你肯定无法直接运行 arm/aarch64 架构的 ELF 文件。
