### ISSUE TITLE
咨询一下一个小问题

### ISSUE THREAD

**Issue by JunShine** [zfl9/ss-tproxy#3]
首先，看了你的文章和脚本学习到很多，很感谢！
然后有一个小疑惑：我还是不太理解dnsforwarder在整个作用，搜索了一下，dnsforwarder是"将下游的 UDP 协议的 DNS 查询转换成 TCP 协议的 DNS 查询后发送到上游服务器"的作用。但是文中看起来，dnsforwarder好像只是一个DNS 缓存和加速的用途，这是不是可以用Dnsmasq来取代？用dnsforwarder把DNS查询转成TCP，再从本机的chinadns转出去，会不会多了一步？

**Comment by zfl9** [comment]
确实，dnsforwarder 在这里就是用来做 DNS 缓存，加速用的。你完全可以使用 pdnsd、dnsmasq、甚至不使用都可以。

**Comment by JunShine** [comment]
谢谢一个哈~
