### ISSUE TITLE
xt_TPROXY 模块问题

### ISSUE THREAD

**Issue by sunmd01** [zfl9/ss-tproxy#30]
我系统是ubuntu 18.01

运行命令 ```find /lib/modules/$(uname -r) -type f -name '*.ko*' | grep 'xt_TPROXY'```
显示的是 ```/lib/modules/4.15.0-42-generic/kernel/net/netfilter/xt_TPROXY.ko```
一键脚本就会报错
手动部署正常

**Comment by zfl9** [comment]
报什么错？

**Comment by sunmd01** [comment]
module not found

**Comment by zfl9** [comment]
可能是 TPROXY 模块的检测命令有问题，你试试编辑 ss-tproxy 脚本，将第  15 行注释掉，看是否正常：
```bash
# modprobe xt_TPROXY &>/dev/null || { echo "[ERR] Require kmodule not found: 'xt_TPROXY'" 1>&2; exit 1; }
```

**Comment by sunmd01** [comment]
我注释掉了，运行一次，也报错误，具体报什么我没有记录下来。

抽空我再试一次吧。

**Comment by zfl9** [comment]
OK，下次报错请记录对应的错误信息。如果能找出是那条命令出错就最好了。

**Comment by sunmd01** [comment]
我把那行注释掉后，可以启动了。
新问题来了，dnsmasq 报不能53 端口占用错误
我看了一下53端口进程占用情况，应该是系统进程，杀了之后会重启
这该怎么办

**Comment by zfl9** [comment]
这个进程应该是可以关的，什么系统，是 systemctl 管理的吧？

**Comment by sunmd01** [comment]
我看了一下是 720/systemd-resolve 这该怎么办？

**Comment by sunmd01** [comment]
系统是ubuntu18.04

**Comment by zfl9** [comment]
```
sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved
```

**Comment by sunmd01** [comment]
谢谢，已经不会报错了
我看到有两个mode pxy/tcp pxy/udp 没有启动
下面是我配置文件
```
## mode
  #mode='global'
  #mode='gfwlist'
  mode='chnroute'
  
   ## proxy
  proxy_tproxy='false'   # 纯TPROXY方式
   proxy_server='103.*.*.*'   # 服务器的地址
   proxy_tcport='60080'   # TCP 监听端口
  proxy_udport='60080'   # UDP 监听端口
 proxy_runcmd='nohup ss-redir -c /etc/shadwosocks-libev/config.json -uv </dev/null &>>/var/log/ss-redir.log &'  # 启动的命令行
  proxy_kilcmd='kill -9 $(pidof ssr-redir)'  # 停止的命令行
 
  ## dnsmasq
  dnsmasq_cache_size='10240'              # DNS 缓存条目
  dnsmasq_cache_time='3600'               # DNS 缓存时间
  dnsmasq_log_enable='false'              # 是否记录日志
  dnsmasq_log_file='/var/log/dnsmasq.log' # 日志文件路径
 
  ## chinadns
  chinadns_mutation='true'                 # DNS 压缩指针
  chinadns_verbose='false'                 # 记录详细日志
  chinadns_logfile='/var/log/chinadns.log' # 日志文件路径
 
  ## dns
  dns_modify='false'           # 直接修改 resolv.conf
  dns_remote='8.8.8.8:53'      # 国外 DNS，必须指定端口
  dns_direct='114.114.114.114' # 国内 DNS，不能指定端口
 
  ## ipts
  ipts_rt_tab='100'              # iproute2 路由表名或 ID
  ipts_rt_mark='0x2333'          # iproute2 策略路由的标记
  ipts_non_snat='false'          # 不设置 SNAT iptables 规则
  ipts_intranet=(192.168.0.0/16) # 内网网段，多个请用空格隔开
 
  ## file
  file_gfwlist_txt='/etc/ss-tproxy/gfwlist.txt'   # gfwlist 黑名单文件 (默认规则)
  file_gfwlist_ext='/etc/ss-tproxy/gfwlist.ext'   # gfwlist 黑名单文件 (扩展规则)
  file_chnroute_txt='/etc/ss-tproxy/chnroute.txt' # chnroute 地址段文件 (chinadns)
  file_chnroute_set='/etc/ss-tproxy/chnroute.set' # chnroute 地址段文件 (iptables)
```

**Comment by sunmd01** [comment]
状态
```
mode:     chnroute
pxy/tcp:  [stopped]
pxy/udp:  [stopped]
dnsmasq:  [running]
chinadns: [running]
```

**Comment by zfl9** [comment]
请检查一下 `/etc/shadwosocks-libev/config.json` 里面的 local_address （设为 0.0.0.0），local_port 设为 60080（要和 ss-tproxy.conf 里面的端口号一致）

**Comment by sunmd01** [comment]
打扰一下，请问启动时为什么会报这个东西呢？ 
```mount: /etc/resolv.conf: mount point is a symbolic link to nowhere. ```
我没有动过resolv.conf这个文件

**Comment by zfl9** [comment]
执行 `bash -x /usr/local/bin/ss-tproxy restart`，看看是哪个命令报的错？

**Comment by sunmd01** [comment]
![image](https://user-images.githubusercontent.com/9304859/50129267-18ccfe80-02b3-11e9-81e7-76f552407931.png)

**Comment by zfl9** [comment]
```
ls -l /etc/resolv.conf
```
看下这个文件是不是提示中的“符号链接文件”？

**Comment by sunmd01** [comment]
![image](https://user-images.githubusercontent.com/9304859/50129366-8f69fc00-02b3-11e9-8190-cf7d2311b763.png)

**Comment by zfl9** [comment]
试一下将图中的 dns_modify 改为 true，看 restart 会不会报错。能否正常代理？
![image](https://user-images.githubusercontent.com/22726048/50129429-d5bf5b00-02b3-11e9-8bbb-5634c22b7571.png)

**Comment by sunmd01** [comment]
![image](https://user-images.githubusercontent.com/9304859/50129642-e6bc9c00-02b4-11e9-8b21-49d0a418cf1a.png)
![image](https://user-images.githubusercontent.com/9304859/50129649-efad6d80-02b4-11e9-88b7-9c462047486f.png)

代理正常

**Comment by zfl9** [comment]
那还有报错吗？

**Comment by sunmd01** [comment]
我之前试过了，虽然不报错，但是代理会出问题。
我现在正在用着，就不折腾了。

**Comment by sunmd01** [comment]
当然，之前试的时候，没有更改modified选项。

**Comment by zfl9** [comment]
ok，正常就行。不折腾
