### ISSUE TITLE
使用自建DNS解析流量全部走代理

### ISSUE THREAD

**Issue by Auska** [zfl9/ss-tproxy#37]
在PI上安装作为网关工作在主路由下 
ChinaDNS国内DNS 设置为114.114.114.114 工作正常 
修改为同一局域网下的自建DNS（AdGuardHome 单独使用正常）所有流量走代理

**Comment by zfl9** [comment]
目前忙于其他事，请谅解，过段时间再解答。

**Comment by zfl9** [comment]
chinadns.log 能提供一下吗（详细的log，-v 参数）

**Comment by Auska** [comment]
[chinadns.log](https://github.com/zfl9/ss-tproxy/files/2923071/chinadns.log)
chinadns的log
目前使用smartdns替换chinadns进行dns解析工作良好

**Comment by zfl9** [comment]
smartdns？能介绍一下吗？

**Comment by Auska** [comment]
https://github.com/pymumu/smartdns

**Comment by zfl9** [comment]
chinadns 的分流逻辑确实有些问题，本来我是打算自己 fork chinadns 然后自己小改一下的，但是无奈没时间搞这个，看情况吧。暂时先这样。

**Comment by zfl9** [comment]
你看下最新的 ss-tproxy 是否已经解决这个问题（chnroute.txt 列表也要更新一下）

**Comment by zfl9** [comment]
我今天实际测试了一下，dns_direct 也是内网服务器（192.168.x.x），虽然没有出现“全部走代理”的情况 ，但是出现了另外一个问题，就是有些域名在公司内部解析是内网 ip，但是 chinadns 解析出来的 ip 确是外网 ip。。看来还得研究研究。

**Comment by zfl9** [comment]
又小改了一下，貌似是因为 chinadns -y 参数没设好，我现在已经没问题了。
