### ISSUE TITLE
是否可以支持goflyway

### ISSUE THREAD

**Issue by shf4715** [zfl9/ss-tproxy#39]
这款软件能否支持goflyway呢

**Comment by zfl9** [comment]
简单看了一下 goflyway 的 wiki，goflyway 貌似支持 socks5 代理（客户端），且支持 udp relay，那么就可以按照 faq 里面的第一个例子来配置（redsocks2），具体可以看下 <https://www.zfl9.com/ss-redir.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98>
