### ISSUE TITLE
archlinux下dnsforwarder无法启动

### ISSUE THREAD

**Issue by IsoaSFlus** [zfl9/ss-tproxy#4]
之前都没问题的，但最近发现dnsforwarder一启动就变僵尸进程了，不知道作者有没有碰到这个问题?

**Comment by zfl9** [comment]
你是指这个吗？能正常使用吗？我一开始就发现了这个问题，不过实际使用没有问题的，估计是 dnsforwarder 的代码不完善。
![image](https://user-images.githubusercontent.com/22726048/38662422-caff49b2-3e66-11e8-9f25-161988ed0201.png)

**Comment by IsoaSFlus** [comment]
@zfl9 没错我就是指这个，但是我这边status会显示dnsforwarder 是stopped状态，而且我没有办法正常使用（无法解析dns

**Comment by zfl9** [comment]
能把 dnsforwarder 的 log 发过来吗，位于 `/var/log/dnsforwarder.log`
最好先把 ss-tproxy 关了，然后清空此文件，最后开启 ss-tproxy，然后把 log 发过来。

**Comment by IsoaSFlus** [comment]
问题找到了，我把上游dns改成8.8.4.4就好了。。。。真的是邪了门了。

**Comment by IsoaSFlus** [comment]
经过几天的观察我发现事情没有那么简单
我目前的情况是，有部分域名查不到，比如pixiv.net
![image](https://user-images.githubusercontent.com/5125031/38933614-10738fbe-434c-11e8-8473-670a74fec474.png)
比较有意思的是,chinadns明明显示已经查到了
![image](https://user-images.githubusercontent.com/5125031/38933667-3ab707e2-434c-11e8-8b44-a9c0e103e8b0.png)
然而dnsforwarder的log显示是time out
![image](https://user-images.githubusercontent.com/5125031/38933714-5cd0f360-434c-11e8-841d-49f024c005da.png)
非常费解为什么会出现这种问题。

**Comment by zfl9** [comment]
很明显，chinadns 把 阿里DNS 返回的结果个 filter 过滤了。过滤后 chinadns 继续等待 ss-tunnel 的响应，然而 ss-tunnel 并没有在指定时间内返回 DNS 解析结果，因此 dnsforwarder 显示 timeout 了。

**Comment by zfl9** [comment]
你应该检查 ss-tunnel 的问题，dnsforwarder 和 chinadns 应该是正常工作的（从你反馈的信息中）。可能 ss-tunnel 丢包了，或者是其他网络原因。

**Comment by IsoaSFlus** [comment]
还真是。。。换了一个ss试了下，发现正常了，感谢解惑！
