### ISSUE TITLE
请问国外翻回国内，怎么让udp流量通过ss-libev？

### ISSUE THREAD

**Issue by cuteSakuraHime** [zfl9/ss-tproxy#40]
RT，目前解决方案是直接用chnroute然后替换了chnroute的表，感觉过于暴力，请问有什么更好地解决方案吗？比如让chnroute的ip才走ss-redir.

**Comment by zfl9** [comment]
国外翻回国内不是用chnonly模式吗。。。

**Comment by cuteSakuraHime** [comment]
@zfl9 你指的是gfwlist模式吗？

**Comment by cuteSakuraHime** [comment]
```

**Comment by zfl9** [comment]
额，tcp 和 udp 都是分流了的，如果位于黑名单中就会走代理，如果要 udp 全走代理自己加几条规则就行了。

**Comment by cuteSakuraHime** [comment]
明白了，如果我把大陆的IP加入到 `gfwlist.ext` 是不是 UDP 就会走了？

**Comment by cuteSakuraHime** [comment]
主要是游戏服务器，不在那个表里面，所以我测试的时候发现都没走代理

**Comment by zfl9** [comment]
是的，gfwlist.ext 和 gfwlist.txt 里面的ip、域名、网段都是会走代理的

**Comment by zfl9** [comment]
如果列表中没，就自己加上（gfwlist.ext 里面）

**Comment by zfl9** [comment]
然后 ss-tproxy restart 生效

**Comment by cuteSakuraHime** [comment]
明白 感谢解答
