### ISSUE TITLE
想要使用tcponly，可以给我一份v2版吗？

### ISSUE THREAD

**Issue by PlaneV** [zfl9/ss-tproxy#41]
你好！我现在在openwrt路由器里面有个socks5的代理在运行，我想把它变成透明代理，但是这个代理只支持tcp，可以给我一份v2吗？谢谢！

**Comment by zfl9** [comment]
https://github.com/zfl9/ss-tproxy/tree/v2-master，但是因为这是归档版本，所以可能需要自己改一些东西。

**Comment by PlaneV** [comment]
哇~谢谢你
