### ISSUE TITLE
Fedora 29下会出现各种权限错误

### ISSUE THREAD

**Issue by tzwjkl** [zfl9/ss-tproxy#43]
更新后发现systemctl start ss-tproxy无法启动
systemctl status ss-tproxy如下
`Failed at step EXEC spawning /usr/bin/ss-tproxy: Permission denied`
关闭SeLinux可以正常启动
回退到`commit 5b393a3a8107c961c91bec2f933e3ed0d309f900`可以正常启用

有空我在找找具体原因

**Comment by tzwjkl** [comment]
在试用旧版可用后，我把最新版本的ss-tproxy内容全文复制到`/usr/bin/ss-tproxy`内，仍然可用，所以应该不是修改的问题了。
之前发现ss-tproxy.service也是，直接cp进去的话无法用，`systemctl list-unit-files`显示是一个bad的status，即使修改文件权限与其他.service相同、`chown root:root`修改拥有着为管理员也无法解决问题。而自己创建ss-tproxy.service并将内容完全复制进去却能正常使用。
Fedora貌似有些玄学SeLinux policy，之前用Ubuntu没遇到这些问题。

临时解决方案：
安装和升级时不使用`cp`，而是使用`touch`、 `vi`、 `vim` 或 `gedit`自行创建并复制代码内容

**Comment by zfl9** [comment]
这么邪乎？不过我表示从来没开启过selinux，驾驭不了这玩意。明天我在readme说明一下这问题吧。
