### ISSUE TITLE
大大，能不能加入自定义所需代理端口的功能呢？

### ISSUE THREAD

**Issue by lflcan** [zfl9/ss-tproxy#49]
大大你好，我经常用 ss-tproxy 中的 chnroute 模式，用这个模式就意味着大部分境外 ip 都要走代理，如果进行 BT/PT 下载 vps 可能就会被封，但大部分 P2P 类下载软件，多使用高端口，所以我想是不是可以自定义需要代理的端口来避免这个问题。openwrt 上的 luci-app-shadowsocks（https://github.com/shadowsocks/luci-app-shadowsocks） 提供了此功能，恩山上 hiboy 的 Padavan 固件所内置的 ss 也支持了。我感觉这个功能还是挺重要的，期待大大的进一步开发！大大加油！

**Comment by zfl9** [comment]
实现不困难，但最近遇到点事，可能需要过段时间再搞。

**Comment by lflcan** [comment]
感谢大大！能不能再考虑加入 ip/ip段白名单呢，这个功能对于 chnroute 模式也很重要！

**Comment by zfl9** [comment]
已在 todo list 中，这段时间没空，请耐心等待。

**Comment by wd** [comment]
> 感谢大大！能不能再考虑加入 ip/ip段白名单呢，这个功能对于 chnroute 模式也很重要！

白名单可以通过这个方式做。。
```
function post_start() {
    echo "Run post start"
    iptables -t mangle -I SSTP_PRE -s 10.10.8.8 -j RETURN
    iptables -t nat -I SSTP_PRE -s 10.10.8.8 -j RETURN
}
```
