### ISSUE TITLE
强制使用重定向地址的DNS

### ISSUE THREAD

**Issue by YanuZhen** [zfl9/ss-tproxy#5]
客户机如果使用了非路由器的DNS，会无法解析到正确地址。可添加以下规则强制使用重定向地址的DNS
iptables -t mangle -A SS-UDP -p udp --dport 53  -j RETURN
iptables -t nat -A PREROUTING -p udp --dport 53 -j DNAT --to 192.168.1.1

**Comment by zfl9** [comment]
感谢提醒，稍后我将添加到脚本中，这样就不用担心什么 DNS 设置不正确的问题了。

**Comment by zfl9** [comment]
已更新，顺便我还把 ss-tproxy stop 后的 DNS 指向也强制重定向了，尽可能防止客户机的 DNS 不正确问题。

**Comment by YanuZhen** [comment]
感谢更新，白名单IP列表建议用：
https://github.com/17mon/china_ip_list/blob/master/china_ip_list.txt

可能是国内目前最好的白名单IP

**Comment by zfl9** [comment]
嗯，感谢，我也感觉 ip.cn 的白名单列表有遗漏。这就更新。
