### ISSUE TITLE
iptables v1.8.2 不兼容

### ISSUE THREAD

**Issue by tianhuxu** [zfl9/ss-tproxy#51]
在debian 9.9 iptables v1.6.2下运行正常。在debian buster，iptables v1.8.2下启动则会报错。几个表不存在。

**Comment by cattyhouse** [comment]
完美运行, 从不出错

uname -a
Linux n1 4.19.56-1-ARCH #1 SMP PREEMPT Mon Jul 1 14:41:05 CST 2019 aarch64 GNU/Linux

iptables --version
iptables v1.8.3 (legacy)

**Comment by zfl9** [comment]
报什么错

**Comment by tianhuxu** [comment]
重新在vm的debian buster试了一下，一切正常。但是始终无法让ss-tproxy在LXC container下正常运行，总是提示各种table不存在例如mangle不存在。我用的是qnap的debian buster，也有可能是官方镜像的问题。

**Comment by zfl9** [comment]
mangle 表不存在？什么系统，肯定有问题，raw、mangle、nat、filter 四个表是内置的啊。
