### ISSUE TITLE
dns

### ISSUE THREAD

**Issue by cndanili** [zfl9/ss-tproxy#52]

**Comment by cndanili** [comment]
通过脚本已经可以科学上网了。但是remote dns使用8.8.8.8解析Netflix.com或者Hulu.com会被系统识别为代理。设置成私人的dns走全局又比较浪费流量。
尝试用在/etc/dnsmasq.d/dnsmasq.conf中添加address=/netflix.com/privatedns和server=/netflix.com/privatedns没有效果。请问应该如何设置呢？

**Comment by zfl9** [comment]
Netflix提示代理和ss-tproxy没有半毛钱关系，不是说使用ss-tproxy就不会被这些网站检查到使用了代理，它们检测你是否使用了代理的原理是检测访问它们网站的来源ip，也就是你的vps ip。懂了吧？要解决这个问题你折腾 dnsmasq 是没有用的，你需要换 vps 的 ip。

**Comment by zfl9** [comment]
如果要增加自定义的dnsmasq配置，目前需要改脚本，在 `start_resolver` 函数里面，自己加上一条配置，引用 /etc/dnsmasq.d/ 下面的 conf 配置文件就行。具体配置看dnsmasq官方配置文档，后续会更新脚本，以支持自定义dnsmasq的配置文件。
