### ISSUE TITLE
服务器ip解析问题

### ISSUE THREAD

**Issue by HiFiPhile** [zfl9/ss-tproxy#55]
在dev分支中,如果服务器dns为相同地址同时配置了A和AAAA记录,resolve_hostname()无法同时获取到v4和v6的ip.

例如在我这里由于有ipv6支持,ping出来的地址默认是v6的,导致出现错误:
`log_error "not found ipv4 address in the proxy_svraddr: ${proxy_svraddr6[@]}"`

建议用ping4和ping6来获取地址.

**Comment by zfl9** [comment]
感谢建议，过几天有时间再加上。

**Comment by HiFiPhile** [comment]
但用ping -6如果本地ipv6不通的话,会返回Network is unreachable. 感觉还是用host好点
