### ISSUE TITLE
如何让网关（ss-tproxy服务器的自身流量）直连？

### ISSUE THREAD

**Issue by Hscpro** [zfl9/ss-tproxy#57]
看了文章，已尝试将如下代码进行注释但是其他设备也均直连了。

# 本机发出去的 TCP 和 UDP 走一下 SETMARK 链
iptables -t mangle -A SSTP_OUT -p tcp -j SETMARK
iptables -t mangle -A SSTP_OUT -p udp -j SETMARK

**Comment by zfl9** [comment]
为何需要让ss-tproxy主机不走代理，有点奇怪哈，注释这个会导致ss-tproxy主机的dns查询被污染，所以不能注释（主要是 -p udp 那条），因为内网主机的dns请求也是通过ss-tproxy主机上的dnsmasq进行处理的，而dnsmasq发出的udp流量（发往远程dns的）必须得经过代理，不然会被gfw污染。解析不到正确的ip。这应该是你所观察到的其它设备也走直连的原因了。

**Comment by zfl9** [comment]
因为dns的特殊性，你必须代理ss-tproxy主机自身的udp流量，当然ss-tproxy主机的tcp流量确实是可以走直连的。但是udp不行，因为dns要处理。我们的dns分流都是经过dnsmasq、chinadns的，而他们都是运行在ss-tproxy主机，所以这个你无法避免，但我觉得并没有什么理由去阻止ss-tproxy主机自身的流量走代理。

**Comment by Hscpro** [comment]
回复神速！是这样的，我的透明代理主要是给游戏主机用的。线路是游戏专用的贼贵。
我把4条本地链路加了端口限制貌似可以了。   

    iptables -t mangle -A SSTP_OUT -p tcp --dport 53 -j SETMARK
    iptables -t mangle -A SSTP_OUT -p udp --dport 53 -j SETMARK

**Comment by zfl9** [comment]
嗯，也是个好方法。
