### ISSUE TITLE
4.0版运行提示 Couldn't load match `state':No such file or directory

### ISSUE THREAD

**Issue by elvisw** [zfl9/ss-tproxy#58]
4.0版运行时提示：iptables v1.8.3 (legacy): Couldn't load match `state':No such file or directory
环境：OpenWRT Snapshot
我搜了一下，发现这个网页：https://bugs.openwrt.org/index.php?do=details&task_id=1193
```
State is deprecated, use "-m conntrack –ctstate ESTABLISHED,RELATED" instead of "-m state –state ESTABLISHED,RELATED"
```
这是说iptables不支持state了？

**Comment by zfl9** [comment]
应该是的，我待会改一下。

**Comment by zfl9** [comment]
已改。

**Comment by elvisw** [comment]
使用 `bash -x /usr/local/bin/ss-tproxy start`
运行到
```
+ iptables -t mangle -A SSTP_RULE -p udp -m set --match-set gfwlist dst -m multiport --dports 1:65535 -m conntrack -ctstate NEW -j MARK --set-mark 0x2333
```
提示
```
iptables v1.8.3 (legacy): -c packet counter not numeric
```

**Comment by zfl9** [comment]
少了个连字符，我马上更新。。

Elvis Wang <notifications@github.com> 于2019年8月17日周六 下午6:20写道：

**Comment by zfl9** [comment]
已更。
