### ISSUE TITLE
如何设置多个服务器

### ISSUE THREAD

**Issue by changhe3** [zfl9/ss-tproxy#59]
我买了一个ssr服务, 有多个节点, 我看了好几遍文档, 也看不明白该如何设置: 如果在proxy_server填上多个url:
```
proxy_server=(ssr1.net ssr2.net ssr3.net)
```
那么下面的`proxy_runcmd`该怎么填?
还有就是`systemctl start/stop ssr-redir@some_url`到底是这个脚本的feature, 还是ss/ssr的feature?

**Comment by zfl9** [comment]
> 允许填写多个 VPS 地址，用空格隔开，填写多个地址的作用是为了方便切换代理，比如我现在有两个 VPS，VPS-A、VPS-B，假设你先使用 VPS-A，因为某些不可抗拒因素，导致 VPS-A 的网络性能低下，那么你可能就要切换到 VPS-B，如果你只填写了 VPS-A 的地址，那么你就需要去修改 ss-tproxy.conf，将地址改为 VPS-B，还得修改 proxy_startcmd，最后还得重启 ss-tproxy 脚本，非常麻烦，而且更麻烦的是，如果现在 VPS-A 的网络又好了，那么你可能又想切换回 VPS-A，那么你又得重复上述步骤，改配置，重启脚本。但现在，你不需要这么做，你完全可以在 proxy_svraddr 中填写 VPS-A 和 VPS-B 的地址，假设你默认使用 VPS-A（proxy_startcmd），那么启动 ss-tproxy 后，默认使用的就是 VPS-A，此后如果你想切换为 VPS-B，仅需停止 VPS-A 本机代理进程，再启动 VPS-B 本机代理进程（切回来的步骤则相反），该过程无需操作 ss-tproxy。

**Comment by zfl9** [comment]
填写多个服务器地址的目的只是为了方便切换代理，并不是说可以同时使用多个 VPS 的代理。你可能没理解对我的意思。

**Comment by zfl9** [comment]
目前脚本无法做到同时使用两个 VPS 的代理，这非常复杂。

**Comment by hachikujimayoi298** [comment]
我知道没法同时使用多个代理。我意思是如果想这样来回切换，下面的proxy_runcmd填其中一个地址的配置就行吗？

**Comment by changhe3** [comment]
我知道没法同时使用多个代理。我意思是如果想这样来回切换，下面的proxy_runcmd填其中一个地址的配置就行吗？

**Comment by zfl9** [comment]
是的，难道readme说的不清楚？启动命令那里随便选一个，你最喜欢哪个就用哪个，切换就是切换进程。

**Comment by zfl9** [comment]
> 还有就是systemctl start/stop ssr-redir@some_url到底是这个脚本的feature, 还是ss/ssr的feature?

这是 systemd 的使用，和脚本以及其它东西没关系。

**Comment by changhe3** [comment]
所以说只要其他配置都一样，脚本会自动将服务器地址替换，对吧？

**Comment by zfl9** [comment]
不是脚本会自动进行替换，是你这些vps地址都放行了，你用其中任意一个 ip 都行，当然你也可以这么理解。

**Comment by changhe3** [comment]
那就是有几个地址脚本就会启动几个进程？

**Comment by zfl9** [comment]
我到底该如何解释，心累。脚本启动多少进程，完全看你的 runcmd 怎么写，这和你写了多少个 vps 地址有毛关系啊

**Comment by zfl9** [comment]
脚本里面没有内置什么启动代理进程的命令。

**Comment by changhe3** [comment]
你意思是不是下面的`proxy_runcmd`也有填多个, 顺序跟上面的服务器的顺序对应?

**Comment by zfl9** [comment]
不是，假设你有 2 个 vps，一个是 1.1.1.1 一个是 2.2.2.2，假设你使用 ss，假设你默认使用 1.1.1.1，那么配置如下：
```
proxy_server=(1.1.1.1 2.2.2.2)
proxy_runcmd='systemctl start vps1'
proxy_kilcmd='systemctl stop vps1 vps2'
```
这样配置后，执行ss-tproxy start，启动的就是vps1，没疑问吧，默认就是使用 vps。好的，你现在要切换为 vps2，那么进行如下步骤
```
systemctl stop vps1
systemctl start vps2
```
现在使用的就是 vps2。你还不明白我就真没办法了。

**Comment by zfl9** [comment]
你不能写多行runcmd，这个配置文件就是个shell脚本，同名变量会覆盖，只有最后一个生效。

**Comment by changhe3** [comment]
vps1和vps2是要自己写systemctl的设置对吧?

**Comment by zfl9** [comment]
是的，当然没说一定要用 systemctl，只是举个例子

**Comment by zfl9** [comment]
你用什么启动方式都可以，这是完全由你们自己定的。

**Comment by changhe3** [comment]
我明白了, 那我就用ssr-electron来切换代理. 感谢解答.
