### ISSUE TITLE
dnsforwarder	[stopped]

### ISSUE THREAD

**Issue by paulplayer** [zfl9/ss-tproxy#6]
Cannot run properly. Need Help.

$ sudo ss-tproxy restart
[sudo] paul 的密码： 
ss-redir	[stopped]
ss-tunnel	[stopped]
chinadns	[stopped]
dnsforwarder	[stopped]

ss-redir	[running]
ss-tunnel	[running]
chinadns	[running]
dnsforwarder	[stopped]

**Comment by zfl9** [comment]
x86 平台吗？貌似 x86 下的 dnsforwarder 有 bug，无法正常运行。
