### ISSUE TITLE
Error in ASUS-Merlin

### ISSUE THREAD

**Issue by allen7643** [zfl9/ss-tproxy#60]
Hi zfl9, when I try to migrate your ss-tproxy to a asus router running Merlin + entware, I got the error 
/opt/usr/bin/ss-tproxy: line 433: sysctl: command not found

I checked your scripts, and I found you use sysctl to enable IP forward in your machine, but Merlin doesn't have sysctl to manage all the service, how can I replace this command?

**Comment by zfl9** [comment]
```
# enable ipv4 forwarding
echo 1 >/proc/sys/net/ipv4/ip_forward

# enable ipv6 forwarding
echo 1 >/proc/sys/net/ipv6/conf/all/forwarding
```

**Comment by allen7643** [comment]
Thanks for reply. This issue was solved. Another bugs I found in ss-tproxy,
line 404        local temp_resolv_conf=$(mktemp)
Which I found var mktemp is not defined either in ss-tproxy or ss-tproxy.conf

**Comment by cattyhouse** [comment]
@allen7643 
mktemp is a command, not a var. 
$(mktemp) is the std out of mktemp.

**Comment by allen7643** [comment]
Sorry for bother, I already found out mktemp is a command, now I think I'm very close to success.
The latest i got the error below:
```
iptables: Protocol wrong type for socket.
iptables: Protocol wrong type for socket.
iptables: No chain/target/match by that name.
```
Do you have any idea what could be the issue behind that?
Thanks a lot!

**Comment by zfl9** [comment]
execute `bash -x /opt/usr/local/bin/ss-tproxy stop` to see which line is wrong

**Comment by allen7643** [comment]
Looks like option "conntrack --cstate" cause the issue. 
```
+ iptables -t nat -A SSTP_POSTROUTING -s 192.168.0.0/16 '!' -d 192.168.0.0/16 -p udp -m conntrack --ctstate NEW -j MASQUERADE
iptables: Protocol wrong type for socket.
```
Here is the iptables version I'm using, am I missing some packages?
iptables - 1.4.21-2a - IP firewall administration tool.  Matches: - icmp - tcp - udp - comment - conntrack - limit - mac - mark - multiport - set - state - time  Targets: - ACCEPT - CT - DNAT - DROP - REJECT - LOG - MARK - MASQUERADE - REDIRECT - SET - SNAT - TCPMSS  Tables: - filter - mangle - nat - raw

**Comment by zfl9** [comment]
Replace `-m conntrack --ctstate NEW` with `-m state --state NEW`, try it again.

**Comment by zfl9** [comment]
```
iptables: No chain/target/match by that name.
```
This error is triggered by which command?

**Comment by allen7643** [comment]
`+ iptables -t mangle -A SSTP_PREROUTING -p udp -m mark --mark 0x2333 -j TPROXY --on-ip 127.0.0.1 --on-port 60080`
This command reports:  the iptables: No chain/target/match by that name.

**Comment by zfl9** [comment]
Your iptables are missing the tproxy module.

**Comment by zfl9** [comment]
> Replace `-m conntrack --ctstate NEW` with `-m state --state NEW`, try it again.

@allen7643 After the change, is it working normally?

**Comment by allen7643** [comment]
> 
> I tried but still same errors... Does it related to linux kernel? 
> Replace `-m conntrack --ctstate NEW` with `-m state --state NEW`, try it again.

**Comment by zfl9** [comment]
> > Replace `-m conntrack --ctstate NEW` with `-m state --state NEW`, try it again.
> > I tried but still same errors... Does it related to linux kernel?

For these rules on the `POSTROUTING` chain, you can actually remove `-m state/-m conntrack` if your iptables don't support it.

**Comment by zfl9** [comment]
> `+ iptables -t mangle -A SSTP_PREROUTING -p udp -m mark --mark 0x2333 -j TPROXY --on-ip 127.0.0.1 --on-port 60080`
> This command reports: the iptables: No chain/target/match by that name.

But for the tproxy module, this is a must, without it, the transparent proxy will not work.

**Comment by allen7643** [comment]
> 
> 
> > `+ iptables -t mangle -A SSTP_PREROUTING -p udp -m mark --mark 0x2333 -j TPROXY --on-ip 127.0.0.1 --on-port 60080`
> > This command reports: the iptables: No chain/target/match by that name.
> 
> But for the tproxy module, this is a must, without it, the transparent proxy will not work.

There is indeed a tproxy moduleI in my router, but I don't know why it's not loaded automatically. After I add a load command in your scripts, this errors solved.
```
find /lib/modules/$(uname -r) -type f -name '*.ko*' | grep 'xt_TPROXY'
/lib/modules/2.6.36.4brcmarm/kernel/net/netfilter/xt_TPROXY.ko
```

**Comment by zfl9** [comment]
So now the problem is solved? Is the transparent proxy working properly?

**Comment by allen7643** [comment]
> So now the problem is solved? Is the transparent proxy working properly?
I also solved the iptables issue. The reason is merlin has iptables which works with you original scripts, but I installed another iptables with entware, that cause the issue.
Now, I don't get any  error output, but the scripts can't start v2ray & dnsmasq, when I run ss-tproxy start, I got the output below:
mode:     chnroute
pxy/tcp:  [stopped]
pxy/udp:  [stopped]
dnsmasq:  [stopped]
chinadns: [running]

**Comment by allen7643** [comment]
The transparent proxy work successfully now!!! Thanks for you nicely guidance!
I'm thinking if you can tweak the scripts and make it also default work for merlin it would be much appreciate! I can contribute my adjusted code to you

**Comment by zfl9** [comment]
Of course, you can tell me here, where you changed, and some suggestions, I am happy to receive it.

**Comment by zfl9** [comment]
Not responding for a long time
