### ISSUE TITLE
ss-tproxy system can not reach oversea address

### ISSUE THREAD

**Issue by johnzhang2015** [zfl9/ss-tproxy#63]
check with ss-tproxy status and all are green.
check with curl -4vsSkL https://www.baidu.com, result is good.
but check with curl -4vsSkL https://www.google.com,

it report:
```
* Rebuilt URL to: https://www.google.com/
* Could not resolve host: www.google.com
* Closing connection 0
curl: (6) Could not resolve host: www.google.com
```

check SS-redir log like below:
```
2019-09-05 19:47:49 INFO: [udp] server receive a packet
 2019-09-05 19:47:49 INFO: [1080] [udp] cache hit: x.x.x.x:xx <-> x.x.x.x:xx
 2019-09-05 19:47:49 INFO: [udp] server_recv_sendto fragmentation, MTU at least be: 2912
 2019-09-05 19:47:49 INFO: [udp] UDP server_recv_recvmsg fragmentation, MTU at least be: 2889
 2019-09-05 19:47:49 INFO: [udp] server receive a packet
```
After recompile chinadns-ng with arm arch, there is no log report again.

The original error log is "[dns_rheader_check] no resource records found in the dn s reply packet"
when I used original compile method.

Thanks if you have time to reply it!

**Comment by zfl9** [comment]
This is a configuration issue with ss-redir or ss-server, and the log output from ss-redir illustrates this. Please check the configuration or go to the shadowsocks-libev home page.

**Comment by zfl9** [comment]
Note these two outputs
```
 2019-09-05 19:47:49 INFO: [udp] server_recv_sendto fragmentation, MTU at least be: 2912
 2019-09-05 19:47:49 INFO: [udp] UDP server_recv_recvmsg fragmentation, MTU at least be: 2889
```

**Comment by johnzhang2015** [comment]
the configuration on server side is ok when use other SS client like SS windows, 

the configuration on the tranparency gateway:

For SS redir config:

{
   	"server":"x.x.x.x",
	"server_port":xx,
	"local_address": "0.0.0.0",

	"local_port":xx,
	
	"password":"xxxxx",
	"timeout":600,
   	
    	"method":"xxxx",
    	
    	 "no_delay": true,
   	 "fast_open":true,
    	


}


For SS tproxy, the config:

## mode
#mode='gfwlist' # gfwlist 分流 (黑名单)
mode='chnroute' # chnroute 分流 (白名单)

## ipv4/6
ipv4='true'     # true:启用ipv4透明代理; false:关闭ipv4透明代理
ipv6='false'    # true:启用ipv6透明代理; false:关闭ipv6透明代理

## tproxy
tproxy='false'  # true:TPROXY+TPROXY; false:REDIRECT+TPROXY

## selfonly
selfonly='false' # true:仅代理本机流量; false:代理本机及"内网"流量

## proxy
proxy_svraddr4=(xxxxx) # 服务器的 IPv4 地址或域名，允许填写多个服务器地址，空格隔开
proxy_svraddr6=()        # 服务器的 IPv6 地址或域名，允许填写多个服务器地址，空格隔开
proxy_svrport='80,443'   # 服务器的外网监听端口，格式同 ipts_proxy_dst_port，不可留空
proxy_tcpport='xx'    # ss/ssr/v2ray 等本机进程的 TCP 监听端口，该端口支持透明代理
proxy_udpport='xx'    # ss/ssr/v2ray 等本机进程的 UDP 监听端口，该端口支持透明代理
proxy_startcmd='(ss-redir -c /etc/shadowsocks-libev/config.json -u -v </dev/null &>>/var/log/ss-redir.log &)'     # 用于启动本机代理进程的 shell 命令，该命令应该能立即执行完毕
proxy_stopcmd='kill -9 $(pidof ss-redir)'      # 用于关闭本机代理进程的 shell 命令，该命令应该能立即执行完毕

## dnsmasq
dnsmasq_bind_port='5354'                  # dnsmasq 服务器监听端口，见 README
dnsmasq_cache_size='4096'               # DNS 缓存大小，大小为 0 表示禁用缓存
dnsmasq_cache_time='3600'               # DNS 缓存时间，单位是秒，最大 3600 秒
dnsmasq_log_enable='true'              # 记录详细日志，除非进行调试，否则不建议启用
dnsmasq_log_file='/var/log/dnsmasq.log' # 日志文件，如果不想保存日志可以改为 /dev/null
dnsmasq_conf_dir=()                     # `--conf-dir` 选项的参数，可以填多个，空格隔开
dnsmasq_conf_file=()                    # `--conf-file` 选项的参数，可以填多个，空格隔开

## chinadns
chinadns_bind_port='65353'               # chinadns-ng 服务器监听端口，通常不用改动
chinadns_timeout='3'                     # 等待上游 DNS 返回响应的超时时间，单位为秒
chinadns_repeat='1'                      # 向可信 DNS 发送几次 DNS 查询请求，默认为 1
chinadns_fairmode='false'                # 使用公平模式，具体看 chinadns-ng 的 README
chinadns_verbose='true'                 # 记录详细日志，除非进行调试，否则不建议启用
chinadns_logfile='/var/log/chinadns.log' # 日志文件，如果不想保存日志可以改为 /dev/null
chinadns_privaddr4=()                    # IPv4 私有地址段，多个用空格隔开，具体见 README
chinadns_privaddr6=()                    # IPv6 私有地址段，多个用空格隔开，具体见 README

## dns
dns_direct='114.114.114.114'          # 本地 IPv4 DNS，不能指定端口，也可以填组织、公司内部 DNS
dns_direct6='240C::6666'              # 本地 IPv6 DNS，不能指定端口，也可以填组织、公司内部 DNS
dns_remote='1.1.1.1#53'               # 远程 IPv4 DNS，必须指定端口，提示：访问远程 DNS 会走代理
dns_remote6='2001:4860:4860::8888#53' # 远程 IPv6 DNS，必须指定端口，提示：访问远程 DNS 会走代理

## ipts
ipts_if_lo='lo'                 # 环回接口的名称，在标准发行版中，通常为 lo，如果不是请修改
ipts_rt_tab='233'               # iproute2 路由表名或表 ID，除非产生冲突，否则不建议改动该选项
ipts_rt_mark='0x2333'           # iproute2 策略路由的防火墙标记，除非产生冲突，否则不建议改动该选项
ipts_set_snat='false'           # 设置 iptables 的 MASQUERADE 规则，布尔值，`true/false`，详见 README
ipts_set_snat6='false'          # 设置 ip6tables 的 MASQUERADE 规则，布尔值，`true/false`，详见 README
ipts_reddns_onstop='true'       # ss-tproxy stop 后，是否将其它主机发至本机的 DNS 重定向至直连 DNS，详见 README
ipts_proxy_dst_port='1:65535'   # 黑名单 IP 的哪些端口走代理，多个用逗号隔开，冒号为端口范围(含边界)，详见 README

## opts
opts_ss_netstat='auto'                  # auto/ss/netstat，用哪个端口检测命令，见 README
opts_overwrite_resolv='false'           # true/false，定义如何修改 resolv.conf，见 README
opts_ip_for_check_net='114.114.114.114' # 用来检测外网是否可访问的 IP，该 IP 需要允许 ping

## file
file_gfwlist_txt='/etc/ss-tproxy/gfwlist.txt'      # gfwlist 黑名单文件 (默认规则)
file_gfwlist_ext='/etc/ss-tproxy/gfwlist.ext'      # gfwlist 黑名单文件 (扩展规则)
file_chnroute_set='/etc/ss-tproxy/chnroute.set'    # chnroute 地址段文件 (iptables)
file_chnroute6_set='/etc/ss-tproxy/chnroute6.set'  # chnroute6 地址段文件 (ip6tables)
file_dnsserver_pid='/etc/ss-tproxy/.dnsserver.pid' # dnsmasq 和 chinadns-ng 的 pid 文件

Currently I don't knw how it happend and no idear how to solve it.

**Comment by zfl9** [comment]
Maybe you can look at these Issues:
- <https://github.com/shadowsocks/shadowsocks-libev/issues/1534>
- <https://github.com/shadowsocks/luci-app-shadowsocks/issues/105>
- <https://github.com/shadowsocks/shadowsocks-libev/issues/832>
- <https://github.com/shadowsocks/shadowsocks-libev/issues/1211>

**Comment by cattyhouse** [comment]
{
   	"server":"x.x.x.x",
	"server_port":xx,
	"local_address": "0.0.0.0",
	"local_port":xx,
	"password":"xxxxx",
	"timeout":600,
        "method":"chacha20-ietf-poly1305",
        "mode":"tcp_and_udp",
   	 "reuse_port": true
}

**Comment by zfl9** [comment]
Not responding for a long time
