### ISSUE TITLE
关于文档中archlinux安装依赖的问题

### ISSUE THREAD

**Issue by cjwddtc** [zfl9/ss-tproxy#64]
https://www.zfl9.com/ss-redir.html#%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96这个页面中安装依赖的文档关于在arch中安装ssr的部分为什么需要手动编译两个依赖库呢？官方的源均可以直接安装，是否有什么版本不能太新的说法？

**Comment by zfl9** [comment]
仅供参考，以具体操作为准。自己多试试就行了。
