### ISSUE TITLE
gfwlist模式下黑名单域名无法解析

### ISSUE THREAD

**Issue by elvisw** [zfl9/ss-tproxy#65]
系统：openwrt snapshot
v2ray本地配置：[https://pastebin.com/EFpvsnu3](https://pastebin.com/EFpvsnu3)
ss-tproxy配置：[https://pastebin.com/Fv6y40yf](https://pastebin.com/Fv6y40yf)
运行ss-tproxy show-iptables的结果：[https://pastebin.com/6Xg2RZSa](https://pastebin.com/6Xg2RZSa)

在路由器运行`dig www.twitter.com`时，提示：
```

; <<>> DiG 9.14.3 <<>> www.twitter.com
;; global options: +cmd
;; connection timed out; no servers could be reached

```

查看dnsmasq日志显示：
```
Sep  6 22:23:42 dnsmasq[14204]: query[A] twitter.com from 127.0.0.1
Sep  6 22:23:42 dnsmasq[14204]: forwarded twitter.com to 2001:4860:4860::8888
Sep  6 22:23:42 dnsmasq[14204]: forwarded twitter.com to 8.8.8.8
Sep  6 22:23:43 dnsmasq[14204]: query[A] twitter.com from ::1
Sep  6 22:23:43 dnsmasq[14204]: forwarded twitter.com to 2001:4860:4860::8888
Sep  6 22:23:43 dnsmasq[14204]: forwarded twitter.com to 8.8.8.8

```

但是V2ray日志没有任何显示（日志级别为info），似乎是UDP代理没有起作用。我研究了好几天都没有结果，请帮我看一下。

**Comment by cattyhouse** [comment]
提供的信息很详细，我只想说，openwrt的iptables我看完就醉了。

既然用了openwrt做主路由器，检查下MASQUERADE （SNAT）设置呗。

**Comment by zfl9** [comment]
你这规则也太多了点。。。debug级别有没有日志？

**Comment by zfl9** [comment]
规则大概看了一下，应该没问题，就是不确定是否会与其他规则冲突。

**Comment by zfl9** [comment]
毕竟 iptables 这玩意，很多时候光靠看是看不出问题的。

**Comment by elvisw** [comment]
那我回去了试试把一些和防火墙有关的不必要的功能禁用了，看看啥情况。

**Comment by zfl9** [comment]
另外看下 debug 级别，虽然印象中 info 级别也会有相应的 log。但不妨试试。

**Comment by elvisw** [comment]
我把koolshare的一些插件禁用了，然后把mwan删了，就正常了，看样子还是koolshare的那一堆插件的问题。
