### ISSUE TITLE
还需要安装ssr软件么？

### ISSUE THREAD

**Issue by jackjin-cn** [zfl9/ss-tproxy#66]
比如还需要安装ss-local之类的软件？我是新手，不太明白。

**Comment by zfl9** [comment]
说明你没有认真读readme的前面几段。如果你要使用ssr透明代理，那么请安装ssr-libev。ssr-local也行，但是需要配合redsocks2。再认真读一遍文档吧。

**Comment by HELLOVENUSLRP** [comment]
[xxxxxx@promote ~]$ ssr install
/usr/local/bin/ssr:行7: 未预期的符号“newline”附近有语法错误
/usr/local/bin/ssr:行7: `<!DOCTYPE html>'

**Comment by zfl9** [comment]
@HELLOVENUSLRP 请不要将无关问题发到这里。
