### ISSUE TITLE
ssr install 指令无法执行

### ISSUE THREAD

**Issue by HELLOVENUSLRP** [zfl9/ss-tproxy#67]
[xxx@promote ~]$ sudo mv ssr /usr/local/bin
[sudo]xxx 的密码：
[lxxx@promote ~]$ sudo chmod 766 /usr/local/bin/ssr
[xxx@promote ~]$ ssr install
/usr/local/bin/ssr:行7: 未预期的符号“newline”附近有语法错误
/usr/local/bin/ssr:行7: `<!DOCTYPE html>'

**Comment by zfl9** [comment]
这里不是 ssr 项目的主页，不要发到这里。
