### ISSUE TITLE
你好，为什么没有全局代理模式了呢

### ISSUE THREAD

**Issue by shenfu1991** [zfl9/ss-tproxy#68]
你好，为什么没有全局代理模式了呢？因为刚刚发现机器是国内家庭宽带的ip，然后从国内的服务器下载东西很慢，也许使用代理之后速度会快一点，所以为什么移除了全局代理呢？谢谢。

**Comment by zfl9** [comment]
移除global模式只是个人觉得很少人用。既然需要，那么过几天再加上吧。

**Comment by shenfu1991** [comment]
@zfl9 感谢大佬
