### ISSUE TITLE
请问NS NAT Type F 有办法解决吗？

### ISSUE THREAD

**Issue by cuteSakuraHime** [zfl9/ss-tproxy#70]
路由器设置好之后在电脑上是Fullcone NAT1，但是NS检测出来就是Type F。

**Comment by zfl9** [comment]
v2ray么？

**Comment by zfl9** [comment]
这个和 ss-tproxy 应该没有关系的，应该是代理的原因。

**Comment by zfl9** [comment]
因为我这边好几个人测试都是正常的 NAT TYPA A，也是 NS 主机测试的。

**Comment by zfl9** [comment]
借用一张之前的测试图：
![image](https://user-images.githubusercontent.com/22726048/64965998-92405e80-d8d0-11e9-80dd-f9c0aa890bf4.png)

**Comment by zfl9** [comment]
另外根据经验，NAT Type 一般就是 A/B/C/D，A最高。如果低于 D，比如 E/F，基本上都意味着 UDP 都没代理成功（udp 连接失败或者等等低级问题）。

**Comment by cuteSakuraHime** [comment]
傻了，我现在测下来PC是Fullcone完全没问题，但是同节点NS就是NAT Type F。
我目前的框架是这样的：
Router （KOOLSS）-> 阿里云深圳 （shadowsocks-py-mu->SSTPROXY） -> 阿里云香港 （独立的SS-libev）
这样下来就是Type F，但是我用下面这种方式就是Type A
Router （KOOLSS）-> 阿里云深圳 （iptables端口转发） -> 阿里云香港 （shadowsocks-py-mu）

**Comment by zfl9** [comment]
sstproxy不适合运行在vps来担当中转的角色

**Comment by zfl9** [comment]
中转的话直接用几条简单的iptables nat规则就够了
