### ISSUE TITLE
关于bypass翻墙软件本身流量的方法

### ISSUE THREAD

**Issue by cjwddtc** [zfl9/ss-tproxy#72]
相比于记录服务器的ip，有一种更方便的方法可以让iptables放行翻墙软件本身本的流量，iptables有一个选项-m --uid-owner xxx，这个选项可以让某个规则对指定用户生效，这样只需要单独建立一个用户运行翻墙工具，就可能实现bypass翻墙软件的出站流量的功能。
相比于单独设置ip的方式，这种方法更加方便，既不需要担心域名所对应的ip更换或者本身就对应多个ip，也不需要在修改节点是修改配置。

**Comment by zfl9** [comment]
嗯，提议不错。有时间再加上吧，让这两种方式共存。
