### ISSUE TITLE
透明代理配置成功后

### ISSUE THREAD

**Issue by cjwddtc** [zfl9/ss-tproxy#77]
使用ss-tproxy配置透明代理成功后，确实能够翻墙访问外网，但是网速十分缓慢，大约只有10mbps左右，远低于电脑客户端的速度，我是用的是虚拟机不存在cpu性能不够的说法，而且用clash自己搭全局（clash分流，iptables全局）速度也能跑满百兆。
htop能看到ss-redir的cpu占用只有13%左右。
是否是iptables出现了性能瓶颈？

**Comment by hcym** [comment]
肯定有不对的，我用j1900和n1都跑过实体机，和电脑差距不大，比op强一点点，就是没有op方便

**Comment by zfl9** [comment]
虽然我不是iptables专家，但是关于性能问题，我有信心告诉你，问题不在iptables。自己好好找原因吧。也不是光我们一两个人用，如果有性能问题，而且真如你说的这么严重，早就很多类似的issue了。

**Comment by zfl9** [comment]
如果你找不到原因，那么我也没啥好办法，也许sstproxy真的不适合你。
