### ISSUE TITLE
dnsmasq log 权限错误

### ISSUE THREAD

**Issue by mting806** [zfl9/ss-tproxy#78]
配置文件里如果指定 
dnsmasq_log_file='/var/log/dnsmasq.log'
开机自启动 无论用 SysVinit 还是Systemd ， dnsmasq都会failed ，具体log 如下。登录以后手工重启dnsmasq可以恢复正常
修改成 
dnsmasq_log_file='/dev/null'
可以避免这个情况

[root@rt-2 ~]# systemctl status ss-tproxy -l
● ss-tproxy.service - linux transparent proxy script
   Loaded: loaded (/etc/systemd/system/ss-tproxy.service; enabled; vendor preset: disabled)
   Active: active (exited) since Thu 2019-10-03 12:02:59 UTC; 2min 15s ago
  Process: 3543 ExecStop=/usr/local/bin/ss-tproxy stop (code=exited, status=0/SUCCESS)
  Process: 3614 ExecStart=/usr/local/bin/ss-tproxy start (code=exited, status=0/SUCCESS)
 Main PID: 3614 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/ss-tproxy.service
           └─3688 chinadns-ng -b 127.0.0.1 -l 65353 -o 3 -p 1 -c 114.114.114.114 -t 8.8.8.8 53

Oct 03 12:02:58 rt-2 systemd[1]: Starting linux transparent proxy script...
Oct 03 12:02:59 rt-2 ss-tproxy[3614]: dnsmasq: cannot open log /var/log/dnsmasq.log: Permission denied
Oct 03 12:02:59 rt-2 ss-tproxy[3614]: iptables v1.4.21: Set chnroute doesn't exist.

**Comment by zfl9** [comment]
你自己设置一下 `/var/log/dnsmasq.log` 文件的权限以及所有者，这个和脚本没关系。

**Comment by mting806** [comment]
修改成777 结果一样

On 3. Oct 2019, at 14:14, zfl9 <notifications@github.com<mailto:notifications@github.com>> wrote:


你自己设置一下 /var/log/dnsmasq.log 文件的权限以及所有者，这个和脚本没关系。

**Comment by zfl9** [comment]
这么奇怪？你是第一个遇到这个问题的人。试试：
```bash
touch /var/log/dnsmasq.log
chown nobody:root /var/log/dnsmasq.log
chmod 0640 /var/log/dnsmasq.log
```

**Comment by mting806** [comment]
结果一样
并且修改之前 dnsmasq.log
的权限就是 nobody:root 0644

On 3. Oct 2019, at 14:18, zfl9 <notifications@github.com<mailto:notifications@github.com>> wrote:


touch /var/log/dnsmasq.log
chown nobody:root /var/log/dnsmasq.log
chmod 0640 /var/log/dnsmasq.log

**Comment by zfl9** [comment]
什么系统哦，头一次遇到这么奇葩的。你开了 selinux？

**Comment by zfl9** [comment]
你先把 Logfile 改为 /dev/null，然后启动 ss-tproxy，然后执行如下命令，输出发来看看：
```
ps -ef | grep dnsmasq
```

**Comment by mting806** [comment]
[root@rt-2 ~]# ps -ef | grep dnsmasq
nobody    2969     1  0 12:33 ?        00:00:00 dnsmasq --keep-in-foreground --conf-file=-
root      3104  3083  0 12:34 ttyS0    00:00:00 grep --color=auto dnsmasq

然后在吧配置文件改回 dnsmasq_log_file='/var/log/dnsmasq.log' 也正常了
奇怪了

**Comment by zfl9** [comment]
这。。。那就不研究了。
