### ISSUE TITLE
Openwrt 下启动报错，请指教

### ISSUE THREAD

**Issue by pizzamx** [zfl9/ss-tproxy#79]
我知道这肯定是我环境的问题，但放狗搜网上似乎压根没人有这种问题……

uname -a 
`Linux OpenWrt 4.18.7-aml-s9xxx #1 SMP PREEMPT Mon Jul 8 11:42:44 CST 2019 aarch64 GNU/Linux`

iptables --version
`iptables v1.8.2 (legacy)`

ss-tproxy start
`RTNETLINK answers: Address family not supported by protocol
Dump terminated
......
iptables v1.8.2 (legacy): Couldn't load match 'addrtype':No such file or directory`

**Comment by zfl9** [comment]
addrtype 这个 iptables 模块没有。话说我在 Android 手机上都有这个 `addrtype` 匹配模块。或许这个模块需要你手动加载一下？我不是很清楚，我能告诉你的就这么多。

**Comment by zfl9** [comment]
模块名应该是这个：
```shell
# root @ arch in /opt/ipt2socks on git:master x [13:42:30] 
$ modprobe xt_addrtype

# root @ arch in /opt/ipt2socks on git:master x [13:43:14] 
$ lsmod | grep addrtype
xt_addrtype            16384  0
x_tables               49152  2 xt_addrtype,ip_tables
```

**Comment by hcym** [comment]
op上用这个，不需要舍近求远吧，这个用在标准系统才是最好的选择

**Comment by pizzamx** [comment]
> op上用这个，不需要舍近求远吧，这个用在标准系统才是最好的选择
碰到了比较诡异的问题，找不到解决办法，迫不得已想另辟蹊径……

**Comment by pizzamx** [comment]
> 模块名应该是这个：
> 
> ```shell
> # root @ arch in /opt/ipt2socks on git:master x [13:42:30] 
> $ modprobe xt_addrtype
> 
> # root @ arch in /opt/ipt2socks on git:master x [13:43:14] 
> $ lsmod | grep addrtype
> xt_addrtype            16384  0
> x_tables               49152  2 xt_addrtype,ip_tables
> ```

谢谢老哥

**Comment by elvisw** [comment]
你用的不是原版的openwrt吗

**Comment by pizzamx** [comment]
> 
> 
> 你用的不是原版的openwrt吗

不是，设备 N1，装的 Armbian+docker，OP 是用别人编译的 docker 镜像。然后爬的时候苹果设备都没问题，安卓用 Google 系总是有一些奇怪的问题，似乎也没人遇到过，所以只好想着换一种办法

**Comment by hcym** [comment]
armbian直接用没问题，dock我是没用过，直接用op也没有问题，没用旁路，加了usb网卡做主路由，实体机跑，无论原版官方还是lean等等，谷歌市场不顺应该还是dns的事

**Comment by pizzamx** [comment]
> 
> 
> armbian直接用没问题，dock我是没用过，直接用op也没有问题，没用旁路，加了usb网卡做主路由，实体机跑，无论原版官方还是lean等等，谷歌市场不顺应该还是dns的事

不只是市场，油管、相册什么的，只要是他家的都有问题，并且找不出规律：有时候没问题，大部分时间打不开。Chrome 又完全没问题。我猜也是 DNS，iOS 的机制似乎是不一样的

**Comment by hcym** [comment]
n1做单臂路由肯定是有这个的，简直痛不欲生。我也是被逼无奈用的usb网卡，据说用vlan标定的没有问题，对我是太复杂

**Comment by cattyhouse** [comment]
> n1做单臂路由肯定是有这个的，简直痛不欲生。我也是被逼无奈用的usb网卡，据说用vlan标定的没有问题，对我是太复杂

问题是, 做单臂路由器, 还是要配置交换机或者无线路由器,以提供Wi-Fi和有线给其他设备. 那么这样想: 反正所需的设备都是一样的, 我不如N1做简单的旁路, 让无线路由器负责拨号, 无线路由器不要刷机, 就用官方的固件. 

这样效率很高.

**Comment by pizzamx** [comment]
> 
> 
> > n1做单臂路由肯定是有这个的，简直痛不欲生。我也是被逼无奈用的usb网卡，据说用vlan标定的没有问题，对我是太复杂
> 
> 问题是, 做单臂路由器, 还是要配置交换机或者无线路由器,以提供Wi-Fi和有线给其他设备. 那么这样想: 反正所需的设备都是一样的, 我不如N1做简单的旁路, 让无线路由器负责拨号, 无线路由器不要刷机, 就用官方的固件.
> 
> 这样效率很高.

我现在就是 N1 旁路，主路由没有动，但就是解决不了安卓的问题……苹果（iOS、macOS ）一切安好

**Comment by cattyhouse** [comment]
> > > n1做单臂路由肯定是有这个的，简直痛不欲生。我也是被逼无奈用的usb网卡，据说用vlan标定的没有问题，对我是太复杂
> > 
> > 
> > 问题是, 做单臂路由器, 还是要配置交换机或者无线路由器,以提供Wi-Fi和有线给其他设备. 那么这样想: 反正所需的设备都是一样的, 我不如N1做简单的旁路, 让无线路由器负责拨号, 无线路由器不要刷机, 就用官方的固件.
> > 这样效率很高.
> 
> 我现在就是 N1 旁路，主路由没有动，但就是解决不了安卓的问题……苹果（iOS、macOS ）一切安好

远离 openwrt ... 
https://github.com/cattyhouse/N1-install

**Comment by pizzamx** [comment]
> 
> 
> > > > n1做单臂路由肯定是有这个的，简直痛不欲生。我也是被逼无奈用的usb网卡，据说用vlan标定的没有问题，对我是太复杂
> > > 
> > > 
> > > 问题是, 做单臂路由器, 还是要配置交换机或者无线路由器,以提供Wi-Fi和有线给其他设备. 那么这样想: 反正所需的设备都是一样的, 我不如N1做简单的旁路, 让无线路由器负责拨号, 无线路由器不要刷机, 就用官方的固件.
> > > 这样效率很高.
> > 
> > 
> > 我现在就是 N1 旁路，主路由没有动，但就是解决不了安卓的问题……苹果（iOS、macOS ）一切安好
> 
> 远离 openwrt ...
> https://github.com/cattyhouse/N1-install

您这个说实话理解有点费劲……是说先在一个 arm64 系统把 Archlinux 装到 U 盘，然后再弄到 N1 的 EMMC 吗？于是 N1 运行 Archlinux 而不是 Armbian？为什么不直接用 Armbian？另外之后呢，按这个指南做成旁路由吗？

**Comment by zfl9** [comment]
> > > > > n1做单臂路由肯定是有这个的，简直痛不欲生。我也是被逼无奈用的usb网卡，据说用vlan标定的没有问题，对我是太复杂
> > > > 
> > > > 
> > > > 问题是, 做单臂路由器, 还是要配置交换机或者无线路由器,以提供Wi-Fi和有线给其他设备. 那么这样想: 反正所需的设备都是一样的, 我不如N1做简单的旁路, 让无线路由器负责拨号, 无线路由器不要刷机, 就用官方的固件.
> > > > 这样效率很高.
> > > 
> > > 
> > > 我现在就是 N1 旁路，主路由没有动，但就是解决不了安卓的问题……苹果（iOS、macOS ）一切安好
> > 
> > 
> > 远离 openwrt ...
> > https://github.com/cattyhouse/N1-install
> 
> 您这个说实话理解有点费劲……是说先在一个 arm64 系统把 Archlinux 装到 U 盘，然后再弄到 N1 的 EMMC 吗？于是 N1 运行 Archlinux 而不是 Armbian？为什么不直接用 Armbian？另外之后呢，按这个指南做成旁路由吗？

直接用 armbian 就行了。

**Comment by cattyhouse** [comment]
> > > > > n1做单臂路由肯定是有这个的，简直痛不欲生。我也是被逼无奈用的usb网卡，据说用vlan标定的没有问题，对我是太复杂
> > > > 
> > > > 
> > > > 问题是, 做单臂路由器, 还是要配置交换机或者无线路由器,以提供Wi-Fi和有线给其他设备. 那么这样想: 反正所需的设备都是一样的, 我不如N1做简单的旁路, 让无线路由器负责拨号, 无线路由器不要刷机, 就用官方的固件.
> > > > 这样效率很高.
> > > 
> > > 
> > > 我现在就是 N1 旁路，主路由没有动，但就是解决不了安卓的问题……苹果（iOS、macOS ）一切安好
> > 
> > 
> > 远离 openwrt ...
> > https://github.com/cattyhouse/N1-install
> 
> 您这个说实话理解有点费劲……是说先在一个 arm64 系统把 Archlinux 装到 U 盘，然后再弄到 N1 的 EMMC 吗？于是 N1 运行 Archlinux 而不是 Armbian？为什么不直接用 Armbian？另外之后呢，按这个指南做成旁路由吗？

直接用armbian也可以, 只是我觉得arch更好玩.

**Comment by pizzamx** [comment]
> 
> 
> > > > > > n1做单臂路由肯定是有这个的，简直痛不欲生。我也是被逼无奈用的usb网卡，据说用vlan标定的没有问题，对我是太复杂
> > > > > 
> > > > > 
> > > > > 问题是, 做单臂路由器, 还是要配置交换机或者无线路由器,以提供Wi-Fi和有线给其他设备. 那么这样想: 反正所需的设备都是一样的, 我不如N1做简单的旁路, 让无线路由器负责拨号, 无线路由器不要刷机, 就用官方的固件.
> > > > > 这样效率很高.
> > > > 
> > > > 
> > > > 我现在就是 N1 旁路，主路由没有动，但就是解决不了安卓的问题……苹果（iOS、macOS ）一切安好
> > > 
> > > 
> > > 远离 openwrt ...
> > > https://github.com/cattyhouse/N1-install
> > 
> > 
> > 您这个说实话理解有点费劲……是说先在一个 arm64 系统把 Archlinux 装到 U 盘，然后再弄到 N1 的 EMMC 吗？于是 N1 运行 Archlinux 而不是 Armbian？为什么不直接用 Armbian？另外之后呢，按这个指南做成旁路由吗？
> 
> 直接用 armbian 就行了。

我觉得似乎加一个 docker 更好，这样随便折腾也不会有事，不动 Armbian

> 
> 
> > > > > > n1做单臂路由肯定是有这个的，简直痛不欲生。我也是被逼无奈用的usb网卡，据说用vlan标定的没有问题，对我是太复杂
> > > > > 
> > > > > 
> > > > > 问题是, 做单臂路由器, 还是要配置交换机或者无线路由器,以提供Wi-Fi和有线给其他设备. 那么这样想: 反正所需的设备都是一样的, 我不如N1做简单的旁路, 让无线路由器负责拨号, 无线路由器不要刷机, 就用官方的固件.
> > > > > 这样效率很高.
> > > > 
> > > > 
> > > > 我现在就是 N1 旁路，主路由没有动，但就是解决不了安卓的问题……苹果（iOS、macOS ）一切安好
> > > 
> > > 
> > > 远离 openwrt ...
> > > https://github.com/cattyhouse/N1-install
> > 
> > 
> > 您这个说实话理解有点费劲……是说先在一个 arm64 系统把 Archlinux 装到 U 盘，然后再弄到 N1 的 EMMC 吗？于是 N1 运行 Archlinux 而不是 Armbian？为什么不直接用 Armbian？另外之后呢，按这个指南做成旁路由吗？
> 
> 直接用armbian也可以, 只是我觉得arch更好玩.

好玩是指什么呢？另外你为啥说要远离 OP……

**Comment by zfl9** [comment]
> > > > > > > n1做单臂路由肯定是有这个的，简直痛不欲生。我也是被逼无奈用的usb网卡，据说用vlan标定的没有问题，对我是太复杂
> > > > > > 
> > > > > > 
> > > > > > 问题是, 做单臂路由器, 还是要配置交换机或者无线路由器,以提供Wi-Fi和有线给其他设备. 那么这样想: 反正所需的设备都是一样的, 我不如N1做简单的旁路, 让无线路由器负责拨号, 无线路由器不要刷机, 就用官方的固件.
> > > > > > 这样效率很高.
> > > > > 
> > > > > 
> > > > > 我现在就是 N1 旁路，主路由没有动，但就是解决不了安卓的问题……苹果（iOS、macOS ）一切安好
> > > > 
> > > > 
> > > > 远离 openwrt ...
> > > > https://github.com/cattyhouse/N1-install
> > > 
> > > 
> > > 您这个说实话理解有点费劲……是说先在一个 arm64 系统把 Archlinux 装到 U 盘，然后再弄到 N1 的 EMMC 吗？于是 N1 运行 Archlinux 而不是 Armbian？为什么不直接用 Armbian？另外之后呢，按这个指南做成旁路由吗？
> > 
> > 
> > 直接用 armbian 就行了。
> 
> 我觉得似乎加一个 docker 更好，这样随便折腾也不会有事，不动 Armbian

当然怎么搞都行，只是我个人不熟悉 docker。

**Comment by cattyhouse** [comment]
openwrt 内置的iptables表太多了. openwrt 模块不全, openwrt 是个精简版的linux. 所以 openwrt 配合 ss-tproxy兼容性不是很好.

**Comment by pizzamx** [comment]
> 
> 
> openwrt 内置的iptables表太多了. openwrt 模块不全, openwrt 是个精简版的linux. 所以 openwrt 配合 ss-tproxy兼容性不是很好.

那我试试看在 docker 里面弄个 archlinux 哈，谢谢

**Comment by elvisw** [comment]
> openwrt 内置的iptables表太多了. openwrt 模块不全, openwrt 是个精简版的linux. 所以 openwrt 配合 ss-tproxy兼容性不是很好.

我就是用的原版的OpenWRT，运行在Hyper-V虚拟机下面，使用没啥大问题，就是和部分插件不兼容，比如mwan之类的

**Comment by elvisw** [comment]
你这个报错是不是因为没装这个包导致的
https://openwrt.org/packages/pkgdata/iptables-mod-extra

**Comment by zfl9** [comment]
@pizzamx 可以试下 @elvisw  说的这个包，我看里面有提到 addrtype 匹配模块。

**Comment by pizzamx** [comment]
> 
> 
> @pizzamx 可以试下 @elvisw 说的这个包，我看里面有提到 addrtype 匹配模块。

系统已经被我铲掉了，要是再碰到我试试看哈，谢谢各位大佬
