### ISSUE TITLE
请教虚拟机安装ss-tproxy做网关的问题

### ISSUE THREAD

**Issue by ppmmaiwo** [zfl9/ss-tproxy#84]
感谢@zfl9 的无私奉献。
教程有提到：

> ss-tproxy 是否可以运行在虚拟机中
可以。以 VMware 为例，只需将网络设为 桥接模式 即可，这样这台虚拟机就接入了当前网络，与物理机没有区别。我在公司就是这样用的。

环境：
MacBook，虚拟机 Parallels ，虚拟机系统 ubuntu 16.4，网卡桥接。ss-tproxy全局模式

问题：
macbook在Wi-Fi模式下，虚拟机能科学上网，tcp和udp均正常。局域网的其他机器，设置路由和dns为虚拟机ip，连接网络失败。用其他机器dig测试，虚拟机dns服务正常。
经过尝试，换type-c hub，关闭无线，接网线。ss-proxy能正常工作，局域网网其他机器能通过虚拟机上网。

请教这个问题有解决方案么？很多场景只有Wi-Fi信号，插网线不方便。
虚拟机尝试过 Parallels、VMware、VirtualBox，透明代理均失败。还尝试过用mini路由器的clicent模式，把wi-fi信号转为有线，同样失败。

网上寻找相关资料，只找到一篇 https://www.virtualbox.org/manual/ch06.html#network_bridged 提到 most wireless adapters do not support promiscuous mode。

**Comment by lisaac** [comment]
可以尝试docker+ipvlan
自己没测试过，应该可解决这个问题

**Comment by ppmmaiwo** [comment]
> 可以尝试docker+ipvlan
> 自己没测试过，应该可解决这个问题

这个docker是大佬你建的么？https://hub.docker.com/r/lisaac/tproxy-gateway
这个是macvlan模式，ipvlan应该用L2模式吧？
docker小白，从头看文档，摊手🤷‍♂️等大佬的 docker hub

**Comment by zfl9** [comment]
我自己也遇到这个问题，暂时不知道解决办法，只有插网线才能用虚拟机桥接。。。

**Comment by lisaac** [comment]
> > 可以尝试docker+ipvlan
> > 自己没测试过，应该可解决这个问题
> 
> 这个docker是大佬你建的么？https://hub.docker.com/r/lisaac/tproxy-gateway
> 这个是macvlan模式，ipvlan应该用L2模式吧？
> docker小白，从头看文档，摊手等大佬的 docker hub

嗯，这个是之前ss-tproxy v3时候搞的，目前我自己还在用
我也没用过ipvlan，周末抽空试一下

**Comment by zfl9** [comment]
https://jingyan.baidu.com/article/948f59242e601dd80ff5f929.html
@ppmmaiwo  我没尝试过，但是感觉有用。

**Comment by zfl9** [comment]
> most wireless adapters do not support promiscuous mode

我也看到过这些，但不是很明白，桥接和网卡的混杂模式有什么关联。
