### ISSUE TITLE
修改了 v2 配置后，域名无法解析

### ISSUE THREAD

**Issue by pizzamx** [zfl9/ss-tproxy#85]
因为服务器变动，改了 v2 的配置，然后重启了若干次 v2 以及 ss-tproxy，都没法用了……不知道如何排查？

`#ss-tproxy status`
`RTNETLINK answers: Address family not supported by protocol`
`Dump terminated`
`mode:     chnroute`
`pxy/tcp:  [running]`
`pxy/udp:  [running]`
`dnsmasq:  [running]`
`chinadns: [running]`

`#curl google.com`
`curl: (6) Could not resolve host: google.com`

`#dig google.com`
`; <<>> DiG 9.14.7 <<>> google.com`
`;; global options: +cmd`
`;; connection timed out; no servers could be reached`

**Comment by zfl9** [comment]
重启系统？话说如果你只是单纯改了 v2ray 的配置的话，那么就是配置有问题了。

**Comment by zfl9** [comment]
v2ray 的日志呢？配置呢？ss-tproxy的配置呢？等等？

**Comment by pizzamx** [comment]
> v2ray 的日志呢？配置呢？ss-tproxy的配置呢？等等？

重启没用，v2 日志里只有这个，不过我看了下之前正常的时候也有，应该是另外的问题：

` v2ray.com/core/transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:60080: accept4: too many open files`

ss-tproxy 的配置没动
