### ISSUE TITLE
如何在路由器上设置？

### ISSUE THREAD

**Issue by JayceYang** [zfl9/ss-tproxy#88]
非常感谢作者的贡献，我已在Ubuntu 14.04上搭建成功了，本机可以科学上网。
但不知道怎么设置路由器的DNS以及网关以实现局域网内所有主机都科学上网？还望大神不吝赐教。
路由器都是ASUS，刷了梅林固件。
我尝试过将路由器LAN里面的DNS以及DHCP的默认网关设置为Ubuntu代理网关的IP，都不行，具体表现为：
1. 仅仅设置DNS的话：国内网站可以访问、国外网站不可访问；
2. 只要设置了默认网关，不管有没有设置DNS：路由器内所有主机（包含Ubuntu代理网关），国内外都不可访问。

另外，反馈一个奇怪的问题：
ss-tproxy status显示dnsmasq为stopped，但是sudo ss-tproxy status显示dnsmasq却为running。

**Comment by JayceYang** [comment]
贴上，一些配置：
【ss.json】
{
        "server":"xxx",
        "server_port":xxx,
        "local_address": "0.0.0.0",
        "local_port":1080,
        "password":"xxx",
        "method":"aes-256-gcm",
        "no_delay": true,
        "fast_open": true,
        "reuse_port": true
}

【ss-tproxy.conf】
## mode
#mode='global'  # global 模式 (不分流)
mode='gfwlist' # gfwlist 模式 (黑名单)
#mode='chnroute' # chnroute 模式 (白名单)

## ipv4/6
ipv4='true'     # true:启用ipv4透明代理; false:关闭ipv4透明代理
ipv6='false'    # true:启用ipv6透明代理; false:关闭ipv6透明代理

## tproxy
tproxy='false'  # true:TPROXY+TPROXY; false:REDIRECT+TPROXY

## tcponly
tcponly='false' # true:仅代理TCP流量; false:代理TCP和UDP流量

## selfonly
selfonly='false' # true:仅代理本机流量; false:代理本机及"内网"流量

## proxy
proxy_svraddr4=(xxx) # 服务器的 IPv4 地址或域名，允许填写多个服务器地址，空
格隔开
proxy_svraddr6=()        # 服务器的 IPv6 地址或域名，允许填写多个服务器地址，空格隔开
proxy_svrport='xxx'   # 服务器的监听端口，可填多个端口，格式同 ipts_proxy_dst_port
proxy_tcpport='1080'    # ss/ssr/v2ray 等本机进程的 TCP 监听端口，该端口支持透明代理
proxy_udpport='1080'    # ss/ssr/v2ray 等本机进程的 UDP 监听端口，该端口支持透明代理
proxy_startcmd='(ss-redir -c /etc/ss.json -u </dev/null &>>/var/log/ss-redir.log &)'     # 用于启动本机代理进程的 shell 命令，该命令应该能立即执行完毕
proxy_stopcmd='kill -9 $(pidof ss-redir)'      # 用于关闭本机代理进程的 shell 命令，该命令应该能立即执行完毕

## dns
dns_direct='114.114.114.114'          # 本地 IPv4 DNS，不能指定端口，也可以填组织、公司内
部 DNS
dns_direct6='240C::6666'              # 本地 IPv6 DNS，不能指定端口，也可以填组织、公司内
部 DNS
dns_remote='8.8.8.8#53'               # 远程 IPv4 DNS，必须指定端口，提示：访问远程 DNS 会走代理
dns_remote6='2001:4860:4860::8888#53' # 远程 IPv6 DNS，必须指定端口，提示：访问远程 DNS 会走代理

## dnsmasq
dnsmasq_bind_port='5300'                  # dnsmasq 服务器监听端口，见 README
dnsmasq_cache_size='4096'               # DNS 缓存大小，大小为 0 表示禁用缓存
dnsmasq_cache_time='3600'               # DNS 缓存时间，单位是秒，最大 3600 秒
dnsmasq_log_enable='false'              # 记录详细日志，除非进行调试，否则不建议启用
dnsmasq_log_file='/var/log/dnsmasq.log' # 日志文件，如果不想保存日志可以改为 /dev/null
dnsmasq_conf_dir=()                     # `--conf-dir` 选项的参数，可以填多个，空格隔开
dnsmasq_conf_file=()                    # `--conf-file` 选项的参数，可以填多个，空格隔开
dnsmasq_conf_string=()                  # 自定义配置，一个数组元素就是一行配置，空格隔开

## chinadns
chinadns_bind_port='65353'               # chinadns-ng 服务器监听端口，通常不用改动
chinadns_timeout='3'                     # 等待上游 DNS 返回响应的超时时间，单位为秒
chinadns_repeat='1'                      # 向可信 DNS 发送几次 DNS 查询请求，默认为 1
chinadns_fairmode='false'                # 使用公平模式，具体看 chinadns-ng 的 README
chinadns_gfwlist_mode='false'            # gfwlist 模式，加载 gfwlist.txt/gfwlist.ext
chinadns_noip_as_chnip='false'           # 启用 chinadns-ng 的 `--noip-as-chnip` 选项
chinadns_verbose='false'                 # 记录详细日志，除非进行调试，否则不建议启用
chinadns_logfile='/var/log/chinadns.log' # 日志文件，如果不想保存日志可以改为 /dev/null
chinadns_privaddr4=()                    # IPv4 私有地址段，多个用空格隔开，具体见 README
chinadns_privaddr6=()                    # IPv6 私有地址段，多个用空格隔开，具体见 README

## dns2tcp
dns2tcp_bind_port='65454'               # dns2tcp 转发服务器监听端口，如有冲突请修改
dns2tcp_verbose='false'                 # 记录详细日志，除非进行调试，否则不建议启用
dns2tcp_logfile='/var/log/dns2tcp.log'  # 日志文件，如果不想保存日志可以改为 /dev/null

## ipts
ipts_if_lo='lo'                 # 环回接口的名称，在标准发行版中，通常为 lo，如果不是请修
改
ipts_rt_tab='233'               # iproute2 路由表名或表 ID，除非产生冲突，否则不建议改动该选项
ipts_rt_mark='0x2333'           # iproute2 策略路由的防火墙标记，除非产生冲突，否则不建议
改动该选项
ipts_set_snat='false'           # 设置 iptables 的 MASQUERADE 规则，布尔值，`true/false`，详见 README
ipts_set_snat6='false'          # 设置 ip6tables 的 MASQUERADE 规则，布尔值，`true/false`
，详见 README
ipts_reddns_onstop='true'       # ss-tproxy stop 后，是否将其它主机发至本机的 DNS 重定向至直连 DNS，详见 README
ipts_proxy_dst_port='1:65535'   # 黑名单 IP 的哪些端口走代理，多个用逗号隔开，冒号为端口范围(含边界)，详见 README

## opts
opts_ss_netstat='auto'                  # auto/ss/netstat，用哪个端口检测命令，见 README
opts_overwrite_resolv='false'           # true/false，定义如何修改 resolv.conf，见 README
opts_ip_for_check_net='114.114.114.114' # 用来检测外网是否可访问的 IP，该 IP 需要允许 ping

## file
file_gfwlist_txt='/etc/ss-tproxy/gfwlist.txt'      # gfwlist 黑名单文件 (默认规则)
file_gfwlist_ext='/etc/ss-tproxy/gfwlist.ext'      # gfwlist 黑名单文件 (扩展规则)
file_chnroute_set='/etc/ss-tproxy/chnroute.set'    # chnroute 地址段文件 (iptables)
file_chnroute6_set='/etc/ss-tproxy/chnroute6.set'  # chnroute6 地址段文件 (ip6tables)
file_dnsserver_pid='/etc/ss-tproxy/.dnsserver.pid' # dns 服务器进程的 pid 文件 (shell)

日志没看到异常

**Comment by zfl9** [comment]
> 我尝试过将路由器LAN里面的DNS以及DHCP的默认网关设置为Ubuntu代理网关的IP，都不行

步骤1：ss-tproxy主机手动配置IP地址信息（网关、DNS等），即不要使用 DHCP 自动配置。
步骤2：再修改路由器的默认网关和DNS服务器配置，这样才不会导致ss-tproxy主机无法上网。

**Comment by zfl9** [comment]
> 步骤1：ss-tproxy主机手动配置IP地址信息（网关、DNS等），即不要使用 DHCP 自动配置。

ss-tproxy 主机的网关和 DNS 原来是什么就填什么，不要指向自己，这样会死循环。
路由器上指定的默认网关和DNS则应该为ss-tproxy主机的IP地址，这个地址建议固定。

**Comment by zfl9** [comment]
@JayceYang

**Comment by JayceYang** [comment]
厉害啊，一下子就帮我解决了。
非常感谢啊！！！

**Comment by sunduda** [comment]
> 
> 
> > 步骤1：ss-tproxy主机手动配置IP地址信息（网关、DNS等），即不要使用 DHCP 自动配置。
> 
> ss-tproxy 主机的网关和 DNS 原来是什么就填什么，不要指向自己，这样会死循环。
> 路由器上指定的默认网关和DNS则应该为ss-tproxy主机的IP地址，这个地址建议固定。

您好，请教一下关于ss-tproxy手动设置DNS的问题：在改网关和DNS之前，`cat /etc/resolv.conf`和`nslookup www.baidu.com`两个命令输出的DNS结果是127.0.0.1，但您又说”不要指向自己“，请问意思是不是设置成任意公共DNS就行？

**Comment by zfl9** [comment]
是的

**Comment by sunduda** [comment]
> 
> 
> 是的

多谢大神！
