### ISSUE TITLE
请问是否考虑加入大陆地址黑名单模式，即只对大陆地址使用代理？

### ISSUE THREAD

**Issue by ideepblue** [zfl9/ss-tproxy#9]
我这里计划假设从国外往国内的ss代理，所以需求是搭梯子的往国内的代理。

**Comment by zfl9** [comment]
翻进国内需要解决DNS问题吗？

**Comment by zfl9** [comment]
还是只需要代理 IP 就行？

**Comment by ideepblue** [comment]
能否有两个版本，一个是用国内dns解析，一个是不带的，仅有代理IP。我也不是很确定。我也得需要试试看。毕竟有些国内服务商，比如腾讯会有国外服务器镜像。我想用这个透明代理是因为我人在国外，想在家里树莓派搞一个透明代理，解决有些app仅大陆访问的问题。我自己会搞一个阿里云作为ss-server。

**Comment by zfl9** [comment]
我稍微了解了一下“反向翻墙”（国外翻回国内），国外 IP 访问国内的 视频、音乐、直播 等 APP、网站会提示“仅限中国大陆地区用户使用”。

反向翻墙建议使用 gfwlist 模式，不过，需要进行一些额外的步骤：
1. 一台大陆 IP 的 SS/SSR VPS 或付费账号（废话）
1. 清空 `/etc/tproxy/gfwlist.txt` 文件，`true >/etc/tproxy/gfwlist.txt`
2. 将国外无法访问的域名加入到 `/etc/tproxy/gfwlist.txt` 黑名单文件
3. 如优酷 `echo 'youku.com' >>/etc/tproxy/gfwlist.txt`，其它的类似
5. 修改 `/etc/tproxy/ss-tproxy.conf` 配置文件中的 DNS 服务器，具体的
 - `dns_remote`：改为 `114.114.114.114:53` 或其它常用的国内 DNS 服务器
 - `dns_direct`：改为 `8.8.8.8 8.8.4.4` 或其它常用的国外 DNS 服务器
4. 启动 ss-tproxy，`ss-tproxy start`，切记不可 `ss-tproxy update-gfwlist`

**Comment by ideepblue** [comment]
多谢，我抽时间试一下。稍后给你反馈，我也就今天突然看到你这个工作，非常感兴趣。或许我可以贡献一些。

**Comment by ideepblue** [comment]
之前工作太忙今天部署了一下ss-tproxy确实十分优秀和易用。

我仔细读了一下你给出的文档，我想了想可能最适合的“反向翻墙”（仅对中国大陆地址代理）应该更符合这样的设置：
```
tproxy_chnonly
# DNS(!chnroute): dnsmasq/53 -> 8.8.8.8
# DNS(=chnroute): dnsmasq/53 -> 114.114.114.114
# DNS(=chnroute): dnsmasq/53 -> ss-tunnel/60053 (或者走ss)
# TCP(!chnroute): 原网络直连
# TCP(=chnroute): ss-redir/60080
# UDP(!chnroute): 原网络直连
# UDP(=chnroute): ss-redir/60080
# dnsmasq: 监听 53/udp，DNS 缓存
# ss-redir: 监听 60080/tcp+udp，代理 TCP/UDP
```

另外，关于中国大陆的ip也是有更新的源，比如<https://github.com/17mon/china_ip_list>和<https://github.com/LisonFan/china_ip_list>。

我对dnsmasq和iptables有了解，但是没怎么实操过。大概还需要几天时间读一下你的代码，然后添加这一部分。不知你有没有什么建议？
