### ISSUE TITLE
resolve_hostname4/6 edge cases

### ISSUE THREAD

**Issue by qip** [zfl9/ss-tproxy#90]
配置文件中 `proxy_svraddr4` 的注释描述为：
>服务器的 IPv4 地址或域名，允许填写多个服务器地址，空格隔开

而实际上，即使填入的是 ip 地址，也会在 `resolve_svraddr` 这一步执行 `resolve_hostname4`。
`resolve_hostname4` 的原理是利用 `ping` 返回服务器解析后的地址，有两个问题均与这个实现有关：
- `proxy_svraddr4` 中填入大量 ip 地址/域名时，即使只是 ip 地址也会消耗相当长的时间等待 `resolve_hostname4` 执行完 - 事实上，不需解析可以直接返回 ip 地址就好。稍微加个正则（不严格）可以解决这个问题：
```
resolve_hostname4() {
    local ipaddr=""
    if [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo "$1"
    else
        while [ -z "$ipaddr" ]; do
            ipaddr=$(ping -nq -c1 -t1 -W1 "$1" | head -n1 | gawk -F'[()]' '{print $2}')
            [ -z "$ipaddr" ] && sleep 1
        done
    fi
    echo "$ipaddr"
}
```
至于大量域名，`dig` 提供相对较快速的批量解析，形如 `dig +short A -f server_list.txt`。（也意味着多一个 bind-utils/dnsutils 依赖）
- `proxy_svraddr4` 中含有不返回 ICMP 请求的服务器时将陷入死循环。
如果是填入的 ip 地址有这个问题可以参考上一点第一部分（即直接返回 ip 地址），而如果填入的是域名可以参考上一点第二部分使用 DNS 解析工具而不依靠 `ping`。

`resolve_hostname6` 同理。

**Comment by zfl9** [comment]
> proxy_svraddr4 中含有不返回 ICMP 请求的服务器时将陷入死循环。

实际上这里的 ping 用法不关心目标主机是否响应 ICMP 消息，我不知道你说的陷入死循环是什么情况，请详细举例说明。

**Comment by zfl9** [comment]
> 至于大量域名，dig 提供相对较快速的批量解析

![image](https://user-images.githubusercontent.com/22726048/68726616-ffd0e880-05fc-11ea-8b24-c5e173437be8.png)

**Comment by zfl9** [comment]
dig解析当然更加“自然”，但是我并不想引入非必要的依赖，使用ping足矣应付。

**Comment by zfl9** [comment]
> 即使只是 ip 地址也会消耗相当长的时间等待。

请详细举例说明（如 time 测试解析时间？），这里确实忘记了优化，加个 `is_ipv4_address $1` 过滤就可以了，不必另写正则，前面其实有了对应的判断函数。

**Comment by qip** [comment]
感谢回复。

> 实际上这里的 ping 用法不关心目标主机是否响应 ICMP 消息，我不知道你说的陷入死循环是什么情况，请详细举例说明。
回头看了我的命令历史，这是我单独测试时使用不同命令参数的误报（眼花把 `-W1` 敲成了 `-m1` ）。

> image
毫秒级正确解析 www.google.com 如果不是主机在外那就应该是因为目标在缓存。
顺便合并
> 请详细举例说明（如 time 测试解析时间？）
截图如下：
![image](https://user-images.githubusercontent.com/1027432/68738143-86e38800-0620-11ea-9503-22c86beb4a5d.png)
补充说明：在执行上述命令前，我刚在该主机上通过 192.168.1.1 （即网关，其 DNS 服务缓存并转发自 ISP 下发的 DNS 服务器，通常响应速度在 5 ms 内）解析了 amazon.com, baidu.com 两个域名。其余域名中我确定 u.ctrip.com 一定不在任何缓存中。
不确定为何同样执行 ping 命令跟你的测试耗时差距甚远，每次 ping 命令耗时均达一秒。我尝试时使用了超过 140 个不同 IPv4 地址，启动服务等待（显而易见地）超过两分钟。
题外话，升级到 4.0 版本后，虽然可以与 3.x 版本相同不显著增加耗时地利用 `ipset` 额外添加至 chnroute 的，不过遵从配置结构把服务器地址放到 `proxy_svraddr4` 我（拖延到现在）改写才发现这个问题。

**Comment by cattyhouse** [comment]
我目前用的方法:
````
dig +timeout=5 +tries=5 +short @114.114.114.114 example.com | tail -n1
````

几点说明:
- 固定114去解析, 可以不用理会 /etc/resolv.conf 的配置
- 增加 timeout 和 tries 提高容错率, 有时候 114 可能瞬间抽风.
- 增加 tail -n1, 因为有的域名 dig 出来后会出现多个结果, 最后一个必定是 ip, 例如 `dig @114.114.114.114 www.zfl9.com A +short`

**Comment by zfl9** [comment]
有些版本的ping确实有等待1秒钟的问题，看来有必要加个选项，选择“域名解析器”了。目前个人了解的有这么几个解析域名的实用工具：
- ping
- dig
- host
- nslookup
- getent

**Comment by zfl9** [comment]
加了个选项，`opts_hostname_resolver`，默认 auto，优先级：`dig`、`getent`、`ping`。
