### ISSUE TITLE
dns2tcp 找不到

### ISSUE THREAD

**Issue by jackjin-cn** [zfl9/ss-tproxy#96]
[ERROR] command not found: dns2tcp

git pull 最新版的时候出现这个问题，用老版没有问题。

我的是deepin 15.
安装sudo apt-get install dns2tcp后
系统只有dns2tcpc dns2tcpd这两个命令。
我看了一下ss-sproxy 里，好像是dns2tcp
请问如何解决，谢谢

**Comment by zfl9** [comment]
@jackjin-cn 
你用的是 tcponly 模式？
如果是的话，那么请安装 <https://github.com/zfl9/dns2tcp>。

**Comment by zfl9** [comment]
如果不是用的 tcponly 模式，那么就是你的 ss-tproxy.conf 配置文件某些配置项缺少了，请对比仓库里面的 ss-tproxy.conf，将缺少的补上去。

**Comment by zfl9** [comment]
```shell
## tcponly
tcponly='false' # true:仅代理TCP流量; false:代理TCP和UDP流量
```
如果此行配置为 true，那么就需要 dns2tcp 转换工具（注意不是apt-get安装的那个），虽然重名。。

**Comment by jackjin-cn** [comment]
谢谢批点。是配置文件有新增项，偷懒没有改。不好意思。
