### ISSUE TITLE
建议加入黑白名单

### ISSUE THREAD

**Issue by lisaac** [zfl9/ss-tproxy#97]
首先感谢作者的辛勤付出！

使用中有时候会出现某些<IP/域名>需要被放行或代理。如果只是用一种模式，这些名单相对较容易维护，如果切换模式则会比较麻烦。
现在 gfwlist 已经有相关的 gfwlist.ext 来补充黑名单，所以能否加入<全局黑名单/白名单>，来控制所有模式中的访问控制。

当然，如果再加入 LAN 侧的访问控制的话，更是极好的，就不用挂钩子了

**Comment by zfl9** [comment]
可以应该是可以，但是目前没有太多精力做这些。

**Comment by zfl9** [comment]
打算先解决 ipt2socks 的几个问题，ss-tproxy 可能推迟一段时间搞。

**Comment by zfl9** [comment]
lan 侧的访问控制感觉略微复杂。全局黑白名单这个已经加了。先关了~

**Comment by zfl9** [comment]
#106 先标记一下。
