### ISSUE TITLE
建议使用ping6 代替ping -6

### ISSUE THREAD

**Issue by tiehichi** [zfl9/ss-tproxy#98]
经过测试发现脚本在`ubuntu 16.04`上运行的时候会异常退出，原因是`ubuntu 16.04`上面的`ping`不支持`-4`、`-6`参数，`ping` ipv6的地址需要使用`ping6`来实现。

在`centos 7`和`ubuntu 18.04`上，`ping6`都是一个指向`ping`的软链接，而在`ubuntu 16.04`上是单独的一个二进制，既然这些系统上都有`ping6`，是否可以考虑使用`ping`和`ping6`而不是参数来提高兼容性呢

**Comment by zfl9** [comment]
你是在解析 dns 的时候报错退出的？还是检查网络是否 ready 时退出的？

**Comment by tiehichi** [comment]
应该是在检查网络时，我修改了`waiting_network `函数里面的ping的使用，但是`resolve_hostname_by_ping`我没改过，应该没有执行到这里

**Comment by zfl9** [comment]
> 经过测试发现脚本在`ubuntu 16.04`上运行的时候会异常退出，原因是`ubuntu 16.04`上面的`ping`不支持`-4`、`-6`参数，`ping` ipv6的地址需要使用`ping6`来实现。
> 
> 在`centos 7`和`ubuntu 18.04`上，`ping6`都是一个指向`ping`的软链接，而在`ubuntu 16.04`上是单独的一个二进制，既然这些系统上都有`ping6`，是否可以考虑使用`ping`和`ping6`而不是参数来提高兼容性呢

不一定都这样，比如我的 archlinux，就没有 ping4、ping6。只有 ping -6/4

**Comment by zfl9** [comment]
我感觉不如加个选项，禁用网络检查算了。

**Comment by tiehichi** [comment]
我是想尽量兼容现在的逻辑，加个针对`ping6`的检查，如果`ping6`不存在才使用`-6`选项

**Comment by zfl9** [comment]
> 我是想尽量兼容现在的逻辑，加个针对`ping6`的检查，如果`ping6`不存在才使用`-6`选项

这样也好，如果有 ping6 就用 ping6，没有就用 ping -6

**Comment by zfl9** [comment]
但是，-4 呢。

**Comment by tiehichi** [comment]
刚去确认了一下确实是个问题，`ping6`为软链接的时候，直接使用`ping`还是会去使用v6的地址，需要加上`-4`参数才行，容我想想方法

**Comment by tiehichi** [comment]
使用`readlink`去检查一下`ping6`是否为软链接是否可行？
``` bash
# ubuntu 18.04
~$ readlink /bin/ping6 
ping
~$
```

``` bash
# ubuntu 16.04
~$ readlink /bin/ping6
~$
```

**Comment by cattyhouse** [comment]
> 使用`readlink`去检查一下`ping6`是否为软链接是否可行？
> 
> ```shell
> # ubuntu 18.04
> ~$ readlink /bin/ping6 
> ping
> ~$
> ```
> 
> ```shell
> # ubuntu 16.04
> ~$ readlink /bin/ping6
> ~$
> ```

readlink -f $(command -v ping)

**Comment by zfl9** [comment]
见最新提交。
